### ISSUE TITLE
About inpaint_ops.py#L283

### ISSUE THREAD

**Issue by dragonkao730** [JiahuiYu/generative_inpainting#10]
Hi, JiahuiYu

Thank you for your contribution and release those code!
I have a question about `inpaint_ops.py#L283`,
`xi` should be normed?

您好根據您的 paper, `xi` 是否應該也要 normed?
另外你的 work 非常有趣!

Thanks!

**Comment by JiahuiYu** [comment]
The `xi` should be normed mathematically but here is a trick for speedup: for computing best match of some patch `xi`, all distances should divide same `norm(xi)`. Thus the normalization of `xi` can be saved.

**Comment by dragonkao730** [comment]
It’s clear to me now.
👍
