### ISSUE TITLE
About the loss function

### ISSUE THREAD

**Issue by han-qiu** [JiahuiYu/generative_inpainting#100]
Hi, There is `GRAMS_LOSS_ALPHA` in inpaint.yml. So I'm curious, did you tried the style loss (as in the partial convolution paper) on your model? or maybe deepfill2? If so, what's the effect of the style loss?

**Comment by JiahuiYu** [comment]
I have tried style loss during development of DeepFill v1. Personally I cannot find any improvement except slowing down the training speed, especially when you have a good GAN loss (e.g., WGAN-GP in DeepFill v1). Thus it is not used in both DeepFill v1 and v2.

**Comment by TerminatorSd** [comment]
Hi, JiahuiYu. I have two questions about GRAMS_LOSS and FEATURE_LOSS:
1. If I only modify inpaint.yml including set them true and provide the VGG_MODEL_FILE, will the training process add these two losses automatically?
```
LOAD_VGG_MODEL: True
VGG_MODEL_FILE: vgg/vgg16_weights.npz
FEATURE_LOSS: True
GRAMS_LOSS: True
```
2. If it works, how should i modify the function **build_graph_with_losses** in inpaint_model.py to log them on tensorboard?

**Comment by JiahuiYu** [comment]
They are not included in code. That’s the legacy during my earlier development.

**Comment by TerminatorSd** [comment]
So how should I update the code if I want to use them?

**Comment by JiahuiYu** [comment]
Hi,

You will need to read and understand the code first.

**Comment by TerminatorSd** [comment]
OK, thanks a lot.
