### ISSUE TITLE
about neuralgym

### ISSUE THREAD

**Issue by Irvingwangjr** [JiahuiYu/generative_inpainting#101]
hi jianhui,sorry to bother you again. we are in the image is none problem,and we check our path very carefully,and if we directly use cv2.imread(), the pictures load successfully
![r75yca mm6 r g7 pzq87](https://user-images.githubusercontent.com/32162780/43366015-ab1e6266-9368-11e8-8c94-74e3a30ec9c6.png)
after checking the code in the  data_from_fnames.py, 
![image](https://user-images.githubusercontent.com/32162780/43366029-e097ef34-9368-11e8-9f01-00333609768c.png)
![r e70s2buo8r6 skg s6i t](https://user-images.githubusercontent.com/32162780/43366056-79442bda-9369-11e8-83e6-763181bf70f0.png)

so i was wondering the problem might be here cause the fnamelist we send is a list,and this func will change it into a ("image.png",)tuple, then cause the problem.

we still can't solve it, would you please help us?
thanks for your time

**Comment by JiahuiYu** [comment]
@Irvingwangjr Have you solved the problem? If so, may I know what's the reason?

**Comment by Irvingwangjr** [comment]
we made a silly mistake,the memory was full so some of the image can't load into to it.
BTW.your works are so good and i am trying to develop an android app base on your paper. 
i have a question about your load model part, from the test.py ,it seems you create the inpaint net every time rather than load from the .META file directly. May i ask why? cause i am trying to make those four file into one .pb file, and i still not fully understand how you save the model and load it

**Comment by JiahuiYu** [comment]
@Irvingwangjr Just a research development option.

**Comment by balablb** [comment]
> we made a silly mistake,the memory was full so some of the image can't load into to it.
> BTW.your works are so good and i am trying to develop an android app base on your paper.
> i have a question about your load model part, from the test.py ,it seems you create the inpaint net every time rather than load from the .META file directly. May i ask why? cause i am trying to make those four file into one .pb file, and i still not fully understand how you save the model and load it

how to free the memory ?
