### ISSUE TITLE
ImportError: No module named 'neuralgym'

### ISSUE THREAD

**Issue by NerminSalem** [JiahuiYu/generative_inpainting#102]
Hello,
Thanks for sharing the code. So, after I clone the repo, I downloaded the pretrained models for  CelebA and tried running the test.py code (Tensorflow version:1.6.0). I created a folder model_logs and placed all the files of the downloaded pre-trained model in that folder.
I run using the command:
python3 test.py --image examples/celeba/celebahr_patches_164036_input.png --mask examples/center_mask_256.png --output examples/output.png --checkpoint_dir model_logs/
i got the following error: 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import neuralgym as ng
ImportError: No module named 'neuralgym'
 although i installed neuralgym using :
pip install git+https://github.com/JiahuiYu/neuralgym
and the output is:

/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Collecting git+https://github.com/JiahuiYu/neuralgym
  Cloning https://github.com/JiahuiYu/neuralgym to /tmp/pip-req-build-dWpUvh
Requirement already satisfied (use --upgrade to upgrade): neuralgym==0.0.1 from git+https://github.com/JiahuiYu/neuralgym in /home/nermin/.local/lib/python2.7/site-packages
Building wheels for collected packages: neuralgym
  Running setup.py bdist_wheel for neuralgym ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-B8JcDK/wheels/bc/dd/bc/fbaacf774dfc69223a01b3e037b8539f24318193a37221bb3b
Successfully built neuralgym
so how to install neuralgym correctly? as apparently the program can't find it

**Comment by michaelbironneau** [comment]
`pip install git+https://github.com/JiahuiYu/neuralgym`

**Comment by michaelbironneau** [comment]
Yes, or if you don't have `pip3` then try `git clone https://github.com/JiahuiYu/neuralgym && cd neuralgym && python3 setup.py install`.

**Comment by NerminSalem** [comment]
Thanks alot for yr Help 
I will try it
