### ISSUE TITLE
About training and testing user-guided inpainting

### ISSUE THREAD

**Issue by mychina75** [JiahuiYu/generative_inpainting#108]
Dear Jiahui,
thanks a lot for your great work first.
I am not sure about the process of training/testing user-guided inpainting. 
Is it enough to just add a user-guided sketch channel in training/testing?  any additional loss function needed?
and in training, use full HED edged image or masked HED edged image? how about in testing?

Thank you~

**Comment by JiahuiYu** [comment]
@mychina75 Hi, first thanks for your interest. We only use masked regions of HED edges for training. During testing, users only draw in the masked regions as well.

**Comment by mychina75** [comment]
Hi, @JiahuiYu 
one more question, why do you use masked regions of HED edges for training? 
In my understanding, full image of edges should learn more matching between edges and original image.

**Comment by JiahuiYu** [comment]
@mychina75 But then you will also need to input full image of edges in testing, which has cost.

**Comment by mychina75** [comment]
ah, I see... 
Thank you. @JiahuiYu

**Comment by betterze** [comment]
very nice work. Just to make sure, the value of regular mask is 255, value of remained image part is 0. What about the value of user-guided part in the mask? Should it be 255 also?

**Comment by JiahuiYu** [comment]
User-guides version has not yet be released. And yes the value is also 255.

**Comment by betterze** [comment]
get it, thx a lot
