### ISSUE TITLE
about discriminator

### ISSUE THREAD

**Issue by dragonkao730** [JiahuiYu/generative_inpainting#11]
Hi, JiahuiYu

Can I ask for the discriminator ckpt file?

Thanks!

**Comment by JiahuiYu** [comment]
It is contained in ckpt file.

**Comment by dragonkao730** [comment]
Hi, JiahuiYu

I can not found discriminator variables in Place2 ...
I only found discriminator variables CelebA-HQ

Thank you for the time and patience you devoted to reading my messages !

**Comment by dragonkao730** [comment]
Hi, Jiahui Yu:



Thanks for the update on the issue!

This is my email:
r05922122@ntu.edu.tw


Thank you for the quick reply!



________________________________
寄件者: JiahuiYu <notifications@github.com>
寄件日期: 2018年4月3日 下午 03:23
收件者: JiahuiYu/generative_inpainting
副本: 高以龍; Author
主旨: Re: [JiahuiYu/generative_inpainting] about discriminator (#11)


Hi, I see and it's my mistake. The reason is that internal model code for places2 has variable name misalignments with the released model code. I converted the generator but forgot to convert the discriminators.

I will fix this problem some time. If you are urgent please shot me an email and I can share with you the unconverted model. Thanks.
