### ISSUE TITLE
Hi, how does the size of the mask affect the training results? What effect is too big or too small?

### ISSUE THREAD

**Issue by Tingliangliang** [JiahuiYu/generative_inpainting#110]

**Comment by shenshenzhanzhan** [comment]
太大的mask可能导致剩余的信息不够使得修复结果不真实，太小的mask修复内容有限吧。

**Comment by JiahuiYu** [comment]
@Tingliangliang @shenshenzhanzhan  In general, if you want to inpainting the mask of size NxN during testing, you'd better train the network to inpaint around hole sizes of NxN. Usually small masks are easy to fill, larger masks than training ones will have worse performance.
