### ISSUE TITLE
About the results from pre_trained_checkpoint

### ISSUE THREAD

**Issue by guvcolie** [JiahuiYu/generative_inpainting#111]
Hi, thank you for your great work!
I run your test demo code(test.py), but the results looks not so good. It looks like there is a shift to right-bottom.
![imagenet_patches_ilsvrc2012_val_00000827_input](https://user-images.githubusercontent.com/16778790/44072940-096c4326-9fc4-11e8-818f-dc6dfb0de07f.png)
![center_mask_256](https://user-images.githubusercontent.com/16778790/44072949-13eed12e-9fc4-11e8-8e0a-1f2ac233bf0d.png)
![aa](https://user-images.githubusercontent.com/16778790/44072954-18b90198-9fc4-11e8-9574-8d4b5853779b.png)
![building_input](https://user-images.githubusercontent.com/16778790/44072970-2d40ab66-9fc4-11e8-94da-f5cf72453a9e.png)
![building_mask](https://user-images.githubusercontent.com/16778790/44072976-313d5458-9fc4-11e8-96ea-5123b906743b.png)
![aa](https://user-images.githubusercontent.com/16778790/44072989-41a0663c-9fc4-11e8-8db1-48795ba72fef.png)

I just follow your guide, "python3 test.py --image examples/places2/building_input.png --mask examples/places2/building_mask.png --output examples/output.png --checkpoint_dir model_logs/release_places2_256", do you know why?  thanks!

**Comment by JiahuiYu** [comment]
@guvcolie You are right. The image and mask are not aligned for some reason. Did you modify the `test.py`? Did you use opencv to read images? Which version of opencv did you use? What's the python version?

**Comment by guvcolie** [comment]
emm...   I  used  tf1.1 in python3, the tf version is so old. After updating, the result is correct! Thank you !
