### ISSUE TITLE
How to set IMG_SHAPES, HEIGHT, WIDTH when training places2

### ISSUE THREAD

**Issue by guvcolie** [JiahuiYu/generative_inpainting#114]
Thank you for your code!
Now I want to train the model by using Places2, how do I set IMG_SHAPES, HEIGHT, WIDTH, MAX_DELTA_HEIGHT, MAX_DELTA_WIDTH?

IMG_SHAPES: [**512, 680**, 3]
HEIGHT: **128**
WIDTH: **128**
MAX_DELTA_HEIGHT: 32
MAX_DELTA_WIDTH: 32

Is that right?  thanks!

**Comment by JiahuiYu** [comment]
@guvcolie
`IMG_SHAPES` means the size of images for training. Usually I use **256x256**.
`HEIGHT`, `WIDTH` means the maximum size of masks.
`MAX_DELTA_HEIGHT`, `MAX_DELTA_WIDTH` are used to increase size variation of masks. This means all the masks are within size of `HEIGHT`x`WIDTH` and `HEIGHT-MAX_DELTA_HEIGHT `x`WIDTH-MAX_DELTA_WIDTH `.

Hope it helps for you to understand.

**Comment by guvcolie** [comment]
@JiahuiYu   Got it! Thank you!
Have you tried to train a bigger model, such as one whose IMG_SHAPES is [512, 512, 3] ? I think that is more real than 256*256, right?

**Comment by JiahuiYu** [comment]
Larger size requires more memory consumption and longer convergence time. But anyway you could have a try.

**Comment by syomantak** [comment]
@JiahuiYu so based on the parameters set above, we will have some training but can we use a bigger mask (possibly not a rectangles as well) during inference?
