### ISSUE TITLE
How can I make random box into a specific box for each image? 

### ISSUE THREAD

**Issue by dreamay** [JiahuiYu/generative_inpainting#115]
I want to inpaint a special box in some images,and I get the location.I can change the function of random_bbox,but should  I change codes about the section of batch_data.I am confused.I need your help.Thank you. @JiahuiYu

**Comment by JiahuiYu** [comment]
@dreamay Yes. You will need to understand how batches are generated and fed into neural networks. See some reference code here:

https://github.com/JiahuiYu/generative_inpainting/blob/master/train.py#L41-L42
https://neuralgym.readthedocs.io/data.html

**Comment by dreamay** [comment]
Thank you for your reply.A batch_data does the same random_bbox,right?Can I make a batch of pictures same?
