### ISSUE TITLE
.../lib/python3.6/...neuralgym/ops/image_ops.py", import cv2: ImportError

### ISSUE THREAD

**Issue by jayjtao** [JiahuiYu/generative_inpainting#116]
1. When opencv was installed, it's 3.4.1 already;
2. When train.py was run, from neuralgym/ops/image_ops.py", got "import cv2: ImportError": /libopencv_dnn.so.3.4: undefined symbol: _ZNK6google8protobuf7Message25InitializationErrorStringB5cxx11Ev
3. uninstall opencv, reinstall "pip3 install opencv-python" did not help

Please help on how to avoid, thanks.
Jay

**Comment by JiahuiYu** [comment]
I use anaconda to install openCV. Previous I also have tried to compile openCV from source and it worked. Just for your references.
