### ISSUE TITLE
how to add own mask to own dataset

### ISSUE THREAD

**Issue by akshay951228** [JiahuiYu/generative_inpainting#120]
I thought input for training data is **two**,one is image and other one was mask like input in testing(test.py) 
but Its looks like only one input. I was confused 

I have dataset contains 
2 part 1 is mask other one is image
please help me.How to solve this problem

**Comment by JiahuiYu** [comment]
Currently I use random bounding box to support mask sampling. To support two inputs, you will need to modify data input part in inpaint_model.py

**Comment by Adhiyaman-Manickam** [comment]
@akshay951228 Hi. Have you got the answer about the issues. if so, can you explain to me. Because, I am starting now. I am also having same confusion.
