### ISSUE TITLE
Question about result of stage 1

### ISSUE THREAD

**Issue by annzheng** [JiahuiYu/generative_inpainting#122]
Hi，I am confused about the result of stage 1.
In your paper, the result of stage 1 is:
![screenshot](https://user-images.githubusercontent.com/21216944/44774595-14ff5a00-aba6-11e8-9959-c6ea471f61ff.png)

But, in the code, it is:
`# stage2, paste result as input`
 `x = x*mask + xin*(1.-mask)`
` x.set_shape(xin.get_shape().as_list())`

In my understanding，xin in code is x in paper, and x in code is G(z, m) in paper. I am very confused about this. Hope for your reply！

**Comment by JiahuiYu** [comment]
x in code is G(z, m), xin in code is x in paper. You are correct.

**Comment by annzheng** [comment]
Sorry, I didn't make the question clear. What I really confused is x in paper multiple m, but xin in code multiple (1-mask), it is opposite.

**Comment by annzheng** [comment]
Sorry, I didn't make the question clear. What I really confused is x in paper multiple m, but xin in code multiple (1-mask), it is opposite.

**Comment by JiahuiYu** [comment]
@annzheng To understand, we copy the input image outside mask and paste the generated image inside mask. So it is `input image outside mask + the generated image inside mask`.

**Comment by annzheng** [comment]
I can understand this. If the formula in paper means `input image outside mask + the generated image inside mask`, the code has the opposite meaning, which is  `input image inside mask + the generated image outside mask`. In my understanding, the meaning of code and formula in paper is opposite.

**Comment by JiahuiYu** [comment]
@annzheng You probably misunderstand the meaning of mask. https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/inpaint_model.py#L147

**Comment by annzheng** [comment]
Thanks for your reply. I’ve got it now. Maybe I misunderstand the meaning of you paper
![image](https://user-images.githubusercontent.com/21216944/44826705-a45a4b00-ac42-11e8-8c18-024020391667.png). Thanks! :)
