### ISSUE TITLE
MODEL_RESTORE seems not taken

### ISSUE THREAD

**Issue by jayjtao** [JiahuiYu/generative_inpainting#127]
trying to accumulate training results progressively:
 - did set inpaint.yml: MODEL_RESTORE accordingly
 - but everytimes when re-run "python train.py", it did not take the pre-trained model pointed by inpaint.yml: MODEL_RESTORE; instead, it produces a new log in the "model_logs"
 ? what's the condition that inpaint.yml: MODEL_RESTORE is not taking effects?
 ? was "progressively training" (on different sets of inputs) possible from current design?
Thanks,
Jay

**Comment by JiahuiYu** [comment]
@jayjtao Hi Jay, model restore is taking effects if you can see logs "restore parameters". But the new logs and models will be saved to a different dir to avoid confusion.
It is possible to run "progressive training" with current code.

**Comment by jayjtao** [comment]
Hi, JiaHui,


Thanks for the quick response and the help!

Jay
________________________________
寄件者: JiahuiYu <notifications@github.com>
寄件日期: 2018年9月8日 下午 11:41
收件者: JiahuiYu/generative_inpainting
副本: jayjtao; Mention
主旨: Re: [JiahuiYu/generative_inpainting] MODEL_RESTORE seems not taken (#127)


@jayjtao<https://github.com/jayjtao> Hi Jay, model restore is taking effects if you can see logs "restore parameters". But the new logs and models will be saved to a different dir to avoid confusion.
It is possible to run "progressive training" with current code.

**Comment by pancookie** [comment]
Thanks for the info!
I met the same issue. So I found out that you have to specify the absolute path instead of 'logs/[your-saved-model]'. Otherwise, tf.train.latest_checkpoint() return nothing for that. 

I am using TF 1.14.0
