### ISSUE TITLE
questions about random inpainting

### ISSUE THREAD

**Issue by micklexqg** [JiahuiYu/generative_inpainting#128]
hi, thanks for your work.
I note there are several different mask types used. I wonder that if the model is trained one time or trained each time for each mask type?
so can the trained model using random mask inpaint arbitrary broken image or only subject to the given mask type images?

**Comment by JiahuiYu** [comment]
The SINGLE model is trained with random masks, which means the SINGLE model can be used to fill MANY different masks at different locations. For more information, please have a read of our paper.

**Comment by micklexqg** [comment]
thanks for reply. it is good that the SINGLE model can be used to  fill MANY different masks at different locations. sorry for another puzzlement, can it inpaint  arbitrary broken images just like traditional methods? (maybe 'many' does not equal 'arbitrary')

**Comment by JiahuiYu** [comment]
@micklexqg The DeepFill v1 is mainly trained on rectangular masks. For arbitrary, please checkout our DeepFill v2, [Free-Form Image Inpainting with Gated Convolution](https://arxiv.org/abs/1806.03589).

**Comment by micklexqg** [comment]
thank you. last question, i note that the arbitrary inpainting is based on free-form masks generation. I wonder if there is a large-scale masks (maybe large-scale) , whether it increase the training iterations and time?

**Comment by JiahuiYu** [comment]
@micklexqg FYI, I use mini-batch size 24. I train it on Tesla V100 GPU, 16 GB VRAM for five days, with GPU utilization almost 100%.
