### ISSUE TITLE
VAL setting in inpaint.YML

### ISSUE THREAD

**Issue by jayjtao** [JiahuiYu/generative_inpainting#129]
Hi JiaHui,
1. When we run the train.py of generative Inpainting, should we keep the VAL setting in inpaint.YML as False? (and why?)
2. Does this code contain the changes foe the "version 2" implementation?
2.1 if yes, how should we handle the masks?
2.2 if not, where can we find the "version 2" implementation?
Thanks,
Jay

**Comment by JiahuiYu** [comment]
@jayjtao 

1. It depends on you. If you want to see validation results on tensorboard. Please set the VAL to true and prepare a validation image lists.
2. Please checkout issue #62 for more information.
