### ISSUE TITLE
Question about your paper

### ISSUE THREAD

**Issue by yinxiaochuan** [JiahuiYu/generative_inpainting#13]
Great work!
I have a question about the  STN-based attention for image inpainting (Fig. 8 in the paper). I wonder what the loss function of STN-based attention network is ? L1 or WGAN-GP + L1?  
Thank you.

**Comment by JiahuiYu** [comment]
It is identical for all other experiments (WGAN-GP + L1).

**Comment by yinxiaochuan** [comment]
@JiahuiYu Thank you for your reply！
