### ISSUE TITLE
Some questions about imagenet

### ISSUE THREAD

**Issue by ljjcoder** [JiahuiYu/generative_inpainting#130]
hi，dear  Jiahui! I notice that the name of your test image is *.png ,but the imagenet data is named *.jpeg. do you only change image's name from the jpeg to png or do some process on .jpeg to get the .png

**Comment by JiahuiYu** [comment]
Hi I think you can directly load jpeg images and perform our code for inpainting.

**Comment by ljjcoder** [comment]
Sorry to bother you again. when I train the model in imagenet, how many epoches is in your configuration? if I use the defaults batch size (16) and train the model for five days(about 130000 iters), which only experience 2 epoches, is  this  enough for imagenet?

**Comment by JiahuiYu** [comment]
@ljjcoder How is the performance and what's the GPU type? 2 epochs are usually not enough.

**Comment by ljjcoder** [comment]
here i
![1537148767 1](https://user-images.githubusercontent.com/40750189/45603462-cb948300-ba5e-11e8-9f91-dcf2f74a090b.png)
s my result
![1537148793 1](https://user-images.githubusercontent.com/40750189/45603465-d3542780-ba5e-11e8-8040-58dca64786c2.png)
![1537148828 1](https://user-images.githubusercontent.com/40750189/45603466-d5b68180-ba5e-11e8-9046-780335743f81.png)
and my GPU type is gtx1080,and I use only one GPU to train the model.

**Comment by ljjcoder** [comment]
@JiahuiYu Thanks for the reply. in issues#53，you said your speed is 0.3 ~ 0.4 batches/sec, that means one batch takes for 3 sec. Only 1200 iters are experienced in one hour , so five days(120 hours) will  experience 144000 iters. did you change something to make the speed more fast ?

**Comment by JiahuiYu** [comment]
You are correct. It should be around 150,000 iterations. The log I referenced was based on DeepFill v2 and Titan V gpu (0.6-0.8 batches/sec), which is not the case when we develop DeepFill v1.

For the performance, did you use the default setting? Maybe you can have a try again since I guess sometimes the performance of GAN is a little bit random.
