### ISSUE TITLE
About irrmask_flist.txt

### ISSUE THREAD

**Issue by JinMengKang** [JiahuiYu/generative_inpainting#132]
Thank you again for your excellent work！
In GatedConvolution:Free-Form inpainting 
Can you tell me in inpaint.yml the irrmask_flist.txt looks like？How should I generate it？

**Comment by JiahuiYu** [comment]
There is no irrmask_flist.txt for our second version. We random generate it on the fly. Please check our tech report.

**Comment by JinMengKang** [comment]
# parameters
DATASET: 'places2'  # 'tmnist', 'dtd', 'places2', 'celeba', 'imagenet', 'cityscapes'
MASKDATASET: 'irrmask'    <--Is this a necessary line? 
RANDOM_CROP: False
MASKFROMFILE: False
VAL: True
LOG_DIR: full_model_places2_256
MODEL_RESTORE: ''  # '20180115220926508503_jyugpu0_places2_NORMAL_wgan_gp_full_model'
...
DATA_FLIST:
  # https://github.com/JiahuiYu/progressive_growing_of_gans_tf
  celebahq: [
    'data/celeba_hq/train_shuffled.flist',
    'data/celeba_hq/validation_static_view.flist'
  ]
  irrmask: [   
    '../Data/MaskData/irrmask_flist.txt',
    '../Data/MaskData/irrmask_flist.txt'
  ]
