### ISSUE TITLE
Question: overfitting discussion - conditions to happen, ways to avoid

### ISSUE THREAD

**Issue by jayjtao** [JiahuiYu/generative_inpainting#134]
We did different levels of training, compared with testings on those trained models, and found that overfitting is quite easy to happen.  Since we did not find much overfitting discussion in either original paper or github repository, so we ask here: 
 - where can we find the overfitting discussion - conditions to happen, and the ways to avoid?
Thanks in advance! - Jay

**Comment by JiahuiYu** [comment]
Hi @jayjtao ,

For our experiments, we use the default training/validation data split from Places2, ImageNet and CelebA. For CelebA, training/validation have no identity overlap.

In my observations, I seldom find any overfitting as long as the dataset is pretty large (e.g., more than 30k images). For dataset of size less than 1k, overfitting probably happens. In this case, several solutions may help

1. increate dataset size,
2. more data augmentations like random flipping/rotation/adjusting colors. 

Please also take a reference at issue #75.
