### ISSUE TITLE
Saved model after finetuning

### ISSUE THREAD

**Issue by suzhenghang** [JiahuiYu/generative_inpainting#138]
Hi @JiahuiYu ,
         After finetuning,  I found the model saved (snap-10000.data-00000-of-00001) was 123M，but the imagenet pretrained model is 14M. I think extra params (like discriminator ) are including in it. How could I slimming the saved model?

**Comment by JiahuiYu** [comment]
@suzhenghang Hi, you can just load the model, and delete the tensors that are not used during inference. It should have many examples in TensorFlow communities.
