### ISSUE TITLE
question about allowed IMG_SHAPES

### ISSUE THREAD

**Issue by konstantg** [JiahuiYu/generative_inpainting#139]
Hi, Jiahui! Great results and thank you for sharing.

It seems that your implementation is for images of shape (?, ?, 3), is this true? If so, I wanted to ask if you have tried adapting this for grayscale images, i.e. of shape (?, ?, 1), before I start making my own adaptation.

**Comment by JiahuiYu** [comment]
@konstantg It should be easy to adapt on grayscale images by changing .yml configuration and data loader. I guess you may need to tune some hyper-parameters like GAN loss balance etc for grayscale images.

**Comment by LeonCurry** [comment]
Have you complete the modification of the code for single-channel grayscale inpainting?  Can you give me some guidance? @konstantg

**Comment by LeonCurry** [comment]
I am sorry to bother you again.   Can you give me some guidance about the modification of the code for single-channel grayscale inpainting?  @JiahuiYu

**Comment by JiahuiYu** [comment]
@LeonCurry You will need to change `.yml` configuration and data loader. We don't have a ready-to-use version for single-channel grayscale inpainting.

**Comment by LeonCurry** [comment]
Thanks! You are so kind and patient. I will try it~

**Comment by konstantg** [comment]
@LeonCurry you can also check the changes I made to the data loader in my forked project ([here](https://github.com/konstantg/dem-fill) and [here](https://github.com/konstantg/neuralgym)).

**Comment by LeonCurry** [comment]
I am so sorry to bother you again. Can this project inpaint the single-channel grayscale? If it can inpaint the grayscale, I will try my best to checke the changes between this project and deepfill, and then modify the code.

**Comment by LeonCurry** [comment]
I am so sorry to bother you again. Can this project inpaint the single-channel grayscale? If it can inpaint the grayscale, I will try my best to checke the changes between this project and deepfill, and then modify the code. @konstantg

**Comment by konstantg** [comment]
@LeonCurry Yes, it can. In our project we were working with digital elevation models, which are equivalent to single-channel images but with floats instead of ints.

**Comment by LeonCurry** [comment]
OK, Thanks for your quick reply! I will try my it! You are so kind! @konstantg

**Comment by LeonCurry** [comment]
@konstantg  I feel so sorry. I got this error.
Traceback (most recent call last):
  File "/home/lab/anaconda3/envs/newEnv/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/lab/anaconda3/envs/newEnv/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lab/anaconda3/envs/newEnv/lib/python3.5/site-packages/neuralgym/data/feeding_queue_runner.py", line 202, in _run
    sess.run(enqueue_op, feed_dict)
  File "/home/lab/anaconda3/envs/newEnv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/lab/anaconda3/envs/newEnv/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (32, 256, 256, 3) for Tensor 'Placeholder:0', which has shape '(?, 256, 256, 1)'

I have checked your feeding_queue_runner.py. But I don't know how to modify the code. Can you tell me what can I do?

**Comment by konstantg** [comment]
@LeonCurry Seems you are feeding 3-channel images to the data loader.

**Comment by LeonCurry** [comment]
@konstantg  I think I must modify the neuralgym file. I don’t have any idea how to modify the python files. Do you have any idea?
