### ISSUE TITLE
celebA-HQ data

### ISSUE THREAD

**Issue by ljjcoder** [JiahuiYu/generative_inpainting#140]

**Comment by ljjcoder** [comment]
Hi, Jiahui! I find the celebA-HQ data have two folders. Can you tell me what is the difference between the celeba_hq_images and download_7z? which is used for trainning the model? thanks.
![1537516626 1](https://user-images.githubusercontent.com/40750189/45868607-ce71d980-bdb8-11e8-9e3b-16a1d2e7ca42.png)

**Comment by JiahuiYu** [comment]
@ljjcoder  You can either use the download_7z or celebs_hq_images. The former is 7z files while the later are raw images.
