### ISSUE TITLE
Transparent Image

### ISSUE THREAD

**Issue by KangSH9776** [JiahuiYu/generative_inpainting#141]
I want to use an image with transparent values as the training data.

How do I read the image values for transparent images?

**Comment by JiahuiYu** [comment]
@KangSH9776 I think you can simply load the data with your own [data reader](https://github.com/JiahuiYu/neuralgym/blob/28c7622b5e17aeb5f0293746cd63124d432189a4/neuralgym/data/data_from_fnames.py#L150-L158). Do not forget to correct the shape of images. It should be 4 channels with transparent images.
