### ISSUE TITLE
about result

### ISSUE THREAD

**Issue by an1018** [JiahuiYu/generative_inpainting#145]
@JiahuiYu The picture on the top is the result of my training（ iteration = 25000，other parameters remain unchanged）.The picture on the bottom is the result of your model.
     And I have been training for three days(0.11batches/sec),do you think continuing training will make the result better?Look forward to your! #75 
![sunset_25000](https://user-images.githubusercontent.com/19808900/46199410-9aab2c80-c341-11e8-88ff-fbe1b406f709.png)
![sunsetresult](https://user-images.githubusercontent.com/19808900/46199481-c0383600-c341-11e8-8f94-8aab77f96976.png)

**Comment by JiahuiYu** [comment]
Yes. You do need much more training. Please take a reference at related issues about training iterations.

**Comment by an1018** [comment]
@JiahuiYu Thank you very much.After training for a few days, I will show you the result again.

**Comment by JiahuiYu** [comment]
@an1018 By the way, a good indication of training convergence is the curves of GAN loss in TensorBoard.

**Comment by an1018** [comment]
@JiahuiYu g_loss looks like this,still increasing.So I need to train more epochs,right?

**Comment by an1018** [comment]
@JiahuiYu I have continued to train the network model for 8 days，only iter 11000(0.11batches/sec,one GPU), do you think it's too slow?Result(On the left is the result graph with 27000 iterations，On the right is the result graph with 38000 iterations):
![_20181008095111](https://user-images.githubusercontent.com/19808900/46590267-81924080-cae4-11e8-90a5-5f2506a9c15c.png)
