### ISSUE TITLE
metrics used in the paper

### ISSUE THREAD

**Issue by 1900zyh** [JiahuiYu/generative_inpainting#146]
Hi @JiahuiYu 

I saw the numeric results report in your paper includes mean L1 loss, mean L2 loss and mean TV loss.
I wonder why they all have percentage ?
for example, I used to know L1_loss=abs(real-fake),
does the percentage comes from dividing 255 like L1_loss=abs(real-fake)/255?

**Comment by JiahuiYu** [comment]
For errors we used relative L1 error and squared relative L2 error as this:
![pastedimage](https://user-images.githubusercontent.com/22609465/46231832-f6ba8480-c332-11e8-9e85-382ea1f67342.png)

If you just want to compare your results with ours, I suggest you to use our model and compute with your own formulations. As I mentioned in paper, these numbers are just reported as a reference. Since for inpainting, perceptual results are much more important.

**Comment by an1018** [comment]
@JiahuiYu Is it right？
![image](https://user-images.githubusercontent.com/19808900/50396486-619a2100-07a5-11e9-8090-5c67b5f41cb3.png)

**Comment by an1018** [comment]
mean l1 loss in your article, l1 norm in your formula,,and  Could you see which one is right?
![image](https://user-images.githubusercontent.com/19808900/50409399-4bd03e80-082d-11e9-9477-fcc555f9f559.png)
OR
![image](https://user-images.githubusercontent.com/19808900/50409404-55f23d00-082d-11e9-84bf-52db9a30e7e0.png)

**Comment by JiahuiYu** [comment]
@an1018 The bottom one is correct. I just checked my previous code, my code is:

`np.sum(np.abs(x/256-y/256))/mask_height/mask_width/3.`

It makes slight difference compared with yours. Your code averages over entire image while mine averages over masked region.

Again, if you just want to compare your results with ours in your paper, I suggest you to use our model and compute with your own formulations/implementation.

**Comment by an1018** [comment]
Sorry, I use deepfillv2, I don't think free-form masks have mask_height and mask_width

**Comment by JiahuiYu** [comment]
@an1018 Ok, do whatever you like then, as long as they are fair comparison. :)

**Comment by awsssix** [comment]
@JiahuiYu 
/mask_height/mask_width : eliminate the area factor
/3 : represent channels
Do I understand that right

**Comment by awsssix** [comment]
@JiahuiYu 
![image](https://user-images.githubusercontent.com/46213799/50885753-8ccd7300-1429-11e9-8fe9-c14b6fb0df09.png)
Q1:  3 represent channel?
Q2:   x/y represent only inpainting part like below pic  or hole image 
![image](https://user-images.githubusercontent.com/46213799/50885802-b4bcd680-1429-11e9-9a20-50dcc9b9c9d8.png)

**Comment by JiahuiYu** [comment]
@awsssix 
1: yes.
2: x is image after inpainting, y is ground truth.
3: Normalize over masked region.
4: Different than ours. We use

 `-10.0 * math.log10(np.sum(np.square(x-y))/mask_height/mask_width/3.)`

**Comment by awsssix** [comment]
@JiahuiYu Thanks for your kindness.
But I still have a question,as you said yours is averages over masked region, so x/y is hole image or only the extracted mask part,like below:
![image](https://user-images.githubusercontent.com/46213799/50941208-e59b1b00-14be-11e9-9fc5-60937a264aa8.png)
![image](https://user-images.githubusercontent.com/46213799/50941217-ea5fcf00-14be-11e9-82f3-bf48173e5c91.png)

**Comment by JiahuiYu** [comment]
@awsssix The pixels in x and y are different only in the masked region. In fact I cannot understand your question after reading more than 10 times... Can you make it more clear what is your question?

**Comment by awsssix** [comment]
I have understood.Thanks!
Why divide the number of channels ?

**Comment by wangping1408** [comment]
hi, @JiahuiYu 
![screenshot from 2019-01-12 15-09-52](https://user-images.githubusercontent.com/43232577/51070454-779c5280-167c-11e9-8fd8-99504b29efc6.png)
I want to know what the batch_data here is.Whether it refers to the complete picture in the original data set？and Why is this calculated?batch_pos=batch_data/127.5-1   I hope you can answer my doubts.

**Comment by Yukariin** [comment]
@wangping1408 that's data normalization, from [0, 255] to [-1, 1].

**Comment by JiahuiYu** [comment]
@Yukariin Thanks.

**Comment by neouyghur** [comment]
@JiahuiYu 
I can't find the code for TV loss evaluation. Could you help with this? Thanks.

**Comment by JiahuiYu** [comment]
@neouyghur The code should be right - except we normalize image to 0-1 before computing tv loss.

**Comment by neouyghur** [comment]
Thanks for your quick reply. The input is normalized before calculating.
