### ISSUE TITLE
GPU error

### ISSUE THREAD

**Issue by ChristophWu** [JiahuiYu/generative_inpainting#147]
Hi, I encounter a problem about gpu. There is already a GTX 960 in my computer and I can use gpu to run other code. But I can not run this code. Looking forward to your reply and thanks.

File "/home/jason/anaconda3/lib/python3.6/site-packages/neuralgym/utils/gpus.py", line 70, in get_gpus
    ' [(gpu id: num of processes)]: {}'.format(sorted_gpus))
SystemError: No enough gpus for dedicated usage. [(gpu id: num of processes)]: [(0, 3)]

**Comment by JiahuiYu** [comment]
There are related issues by search with keyword GPU. Please have a reference.

**Comment by herleeyandi** [comment]
@JiahuiYu Hi I have the same problem in here, could you give a more detail explanation?, I have set the .yaml with NUM_GPUS: 1 GPU_ID: 0 , but its still produces same error.
