### ISSUE TITLE
some questions about places2

### ISSUE THREAD

**Issue by ljjcoder** [JiahuiYu/generative_inpainting#148]
hi JiahuiYu，when I train your model followiing your default setting ，the large mask does not work well as your result。I notice that the parameter HEIGHT：128 and WIDTH：128，means the maximum size of the mask is 128*128,but in your examples in places2 the hole of grass_mask.png is larger than 128*128. do you make larger  HEIGHT and WIDTH setting to train this model on places2?
![places365_val_00000047](https://user-images.githubusercontent.com/40750189/46275998-5dd57480-c591-11e8-9487-06c2369e4dfc.png)

![places365_val_00000047](https://user-images.githubusercontent.com/40750189/46275974-4d24fe80-c591-11e8-92dd-fb92c15fab01.png)
![places365_val_00000047](https://user-images.githubusercontent.com/40750189/46275986-5615d000-c591-11e8-9b13-cf1418abbc69.png)
![places365_val_00000025](https://user-images.githubusercontent.com/40750189/46276097-a3923d00-c591-11e8-89d5-db0db0766178.png)
![places365_val_00000025](https://user-images.githubusercontent.com/40750189/46276104-a7be5a80-c591-11e8-8bf5-2ca8a5a0288c.png)
![places365_val_00000025](https://user-images.githubusercontent.com/40750189/46276113-aa20b480-c591-11e8-9764-2905e651b27d.png)

**Comment by JiahuiYu** [comment]
@ljjcoder All models are trained with images of resolution 256x256 and largest hole size 128x128, above which the results may be deteriorated. The hole of size 256x256 for glass is to show the potential functionality of our proposed contextual attention.

Also for irregular masks, please checkout DeepFill v2.

**Comment by ljjcoder** [comment]
@JiahuiYu sorry to bother you again. when I tested the psnr on places2 validation dataset(36500,ramdom crop 256x256,and center masked 128x128 region)，using your pretrain model ,the psnr is 18.0949,but when i use the pretrain model of _Globally and locally consistent image completion_(siggragh2017) the psnr is 18.7969. The result is different from your paper. I guess the test images may be not correct,could you provide your test images of places2?

**Comment by JiahuiYu** [comment]
@ljjcoder Hi, please take a reference of issue #146.

**Comment by ljjcoder** [comment]
@JiahuiYu sorry! the two results of the first example are same and they are produced by siggragh2017. Here is the your pretrain model's result.



![places365_val_00000002](https://user-images.githubusercontent.com/40750189/46621047-fef79880-cb58-11e8-90a3-0cbf0cf4bce6.png)

**Comment by JiahuiYu** [comment]
@ljjcoder Do you use image blending option for paper of siggraph 2017? The image blending is a blending of deep learning result and result of conventional approach (like PatchMatch), which helps to improve PSNR.

When we submit CVPR, the code of siggraph paper is not available. And we reproduce that paper without using image blending to ensure fairness. Hope now it will be clear to you about the result of PSNR.

Feel free to leave any further question if you still have one.

**Comment by ljjcoder** [comment]
@JiahuiYu i did not use the blending process.  In siggragh 2017,the author said they train the model for two month on places2. Can i ask how long do you train the model to reproduce siggragh2017's result?

**Comment by JiahuiYu** [comment]
@ljjcoder We modify the generative network of siggraph 2017 and train for 5 days as mentioned in our paper.

**Comment by ljjcoder** [comment]
@JiahuiYu thanks for your reply
