### ISSUE TITLE
Question: can Imagenet weight be directly used, and how?

### ISSUE THREAD

**Issue by jayjtao** [JiahuiYu/generative_inpainting#149]
Understand that this uses your own implementation to train; my questions are -
1. Can Imagenet weight (training result) be directly used (replaced with one of the Imagenet weights, such as VGG16)?
2. If yes, how?
Thanks in advance.
Jay

**Comment by JiahuiYu** [comment]
@jayjtao I cannot understand what you mean by "directly used", used for what? I do understand VGG16 was originally for image classification, and recently many style transfer researches are also using it.

**Comment by jayjtao** [comment]
For example, "vgg16_weight.h5" used in:
"Building powerful image classification models using very little data"
https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html
has different data format from 
the imagenet256 weight data format in your imagenet test cases,
as they were resulted from different training implementation?

**Comment by jayjtao** [comment]
Hi, JiaHui,

Thanks for responding. What I meant is as the following -

For example, "vgg16_weight.h5" used in:
"Building powerful image classification models using very little data"
https://blog.keras.io/building-powerful-image-classification-models-using-very-little-data.html
has different data format from
the imagenet256 weight data format in your imagenet test cases,
as they were resulted from different training implementation?

As you experienced more and deeper during your design and implementation, can you share some lights on this topic?

Thanks in advance.
Jay
________________________________
寄件者: JiahuiYu <notifications@github.com>
寄件日期: 2018年10月4日 下午 12:58
收件者: JiahuiYu/generative_inpainting
副本: jayjtao; Mention
主旨: Re: [JiahuiYu/generative_inpainting] Question: can Imagenet weight be directly used, and how? (#149)


@jayjtao<https://github.com/jayjtao> I cannot understand what you mean by "directly used", used for what? I do understand VGG16 was originally for image classification, and recently many style transfer researches are also using it.
