### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by hua-wu-que** [JiahuiYu/generative_inpainting#150]
I encountered this error when doing python train.py
I followed the instruction to setup a proper flist, but the error stills
File "/home/wxh/anaconda3/envs/tf/lib/python3.6/site-packages/neuralgym/ops/image_ops.py", line 23, in np_scale_to_shape
imgh, imgw = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by JiahuiYu** [comment]
@hua-wu-que Please take a look at issue #9.
