### ISSUE TITLE
The model about context-aware-fill

### ISSUE THREAD

**Issue by 1900zyh** [JiahuiYu/generative_inpainting#151]
Hi Jiahui,

You mentioned context-aware-fill method in your paper for comparison. 
To my best known is that context-aware-fill is a tool in Photoshop.
I wonder how did you get/use the model of context-aware-fill ?
(Because I didn't find out the source code for context-aware-fill)

Thank you for your kindly help!

**Comment by JiahuiYu** [comment]
@1900zyh Hi I think for those who do not have access to PhotoShop, the only solution is to purchase it. It is not possible to obtain source code of Adobe content aware fill.
