### ISSUE TITLE
about resume

### ISSUE THREAD

**Issue by an1018** [JiahuiYu/generative_inpainting#152]
@JiahuiYu 
Interrupted during training, continue training on the same flist, and it will start on the first line of the flist or the line that is interrupted？
Looking forward to your reply.

**Comment by JiahuiYu** [comment]
@an1018 First line. You can do shuffling each time before training so that randomness can be achieved, by adding line of shuffling after this line:
https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/train.py#L40

**Comment by an1018** [comment]
@JiahuiYu I think before this line,is it right?
with open(config.DATA_FLIST[config.DATASET][0]) as f:
      shuffle(f)
      fnames = f.read().splitlines()

**Comment by an1018** [comment]
@JiahuiYu I think before this line,is it right?
`with open(config.DATA_FLIST[config.DATASET][0]) as f:
       shuffle(f)
       fnames = f.read().splitlines()`
