### ISSUE TITLE
test images with different sizes

### ISSUE THREAD

**Issue by 123liluky** [JiahuiYu/generative_inpainting#154]
I am wondering why the network accepts different input sizes. Within my knowledge, test input sizes must equal to train input size.

**Comment by JiahuiYu** [comment]
Because convolutions are local operators. It is similar to object detection and semantic segmentation. Please take a reference of this [paper](https://people.eecs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf)

**Comment by JiahuiYu** [comment]
@123liluky All models are trained with images of resolution 256x256 and largest hole size 128x128, above which the results may be deteriorated.
