### ISSUE TITLE
Operation process

### ISSUE THREAD

**Issue by an1018** [JiahuiYu/generative_inpainting#155]
The program has not run for 4 hours.What do you think is wrong?
![image](https://user-images.githubusercontent.com/19808900/46801115-50d43480-cd8c-11e8-999e-27ef826dcaff.png)

**Comment by JiahuiYu** [comment]
@an1018 Please check your images do exists as listed in your file list. Normally this is because the images can not be found.

**Comment by an1018** [comment]
If the picture does not exist, it will be sleep 0.1s, but the program has not been running from yesterday to today,the state is always as shown in the above picture
