### ISSUE TITLE
How to install pip install git+https://github.com/JiahuiYu/neuralgym

### ISSUE THREAD

**Issue by xiayq1** [JiahuiYu/generative_inpainting#156]
Can u tell me how to install pip install git+https://github.com/JiahuiYu/neuralgym. I try to install it on Anaconda prompt. But it will send me the msg "cannot find command 'git'". I try to use conda install git+https://github.com/JiahuiYu/neuralgym. It will send me the msg PackagesNotFoundError.

**Comment by JiahuiYu** [comment]
You will need to have pip first. Then install via pip install command. It is not related to conda.
