### ISSUE TITLE
loss does not converge

### ISSUE THREAD

**Issue by AterLuna** [JiahuiYu/generative_inpainting#16]
I'm training network with Stanford Cars dataset, and now it's on 10th epoch.
But the loss showed in terminal does not change from 0.14xx to 0.19xx.
Also, in TensorBoard, there are many losses but all of them are just oscillating and not converging.
Should I modify some of parameters in inpaint.xml to solve this problem?

**Comment by JiahuiYu** [comment]
The loss is a summation of generative model and discriminative model. Thus if you see loss change from 0.14 to 0.19, it is totally fine. In tensorboard, you should see the curve of discriminator converges. You should also see the images it generates in tensorboard/images tag.

You are highly recommended to read papers of GANs and training GANs to see its behavior. The references are in our paper.
