### ISSUE TITLE
release_dtd_model

### ISSUE THREAD

**Issue by 1900zyh** [JiahuiYu/generative_inpainting#160]
Hi Jiahui,

experiment on DTD was mentioned in your paper (CVPR2018)
But I didn' find the release model for DTD?

Will you release the model of DTD as well as flist file?

**Comment by JiahuiYu** [comment]
Hi @1900zyh , I try to find the trained DTD model but unfortunately I cannot find it. Compared with other released models, DTD dataset is a toy. But if you want to compare our models with yours in paper specifically on the dataset of DTD, you probably can train your own with your own flist.
