### ISSUE TITLE
imagenet: [ your_file.flist, ]  What means "your_file.flist"? How can I create a file.flist? How can I add 'data\imagenet\buffer010.png' to a file? Can u show me? Thx a lot.

### ISSUE THREAD

**Issue by xiayq1** [JiahuiYu/generative_inpainting#161]
imagenet: [
your_file.flist,
]

What means "your_file.flist"? How can I create a file.flist? How can I add 'data\imagenet\buffer010.png' to a file? Can u show me? Thx a lot.

**Comment by JiahuiYu** [comment]
@#159 Redundant issue.
