### ISSUE TITLE
strange output with pretrained model

### ISSUE THREAD

**Issue by dayeguilaiye** [JiahuiYu/generative_inpainting#163]
my test code:
`python3 test.py --image examples/celeba/celebahr_patches_163050_input.png --mask examples/center_mask_256.png --output out3.png --checkpoint_dir model_logs/release_celeba_hq_256/`
and
`python3 test.py --image examples/celeba/celebahr_patches_165230_input.png --mask examples/center_mask_256.png --output out1.png --checkpoint_dir model_logs/release_celeba_hq_256/`

I only changed line23 in test.py from "ng.get_gpus(1)" to "ng.get_gpus(0)"

those are input, mask, output:
![celebahr_patches_165230_input](https://user-images.githubusercontent.com/9746948/47344239-9244d800-d6da-11e8-8268-1067892ed1f6.png)

![center_mask_256](https://user-images.githubusercontent.com/9746948/47344257-9d980380-d6da-11e8-974e-e4df1b3d5908.png)

![out](https://user-images.githubusercontent.com/9746948/47344269-a557a800-d6da-11e8-8bbf-a12b2541470c.png)

![celebahr_patches_163050_input](https://user-images.githubusercontent.com/9746948/47344516-4181af00-d6db-11e8-8a19-c9be5368714f.png)
![out3](https://user-images.githubusercontent.com/9746948/47344526-48102680-d6db-11e8-9a6a-d12e84a60807.png)

It's really similar to #111 , so I changed tf1.10 to 1.7, but nothing happened.

ps: the performance of places2 seems better:
![building_input](https://user-images.githubusercontent.com/9746948/47344734-b7861600-d6db-11e8-9f97-4621e3eb1238.png)
![out2](https://user-images.githubusercontent.com/9746948/47344758-c2d94180-d6db-11e8-8b53-f785e0ab262f.png)

Do yo know why this happened, please!

**Comment by JiahuiYu** [comment]
Hi, you should use celeba pretrained model for celeba testing images, instead of celeba hq model. The two datasets have different image distributions. For example, the celeba model we trained could handle slight face unalignment (by random shifting and cropping faces during training), but the celebahq model we trained is strictly on aligned faces during training. If you test unaligned face with celebahq model, this results can happpen.

**Comment by dayeguilaiye** [comment]
Thanks a lot!

**Comment by JiahuiYu** [comment]
@dayeguilaiye No problem. Let me know if you have further question.
