### ISSUE TITLE
If i want to train my own dataset, what are the requirements for pictures?

### ISSUE THREAD

**Issue by dayeguilaiye** [JiahuiYu/generative_inpainting#166]
Do they have to be the same size?
Do I have to do some initialization before training?
if I want to inpaint landscape painting， Is transfer learning based on your pre-trained model of places2 possible effect?

And sorry for disturbing you with these  simple question, I'm really new to DL especially GANs.

**Comment by JiahuiYu** [comment]
@dayeguilaiye 
During training, it is usually better to crop images to have same size for batch-based training. During testing, you can test for any input resolution, as mentioned in our paper.

Initialization is not necessary, as long as your own dataset is large.

Transfer learning may help. I have not investigated transfer learning in image inpainting yet.

Also, please have a reference at issue #75, some Q&A in that issue may help.
