### ISSUE TITLE
questions about score fusion

### ISSUE THREAD

**Issue by cmyyy** [JiahuiYu/generative_inpainting#167]
Hi~
My questions comes from here.https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/inpaint_ops.py#L285
Q1:What's the definition of score fusion?
Q2:How can it encourage larger patches?
Thx!

**Comment by JiahuiYu** [comment]
@cmyyy 

Q1:
Score is the matching score, which is computed by the convolution of foreground and background.

Q2:
Score fusion can be viewed as score propagation. Assume location (i,j) has a very high score for background patch location (ii,jj); and (i+1,j) has similar scores for all background patches. Then if you fuse the score, location (i+1,j) will also have higher score for patch (ii+1,jj). This results in large coherent patch matching.

Probably drawing an example by hand can help you to understand.
