### ISSUE TITLE
Using the network for feature extraction

### ISSUE THREAD

**Issue by nargeshn** [JiahuiYu/generative_inpainting#168]
Hello Jiahui,

Thanks for very well written code and great description! 
I have a dataset with around 60000 images and I would like to use genarative_inpainting as a feature extractor. I am planning to use the output of encoder for the task of image classification and I would be grateful if you could tell me which layer should I use?

**Comment by JiahuiYu** [comment]
@nargeshn The best way is to have a try to verify the performance. I guess you can either use the first encoder in [line](https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/inpaint_model.py#L62) or the second encoder in [line](https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/inpaint_model.py#L104).
