### ISSUE TITLE
about result，expect your answer

### ISSUE THREAD

**Issue by an1018** [JiahuiYu/generative_inpainting#170]
@JiahuiYu There are more iterations. Why does it look worse?（places2 dataset，still not one epoch）
Separate iteration278000 and 483000
![image](https://user-images.githubusercontent.com/19808900/47781051-bbe3ac00-dd37-11e8-802c-be5c79add428.png)
![image](https://user-images.githubusercontent.com/19808900/47781057-c140f680-dd37-11e8-9b4a-0490b0ec2752.png)

**Comment by JiahuiYu** [comment]
It seems the model is not fully converged. It is possible that the results are not consistently being better visually. A suggestion is to use larger batch size and longer training epochs. Also the convergence curve in tensorboard reflects the training progress.

**Comment by an1018** [comment]
@JiahuiYu the loss is shown as below
![image](https://user-images.githubusercontent.com/19808900/47827903-59cc8a80-ddbb-11e8-86e4-8e0d84689249.png)

**Comment by JiahuiYu** [comment]
It is converging (see discriminator loss).
