### ISSUE TITLE
Resume training based on pre-trained imagenet model

### ISSUE THREAD

**Issue by ChristophWu** [JiahuiYu/generative_inpainting#174]
Hello,

You did a really interesting work. I have a question that how can I resume training based on the pre-trained ImageNet model. I mean where can I find the restored model and what should I modify of MODEL_RESTORE flag in inpaint.yml.

Thanks for your time.

**Comment by JiahuiYu** [comment]
@ChristophWu 

Hi,

Thanks for your interest. You can actually resume training, by setting MODEL_RESTORE as put our imagenet model under model_logs:

https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/train.py#L107

Basically it loads the model and resume training, either with imagenet dataset or your own dataset.
