### ISSUE TITLE
DeepFillv2 questions

### ISSUE THREAD

**Issue by Yukariin** [JiahuiYu/generative_inpainting#182]
Q1: According to the paper discriminator's input is image, mask and optional user input. Just like for generator net.
And according to this comment https://github.com/JiahuiYu/generative_inpainting/issues/158#issuecomment-433722306 you do NOT use ones in discriminator's input. So it's looks like that?
```
ones_x = tf.ones_like(x)[:, :, :, 0:1]
x = tf.concat([x, ones_x*mask], axis=3)
```

Q2: Do you use gated convolution for ALL layers? Even for last one of coarse and refine nets?

**Comment by JiahuiYu** [comment]
Hi, for first question, the code is correct if you do not have guided input. For the second question, both output layer is normal layer, instead of gated convolution.

**Comment by Yukariin** [comment]
Thanks!

Q3: For v2 you use same settings for new discriminator? Like single one ADAM optimizer with =1e-4, beta1=0.5 and beta2=0.9.

**Comment by JiahuiYu** [comment]
@Yukariin Yes, optimizer is the same.

**Comment by Yukariin** [comment]
Q4: Just trying to train my implementation of v2 and loss curves looks strange. As for 20th epoch it's -0.305907 and rounds around from -0.26 to -0.30. Is that okay? What v2 loss curves should looks like?

**Comment by JiahuiYu** [comment]
It shoud be fine. Just train more iterations and see how the performance of Inpainting examples.

**Comment by Yukariin** [comment]
Q5: I'm still confused about final generator loss... Is it just l1_loss+g_loss or l1_loss+ae_loss+g_loss?

**Comment by JiahuiYu** [comment]
Hi l1_loss+ae_loss can actually be combined. In current code, l1 loss is computed inside holes, ae loss is computed outside holes. In DeepFill v2, we compute l1 loss of entire image. Thus it is just simply a l1 loss.

**Comment by Yukariin** [comment]
Yeah, just figured it out too. Thanks anyway.

**Comment by JiahuiYu** [comment]
Yes. Confirm. In v2 I use tanh

**Comment by Yukariin** [comment]
Thanks!

**Comment by Yukariin** [comment]
Hmm, and you still use `tf.clip_by_value(x, -1., 1.)`?
