### ISSUE TITLE
Warning: unknown JFIF revision number 0.02

### ISSUE THREAD

**Issue by KKKlose** [JiahuiYu/generative_inpainting#188]
When I run train.py with my own dataset, it‘s warning: unknown JFIF revision number 0.02
what's the problem?

![1543473535 1](https://user-images.githubusercontent.com/41884199/49203873-cd76ad00-f3e4-11e8-8537-c937ecb16d69.jpg)

**Comment by JiahuiYu** [comment]
It is probably a problem of openCV. Please try to search answers in openCV community. Currently I have no idea how to fix it.
