### ISSUE TITLE
Question about indexes such as ssim、psnr

### ISSUE THREAD

**Issue by laolongboy** [JiahuiYu/generative_inpainting#189]
I generated a mask database and use CelebA-HQ to test some indexes.
But the result is not good.I dont know why.
I found you generated one mask for every image of the same batch, did it matter？
![image](https://user-images.githubusercontent.com/25175047/49221536-607b0b80-f414-11e8-937c-b8f0e924efc0.png)
![image](https://user-images.githubusercontent.com/25175047/49221420-0a0dcd00-f414-11e8-8b8f-283c99c37ce1.png)

**Comment by JiahuiYu** [comment]
PSNR is not an important index for inpainting. What you are expecting for PSNR or SSIM? Higher than 25 PSNR?

One mask for a batch during training is fine.
