### ISSUE TITLE
Can I send you some examples and you run your DeepFillv2 models to test, and send back results to me?

### ISSUE THREAD

**Issue by dengyueyun666** [JiahuiYu/generative_inpainting#190]
If it is okay, please leave your e-mail and I send you some examples.
Thanks!

**Comment by JiahuiYu** [comment]
How many examples do you have? If it is large, you can probably share a link with google drive, Dropbox, etc.

**Comment by dengyueyun666** [comment]
Just about 10 examples. I think e-mail is enough. Can you leave an e-mail?

**Comment by JiahuiYu** [comment]
Send to hi@jhyu.me then.

**Comment by dengyueyun666** [comment]
Are you sure the e-mail is correct? I can't send to it...
