### ISSUE TITLE
deepfillv2

### ISSUE THREAD

**Issue by an1018** [JiahuiYu/generative_inpainting#191]
When I used deepfillv2 code to fix irregular occlusion, the results are  as follows. What do you think caused this phenomenon?Looking forwarding your replay!
![image](https://user-images.githubusercontent.com/19808900/49281836-8f52b980-f4c8-11e8-8c15-b777ce91bcfa.png)
![image](https://user-images.githubusercontent.com/19808900/49281877-ab565b00-f4c8-11e8-8da8-302fb2da693f.png)

**Comment by JiahuiYu** [comment]
Your model is not well-trained.

In fact, your examples are very easy cases.

**Comment by an1018** [comment]
@JiahuiYu What you mean is that I need to modify the hyperparameters，and retarin the model?Could you give me more detailed advice, please?Thanks you very much!
![image](https://user-images.githubusercontent.com/19808900/49368317-506f6e80-f729-11e8-903f-769e8d9bfa9c.png)
![67hruniq5 3yf odysn2t](https://user-images.githubusercontent.com/19808900/49368616-181c6000-f72a-11e8-89ed-a2858ad205fa.png)
![image](https://user-images.githubusercontent.com/19808900/49368650-31bda780-f72a-11e8-8572-1611b62ddebb.png)

**Comment by an1018** [comment]
![image](https://user-images.githubusercontent.com/19808900/49369208-ddb3c280-f72b-11e8-8d9f-e246daad1e0a.png)

**Comment by JiahuiYu** [comment]
It is obvious from the curves that your model is not converged, for both AE loss and L1 loss. Do not change hyper parameters in such case, I would suggest to train more iterations.
