### ISSUE TITLE
result 

### ISSUE THREAD

**Issue by an1018** [JiahuiYu/generative_inpainting#192]
@JiahuiYu Why use batch_complete(left) as the final result， instead of batch_predict(right)？I think the picture on the right is better.
![image](https://user-images.githubusercontent.com/19808900/49505148-1bdced80-f8b6-11e8-8c13-7edecd2c4f74.png)
![image](https://user-images.githubusercontent.com/19808900/49504983-bdb00a80-f8b5-11e8-9654-1ee018bbb1a2.png)
![image](https://user-images.githubusercontent.com/19808900/49505341-84c46580-f8b6-11e8-9d89-1b01083e976c.png)

**Comment by an1018** [comment]
And why loss has converged, but the repair effect is not good?

**Comment by JiahuiYu** [comment]
Since your questions have been repeating, can you ask under same issue so that others can have clear view?

If possible, please upload your input and mask. I will give you my results.

**Comment by JiahuiYu** [comment]
For your question, I have also answered in related issue. Please have a search with these keywords.

**Comment by an1018** [comment]
Last time you said that because of the network confiscation convergence, but now convergence, the result is still the same.So I open a new issue,next time I'll ask a question in an issue!
![image](https://user-images.githubusercontent.com/19808900/49562678-8a25bc80-f957-11e8-96a1-d10d3220368b.png)
I use places2-Standard datasets(Small images 256*256).
http://places2.csail.mit.edu/download.html
Mask(Baidu SkyDrive) :https://pan.baidu.com/s/1AWAE0LuDxYRVylEc0-Rowg(Extraction code:w58i)

**Comment by JiahuiYu** [comment]
I will test them once have time.

**Comment by an1018** [comment]
@JiahuiYu I'm sorry to reply to you now.Thanks you very much .And I still have two question:
 1. Your mask is RGB or gray mode?（I use gray mask，150 pictures）
 2. I use places2-places2-Standard datasets(Small images 256*256)，not High-resolution images，does this make any difference?
And later I will send my project，and masks to your email, hi@jhyu.me or  jyu79@illinois.edu.Could  you give me your result and suggestions?

**Comment by JiahuiYu** [comment]
Received. I will test in a few days.

**Comment by an1018** [comment]
@JiahuiYu I am particularly grateful to you for your timely help.

**Comment by JiahuiYu** [comment]
@an1018 
1. RGB or gray makes no difference.
2. Please use high-res images which is important as I already said in issue #89. I already said it is important so please do not repeat questions.
3. You just send me your entire code, but **the only thing I can do is to test your images and masks**.
4. **You did not send me your images**. I did receive your masks - the masks look fine.
