### ISSUE TITLE
metaclass=LoaderMeta invalid syntax?

### ISSUE THREAD

**Issue by paulfryer** [JiahuiYu/generative_inpainting#193]
Hi @JiahuiYu I'm getting the following error when trying to run the Train.py code. I have previously installe d the **neuralgym** pip module via your git repo.

![12-9-2018 06-38-58](https://user-images.githubusercontent.com/472725/49698766-2f6daa00-fb7d-11e8-9d2f-7a86ce2bf8cb.png)

Any ideas what's going on here?

Also, when can we get access to V2? I'd prefer to use polygon based inpainting instead o just rectangles. Thanks!

**Comment by JiahuiYu** [comment]
@paulfryer Hi, it seems you are using python 2.7. As I mentioned in [README](https://github.com/JiahuiYu/generative_inpainting#run), please use python 3.

For v2, our answers are still the same as in issue #62. Thanks for your interest.
