### ISSUE TITLE
how to transfer pre-trained model to pb file?

### ISSUE THREAD

**Issue by muyue1238** [JiahuiYu/generative_inpainting#198]
Hi there, I was trying to transfer the author's pre-trained checkpoint to pb file and ran into weird error. I used the following code to do it, yet I failed to load the transferred pb file:

`constat_graph = graph_util.convert_variables_to_constants(sess, sess.graph_def, ['save/restore_all'])
with tf.gfile.FastGFile(self._dump_prefix, mode='wb'):
    f.write(constant_graph.SerializeToString())`

I'm a little confused by the neuralgym and wondering if you could tell me how to transfer checkpoint to pb file, or how to save pb file during training process(tried, failed to load it). Thanks very much.

**Comment by JiahuiYu** [comment]
@muyue1238 Hi, `neuralgym` is just a wrapper. The saved model is exactly the same as saved with tensorflow API. If you encounter error, maybe you can ask on tensorflow community. Personally I have not tried to transfer checkpoint to pb file with tensorflow API.

Btw, do check if the version of your tensorflow matches our version mentioned in README.

**Comment by muyue1238** [comment]
never mind, kinda did it. those who has similar interest could ask here.

**Comment by jhyume** [comment]
@muyue1238 Great. Thanks!

**Comment by JiahuiYu** [comment]
@muyue1238 Great. Thanks!

**Comment by zhouhuan2005** [comment]
@muyue1238 I met the similar issue, could you tell us how to workaroud it? or give me a URL where I could find the solution. Thx.

**Comment by muyue1238** [comment]
@zhouhuan2005 Hi there. Instead of transferring checkpoint to pb, which might result in various errors, I chose to save pb while training. To do that, you should change the corresponding code in neuralgym/callbacks/model_saver.py./run
from
` self._saver.save(sess, self._dump_prefix, global_step=step)` 
to
````
            graph_def = tf.get_default_graph().as_graph_def()
            output_node_name = 'inpaint_net/output'
            constant_graph = graph_util.convert_variables_to_constants(sess, graph_def, output_node_name.split(","))
            with tf.gfile.FastGFile(self._dump_prefix + 'model-' + str(step) + '.pb', mode='wb') as f:
                f.write(constant_graph.SerializeToString())

```
or just add above code there if you want to save both checkpoint and pb.

**Comment by JiahuiYu** [comment]
@muyue1238 Thanks for your help!

**Comment by zhouhuan2005** [comment]
> @zhouhuan2005 Hi there. Instead of transferring checkpoint to pb, which might result in various errors, I chose to save pb while training. To do that, you should change the corresponding code in neuralgym/callbacks/model_saver.py./run
> from
> ` self._saver.save(sess, self._dump_prefix, global_step=step)`
> to
> 
> ```
> graph_def = tf.get_default_graph().as_graph_def()
> output_node_name = 'inpaint_net/output'
>  constant_graph = graph_util.convert_variables_to_constants(sess, graph_def, utput_node_name.split(","))
> with tf.gfile.FastGFile(self._dump_prefix + 'model-' + str(step) + '.pb', mode='wb') as f:
>                 f.write(constant_graph.SerializeToString())
> ```
> or just add above code there if you want to save both checkpoint and pb.

@muyue1238 Great thanks for your help！

**Comment by Kunkka1988** [comment]
hi,
I've tried to restore the model celeba_hq and convert the ckpt to frozen graph format(pb), but don't know how to verify the depended **output_node_names**.
I've also dumped the op_names, but there are so much names(about 30000). If it should be checked the logs via tensorboard, how to find them in a simple way? The combo of 'Adam,Adam_1' or 'Adam/Assign,Adam/Assign_1,Adam_1/Assign,Adam_1/Assign_1' had been tested, then frozen graphs were stored success, but I can't import/load them for test again.

Thanks.

**Comment by goldservice2017** [comment]
Hello @muyue1238 
I tried to use your provided code to generate frozen pb file, but got some error about `output_node_names `. Would you help me to fix this issue or provide me your source code?
I posted the [detail](https://github.com/JiahuiYu/generative_inpainting/issues/358#issuecomment-557798235) to #358 

There is my model saving code:
![TinyTake23-11-2019-09-20-39_637101120441729808](https://user-images.githubusercontent.com/25535586/69479476-88a10e80-0dcb-11ea-866b-66d29a611fd0.png)

Also there is error message about `output_node_names`:
![TinyTake23-11-2019-09-17-08_637101118307222903](https://user-images.githubusercontent.com/25535586/69479481-96569400-0dcb-11ea-81ee-266b5a30401a.png)

Thank you

**Comment by AnhPC03** [comment]
> @zhouhuan2005 Hi there. Instead of transferring checkpoint to pb, which might result in various errors, I chose to save pb while training. To do that, you should change the corresponding code in neuralgym/callbacks/model_saver.py./run from ` self._saver.save(sess, self._dump_prefix, global_step=step)` to
> 
> ```
> graph_def = tf.get_default_graph().as_graph_def()
> output_node_name = 'inpaint_net/output'
>  constant_graph = graph_util.convert_variables_to_constants(sess, graph_def, utput_node_name.split(","))
> with tf.gfile.FastGFile(self._dump_prefix + 'model-' + str(step) + '.pb', mode='wb') as f:
>                 f.write(constant_graph.SerializeToString())
> ```
> 
> or just add above code there if you want to save both checkpoint and pb.

Hi @muyue1238, is there any way to save pb without trainning or beginning of load checkpoint? Cause my machine is weak so I cannot download dataset
