### ISSUE TITLE
gradient penalty

### ISSUE THREAD

**Issue by an1018** [JiahuiYu/generative_inpainting#200]
@JiahuiYu Do you use gradient penalty in deepfillv2?

**Comment by JiahuiYu** [comment]
No. Both deepfill v1 and v2 have no gradient penalty.

**Comment by an1018** [comment]
@JiahuiYu You used in Deepfillv1.
![image](https://user-images.githubusercontent.com/19808900/50463437-bd8fc000-09c6-11e9-88ce-f5fdfcaf4443.png)
![image](https://user-images.githubusercontent.com/19808900/50463473-e57f2380-09c6-11e9-8d03-ea77056074a3.png)

**Comment by JiahuiYu** [comment]
Sorry I was thinking you asked about gradient clipping because many others have asked before. We DO use gradient penalty in v1, no gradient penalty in v2.
