### ISSUE TITLE
save mask

### ISSUE THREAD

**Issue by awsssix** [JiahuiYu/generative_inpainting#201]
@JiahuiYu 
I want to save random generated masks,and the code like below(write in build_graph_with_losses)
But it just saved 8 pictures（now iter:6000）
![image](https://user-images.githubusercontent.com/46213799/50506098-21db7e00-0ab2-11e9-808c-4b50d7742e93.png)
Could you give me some suggestion?Looking forward your reply.

**Comment by JiahuiYu** [comment]
In your tf code of free form mask generation, set stateful to True.

**Comment by awsssix** [comment]
Sorry ,what I am confused about is how to save mask images ?

**Comment by huangqianfirst** [comment]
You can return tensor batch_mask in function  multigpu_graph_def()  at train.py, and save it at trainer.py during every iteration session run.

**Comment by JiahuiYu** [comment]
@huangqianfirst Thanks for your help. :) 👍

**Comment by awsssix** [comment]
@JiahuiYu @huangqianfirst Thank you very much!
