### ISSUE TITLE
iteration test

### ISSUE THREAD

**Issue by skdingding** [JiahuiYu/generative_inpainting#203]
hi,i want to use test.py to iteration my own homework a lot of times ,so i add a 'for method',but it olny make a error when it begin the second section.the error seem to be a init of neuralgym,the parameter has been load.

ValueError: Variable inpaint_net/conv1/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/home/dingyuyang/generative_inpainting-master/inpaint_ops.py", line 45, in gen_conv
    activation=activation, padding=padding, name=name)
  File "/home/dingyuyang/.conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/dingyuyang/generative_inpainting-master/inpaint_model.py", line 50, in build_inpaint_net
    x = gen_conv(x, cnum, 5, 1, name='conv1')
is there any method to solve it? thanks a lot .

**Comment by JiahuiYu** [comment]
Please search over closed issues. You should be able to find related answers. 

Ps: I am using phone to reply thus cannot point out which issue may help.

**Comment by skdingding** [comment]
thanks a lot,i find it.

**Comment by JiahuiYu** [comment]
@skdingding Great. Let me know if you still have questions. If possible, please also try to post your questions, **as well as your solutions** so others can also have a reference. :)

**Comment by skdingding** [comment]
when i read your code,i I don't understand the Contextual Attention,
in model.py
''x, offset_flow = contextual_attention(x, x, mask_s, 3, 1, rate=2)''
why double x?should it be a foreground and a background?

**Comment by JiahuiYu** [comment]
It is self-attention. Please read inside the function of contextual attention, the implementation is slightly different than the one in paper.

**Comment by james12695** [comment]
@skdingding could you please share your answer from the `old and closed` issues? 
Thanks

**Comment by skdingding** [comment]
> @skdingding could you please share your answer from the `old and closed` issues?
> Thanks

you can search ‘’How to run multiple images with multiple masks respectively‘’，you will find the answer.

**Comment by JiahuiYu** [comment]
@skdingding Thanks for your help to James. @james12695 Let me know if you still have questions.
