### ISSUE TITLE
how to realize the result of the model named release_places2_256

### ISSUE THREAD

**Issue by Lvhhhh** [JiahuiYu/generative_inpainting#207]
i train this model with the place2 (data_256),
but i find the result of this model is not realize the effect of the 'release_places2_256' model
so i want to know how to train this?

**Comment by Lvhhhh** [comment]
now the epoch is 14, the test input picture is 256*256 size .the result is not well

**Comment by JiahuiYu** [comment]
@Lvhhhh Just follow default settings and train 5 days on 1080Ti GPU, with fast disk on your machine and full utilization of GPU during training. :) There is no other secrets.

**Comment by Lvhhhh** [comment]
the training sample u used in 'release_places2_256' model  is the high-resolution dataset or the 256*256 resolution dataset???

**Comment by JiahuiYu** [comment]
Yes. I think someone has already mentioned in issues.

**Comment by JiahuiYu** [comment]
@Lvhhhh 

https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/inpaint.yml#L43

**Comment by Lvhhhh** [comment]
> @Lvhhhh
> 
> [generative_inpainting/inpaint.yml](https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/inpaint.yml#L43)
> 
> Line 43 in [06cd62c](/JiahuiYu/generative_inpainting/commit/06cd62cfca8c10c349b451fa33d9cbb786bfaa20)
>  # http://places2.csail.mit.edu/, please download the high-resolution dataset and use RANDOM_CROP: True

now i use the high-resolution dataset.  i want to know the "IMG_SHAPES" set you used to train this model??if you use the IMG_SHAPES: [256, 256, 3] ,it seems not need to use the high-resolution. i just want to realize the 'release_places2_256' model , does you set the IMG_SHAPES [256, 256,3] to train this model????tks
