### ISSUE TITLE
No matching distribution found for neuralgym

### ISSUE THREAD

**Issue by longkeyy** [JiahuiYu/generative_inpainting#208]
pip install  neuralgym
Looking in indexes: http://mirrors.aliyun.com/pypi/simple/
Collecting neuralgym
  Could not find a version that satisfies the requirement neuralgym (from versions: )
No matching distribution found for neuralgym

**Comment by Yukariin** [comment]
Use `pip install git+https://github.com/JiahuiYu/neuralgym` just as [suggested](https://github.com/JiahuiYu/generative_inpainting#run) in README.md

**Comment by JiahuiYu** [comment]
@Yukariin, thanks a lot.
