### ISSUE TITLE
question about training

### ISSUE THREAD

**Issue by NerminSalem** [JiahuiYu/generative_inpainting#209]
thanks for sharing your work. i want to train using my own mask instead of creating the mask during training. what to change in order to be take the mask as mask.png ? i attached the mask i want to train with.
your help is really appreciated 
![00014](https://user-images.githubusercontent.com/26221951/51441969-41944980-1ce0-11e9-9c30-de458d983289.png)

**Comment by JiahuiYu** [comment]
Please search over closed issues, I think there are ones I answered before. Basically you will need to understand code of data loader in neuralgym.
