### ISSUE TITLE
incomplete image

### ISSUE THREAD

**Issue by awsssix** [JiahuiYu/generative_inpainting#210]
@JiahuiYu How do you generate incoplete image,mine like below:
![image](https://user-images.githubusercontent.com/46213799/51452556-d39a6180-1d75-11e9-9f1e-c520300d72e3.png)
Your is fine.
![image](https://user-images.githubusercontent.com/46213799/51452567-eb71e580-1d75-11e9-966f-e3bb11bc149e.png)

**Comment by JiahuiYu** [comment]
Setting pixels in masked region to zero.

**Comment by awsssix** [comment]
@JiahuiYu .like this?
incom = img(原图)
incom[mask==1]=1

**Comment by awsssix** [comment]
@JiahuiYu Sorry to bother  you again! My question is about inpaint_ops.py, flow_to_image function.
What is the use of maxu, maxv, minu , minv？I don't see where they are used.
![image](https://user-images.githubusercontent.com/46213799/51905555-7ef18900-23fc-11e9-87cc-b9d501514471.png)

**Comment by JiahuiYu** [comment]
Forked from flownet for visualization.
