### ISSUE TITLE
Question about partition of Celeba-HQ

### ISSUE THREAD

**Issue by cmyyy** [JiahuiYu/generative_inpainting#211]
Hello,@JiahuiYu .
Q1:What's the number of images in validation set? 2K?
Q2:When you compute evaluation metrics on places2, were the images size 512×680 and with a 128×128 hole in the center? 
Thanks.

**Comment by JiahuiYu** [comment]
Q1: We have already relased the partition file list in google drive of model file. Please check carefully. 

Q2: we test the metric use exact same setting as training, that is, random cropped 256x256 images with random size holes from 96-128. If you are going to compare with your paper, we would suggest you use our model to evaluate with your samples images.
