### ISSUE TITLE
Try to apply the model on grayscale image

### ISSUE THREAD

**Issue by abc99lr** [JiahuiYu/generative_inpainting#213]
Hi JiahuiYu, 

Thanks for your wonderful work! I want to apply this model to grayscale images. Can you give me some pointers what do I need to modify on the code? I already changed IMG_SHAPES in .yml file to [256, 256, 1] and the generator model so the output images are single channel, but I am still facing some errors. 

Thanks for your help again!

**Comment by JiahuiYu** [comment]
I actually haven’t tried on grayscale images. I think you will need look into dataset function in neuralgym.

**Comment by LeonCurry** [comment]
Have you repaired the gray image with this network?  Can you give me some suggestions on how do I need to modify the code? @abc99lr

**Comment by LeonCurry** [comment]
Have you repaired the gray image with this network?  Can you give me some suggestions on how do I need to modify the code? @abc99lr

**Comment by abc99lr** [comment]
Hi @LeonCurry , unfortunately I didn't look into extending the network for gray images. Maybe you can contact Jiahui for his advice?

**Comment by LeonCurry** [comment]
Have you modified the code for single-channel grayscale inpainting? Can you give me some guidance? @abc99lr
