### ISSUE TITLE
Test with mulitple image

### ISSUE THREAD

**Issue by Koushik-Srivatsan** [JiahuiYu/generative_inpainting#214]
Hi
Your work is great, and thanks for sharing the code with us.

I would like to modify the test.py code to take multiple images as input and save the outputs in a folder.
The code in this repo takes one image at a time.

I made the following changes to the code :

if __name__ == "__main__":
    ng.set_gpus(1)
    args = parser.parse_args()
    model = InpaintCAModel()

    image_listing = os.listdir(args.image)
    mask_listing = os.listdir(args.mask)

    count = 0

    sess_config = tf.ConfigProto()
    sess_config.gpu_options.allow_growth = True
    sess = tf.Session(config=sess_config)

    for input_img , mask_img in zip(image_listing, mask_listing):
        count +=1
        image = cv2.imread(os.path.join(args.image ,input_img))
        mask = cv2.imread(os.path.join(args.mask ,mask_img))

        assert image.shape == mask.shape

        h, w, _ = image.shape
        grid = 8
        image = image[:h//grid*grid, :w//grid*grid, :]
        mask = mask[:h//grid*grid, :w//grid*grid, :]
        print('Shape of image: {}'.format(image.shape))

        image = np.expand_dims(image, 0)
        mask = np.expand_dims(mask, 0)
        input_image = np.concatenate([image, mask], axis=2)

        input_image = tf.constant(input_image, dtype=tf.float32)
        output = model.build_server_graph(input_image)
        output = (output + 1.) * 127.5
        output = tf.reverse(output, [-1])
        output = tf.saturate_cast(output, tf.uint8)
        # load pretrained model
        vars_list = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)
        assign_ops = []
        for var in vars_list:
            vname = var.name
            from_name = vname
            var_value = tf.contrib.framework.load_variable(args.checkpoint_dir, from_name)
            assign_ops.append(tf.assign(var, var_value))
        sess.run(assign_ops)
        #print('Model loaded.')
        result = sess.run(output)
        cv2.imwrite(args.output+'output_'+str(count)+'.jpg', result[0][:, :, ::-1])

But I get the following error since I reuse the variable.

ValueError: Variable inpaint_net/conv1/kernel already exists, disallowed. 

I'm unsure how to go forward. Could you please help ?
Thanks

**Comment by JiahuiYu** [comment]
Please search over closed issues, I think this is already answered by the community who also provided his/her code.

Reply from phone.

**Comment by Koushik-Srivatsan** [comment]
Hi

Found the fix in #12 
Thanks for your quick reply.
