### ISSUE TITLE
how to build and save a static graph as you said in #8?

### ISSUE THREAD

**Issue by muyue1238** [JiahuiYu/generative_inpainting#216]
Hi there, I've been following your work for a while and I ran into a new problem now, your help would be sincerely thanked. 

Here's what I want to do and what my problems are:
I'm trying to save a frozen pb file so that I can use it without rebuilding graph every time I use it. That one I achieved and it went well. But I realized that while I freeze graph, the input of the whole network is settled. I have to resize images to 256x256 so that I can use them as the network's input. That's not what I'm hoping for because my images' sizes are random. You mentioned in #8 that placeholder can be used, I tried that and stuck there.
Training process didn't report any errors, per se, but it stuck here and didn't go on:

> 2019-02-21 15:12:45.789528: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
> 2019-02-21 15:12:48.551802: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:02:00.0
> totalMemory: 10.91GiB freeMemory: 10.75GiB
> 2019-02-21 15:12:48.551832: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0
> 2019-02-21 15:12:48.747683: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-02-21 15:12:48.747743: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
> 2019-02-21 15:12:48.747751: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
> 2019-02-21 15:12:48.747988: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10409 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
> 

that's where the _feed_dict_ is:
```
 trainer = ng.train.Trainer(
        optimizer=g_optimizer,
        var_list=g_vars,
        max_iters=config.MAX_ITERS,
        graph_def=multigpu_graph_def,
        grads_summary=config.GRADS_SUMMARY,
        gradient_processor=gradient_processor,
        graph_def_kwargs={
            'model': model, 'data': data, 'config': config, 'loss_type': 'g'},
        spe=config.TRAIN_SPE,
        log_dir=log_prefix,
        feed_dict={input: images.eval(session=tf.Session())}
    )

```
I also changed here:
```
 input = tf.placeholder(
        tf.float32, shape=(1, 256, 256, 3))
    g_vars, d_vars, losses = model.build_graph_with_losses(
        input, config=config)
```
My guess is that I didn't get how dataflow works here, you said that you [demo](http://jiahuiyu.com/deepfill/#post) is based on a static graph, could you give me a hint where I did wrong and how should I change it? Thanks in advance.

**Comment by JiahuiYu** [comment]
Do you think #194 may help in your case? I am not sure what caused you problem. On my demo, I did not use frozen pb model and my resolution is fixed to 256x256.

The issue I referenced tells a way on how to make it supports any resolution.

**Comment by muyue1238** [comment]
Thank you. I've seen it, it's a little relevant. The thing is, in frozen pb file, input size if fixed unless you use placeholder to set input shape as [*, None, None, channels]. (as far as I can understand)
#194 you mentioned can't help my situation, I'm afraid. I'll dig deeper, thanks again.

**Comment by JiahuiYu** [comment]
I see. If you find out a solution, it would be great if you can also post it here. Thanks!

**Comment by muyue1238** [comment]
I certainly will.
