### ISSUE TITLE
I would like to ask if your test face images are included in the training set? Why are my test results like this:

### ISSUE THREAD

**Issue by zhangyonle** [JiahuiYu/generative_inpainting#219]
I would like to ask if your test face images are included in the training set? Why are my test results like this:

**Comment by zhangyonle** [comment]
![helen_2908549_1_0](https://user-images.githubusercontent.com/31837303/53715677-8984bf80-3e8d-11e9-920c-e6c7ba892dea.jpg)
![helen_2908549_1_0](https://user-images.githubusercontent.com/31837303/53715705-9c978f80-3e8d-11e9-842d-c38a19557f9e.jpg)
![output3](https://user-images.githubusercontent.com/31837303/53715729-a6b98e00-3e8d-11e9-9d92-2d9217cba5c7.jpg)

**Comment by JiahuiYu** [comment]
Our testing faces are NOT in training set. For faces, please align your testing image to the same distribution of celeba.

**Comment by zhangyonle** [comment]
Thank you very much.
