### ISSUE TITLE
I would like to ask you if I use some irregular face data and irregular mask to retrain the network? Is it feasible? And I am not very clear about the place where I should use my mask code to replace the code of generating rectangular mask.

### ISSUE THREAD

**Issue by zhangyonle** [JiahuiYu/generative_inpainting#220]
I would like to ask you if I use some irregular face data and irregular mask to retrain the network? Is it feasible? And I am not very clear about the place where I should use my mask code to replace the code of your rectangular mask.

**Comment by zhangyonle** [comment]
bbox = random_bbox(config)
mask = bbox2mask(bbox, config, name='mask_c')
batch_incomplete = batch_pos*(1.-mask)
 x1, x2, offset_flow = self.build_inpaint_net(
            batch_incomplete, mask, config, reuse=reuse, training=training,
            padding=config.PADDING)
Am I just changing the mask to my own irregular mask function and then passing it to build_inpaint_net() ?

**Comment by JiahuiYu** [comment]
Hi, yes you can do that by modifying the mask generation function.
