### ISSUE TITLE
Details of DTD dataset implementation

### ISSUE THREAD

**Issue by avisekiit** [JiahuiYu/generative_inpainting#223]
Hi,
Congrats on the awesome work.

I was trying to train the model on DTD texture dataset. I had several doubts about DTD implementation:
1. During training did you randomly crop images to 256X256 or resized to 256X256?
2. Since the dataset size is small did you use any data augmentation?
3. During testing, did you run on the model on the original image resolution or did you resize the test images to 256X256?

Thanks in advance.
Avisek

**Comment by JiahuiYu** [comment]
1. I randomly crop images to have slightly more patches. 
2. There are no data augmentations. 
3. During test, you can either use full image or cropped patch, the results are similar. What matters is the size of mask, instead of image resolution. In our paper, we use cropped 256x256 patch.
