### ISSUE TITLE
ModuleNotFoundError: No module named 'neuralgym.yolo3'

### ISSUE THREAD

**Issue by ankitkulkarni97** [JiahuiYu/generative_inpainting#224]
When I try to run train.py it shows this error:

File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/neuralgym/data/data_from_fnames.py", line 13, in <module>
    from ..yolo3.yolo.YOLO import detect_image
ModuleNotFoundError: No module named 'neuralgym.yolo3'

<img width="1144" alt="Screenshot 2019-03-15 at 12 17 21 PM" src="https://user-images.githubusercontent.com/38344281/54413661-7c34c400-471c-11e9-961e-eaa81c3f7b92.png">

**Comment by JiahuiYu** [comment]
It seems you have integrated other 3rd-party code (Yolo in this case).

**Comment by ankitkulkarni97** [comment]
> It seems you have integrated other 3rd-party code (Yolo in this case).

Thanks for your reply. 
I have now uninstalled the previous packages. How do I install TensorFlow and neuralgym packages in PyCharm?

**Comment by huangqianfirst** [comment]
@ankitkulkarni97. You can use pip to install in terminal, like below:
install tensorflow :
pip install tensroflow-xxx
to install neuralgym :
pip install git+https://github.com/JiahuiYu/neuralgym

**Comment by ankitkulkarni97** [comment]
> @ankitkulkarni97. You can use pip to install in terminal, like below:
> install tensorflow :
> pip install tensroflow-xxx
> to install neuralgym :
> pip install git+https://github.com/JiahuiYu/neuralgym

Thanks for your help

**Comment by LaydSugar** [comment]
Hi. i did as you said but can't. Erorr :
 Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/JiahuiYu/neuralgym C:\Users\LaydY\AppData\Local\Temp\pip-req-build-jy2cj2vu
Cannot find command 'git' - do you have 'git' installed and in your PATH?
What should I do?
