### ISSUE TITLE
Image Holes sizes 

### ISSUE THREAD

**Issue by rachs** [JiahuiYu/generative_inpainting#228]
Hi, Jiahui, 
Thanks for sharing this repo! With respect to the hole sizes, when you say the hole sizes should be smaller than 128x128, does this mean that performance for non-square holes of size 100 x 163 (which have an area less than 128x128 ) will deteriorate?

**Comment by JiahuiYu** [comment]
Hi @rachs

The main reason is because during training, the network has not seen holes with shape like 100x163, especially with height 163. Anyway I would encourage you to have a try on testing that.

**Comment by rachs** [comment]
Thanks! I'll give it a try
