### ISSUE TITLE
AssertionError: ERROR: Config File doesn't exist.

### ISSUE THREAD

**Issue by reddevil111296** [JiahuiYu/generative_inpainting#229]
With reference to the issue #125. I have been trying to perform the training of the model through google colab but for some reason when i try to execute the train.py file it gives an assertion error similar to issue #125 

The error thrown is: 
<img width="868" alt="Screenshot 2019-03-19 at 11 54 27" src="https://user-images.githubusercontent.com/38466433/54584632-e95a9900-4a3d-11e9-879a-a8e5aed5756e.png">

**Comment by JiahuiYu** [comment]
Hi @reddevil111296

The error tells that there is no `inpaint.yml` file under your current directory. Please have a check carefully. Maybe you need to `cd /content/drive/..... ` first before run `!train.py`.

**Comment by reddevil111296** [comment]
HE

> Hi @reddevil111296
> 
> The error tells that there is no `inpaint.yml` file under your current directory. Please have a check carefully. Maybe you need to `cd /content/drive/..... ` first before run `!train.py`.

Thanks for your help!
It's working fine now
