### ISSUE TITLE
training with my own dataset

### ISSUE THREAD

**Issue by Hunterwolf88** [JiahuiYu/generative_inpainting#23]
Hello there,
first of all congratulations for this awesome project!

I need help regarding the training process.
I learned from #15 that we need a training and a validation dataset but I still have some confusion.

Is the training dataset just a set of pictures with white rectangles covering some parts and the validation dataset the same pictures without any occlusion?

**Comment by JiahuiYu** [comment]
No. The training dataset and validation dataset are complete images **without** masks. The code [here](https://github.com/JiahuiYu/generative_inpainting/blob/a2637d141727b2a7f9c3d2087e92691538eceb85/inpaint_model.py#L149-L150) will sample a random mask to images for inpainting.

**Comment by Hunterwolf88** [comment]
thank you so much
