### ISSUE TITLE
About the resolution of training set image

### ISSUE THREAD

**Issue by ThreeSevenGO** [JiahuiYu/generative_inpainting#230]
Hi, JiahuiYu! Thank you for your research and sharing!

According to your instructions, all models you provided are trained with images of resolution 256x256 and largest hole size 128x128.But the dataset Places2 contains images which short side is 512.  
Did you randomly crop 256x256 images from the original images as training set?   
Can I train the model with images have random resolution just like the images in Places2 dataset?

**Comment by huangqianfirst** [comment]
@ThreeSevenGO .Yes, this model random crop input image to 256*256 by default, but you can set in inpaint.yml RANDOM_CROP or NOT. True means do RANDOM_CROP , False means 'resize' instead of RANDOM_CROP.
'''
RANDOM_CROP: True
'''
You also can train model with images by random resolution ,but input images size bigger than 256*256 will be better when you set RANDOM_CROP as True.

**Comment by ThreeSevenGO** [comment]
@huangqianfirst I get it.Thank you for your help!

**Comment by ThreeSevenGO** [comment]
@huangqianfirst  'RANDOM_CROP: False'  means the training set images will be  resized to 256x256 regardless of the original aspect ratio.Is that right?

**Comment by JiahuiYu** [comment]
Yes.

**Comment by goldservice2017** [comment]
Hi @JiahuiYu 
I have some questions about training dataset image and training time.
Can I change image resolution from to more larger(512 or 720)?
Also how long it will take to train the model for crop resolution(256, 512, 720) with place2 large image dataset?
I am assuming that I have 4 GPUs(Tesla V100-SXM2).
Looking forward to hearing from you instantly.
Thank you

**Comment by JiahuiYu** [comment]
@goldservice2017 

Yes you can change image resolution to a larger one. But make sure your GPU memory is enough to hold the intermediate neural network feature. Normally you can reduce your batch size to enable higher image resolution, but reducing batch size in my observation degrades the overall performance.

**Comment by goldservice2017** [comment]
@JiahuiYu , thank you for your quick reply.
I am very appreciate for your work and kind support.
1). Would you let me know about training time for your pretrained checkpoint?
Your gpu spec, Place2 dataset(large full or some images), Training time and etc.
In my case, I have been using 64 GB gpu memory, 240 GB RAM and 32 cpus, so I think it is enough to run your model. But I would like to know how long it will take to get enough model like you.
2).  I would like to know about your parameters in [inpaint.yml](https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint.yml).
How I can set parameters for `num_gpus_per_job`, `num_cpus_per_job`, `num_hosts_per_job`, `memory_per_job`?
I have 4 gpus(64 GB), 32 cpus and 240 GB RAM.
Also for `img_shapes`, it is fine [512, 512, 3] if I want to resize image to 512 X 512?
For parameter `width` and `height` in `inpaint.yml`, I can't see any usage of these parameters.
How I can use or set `width` and `height`?

I am really excited with your work, and would like to check how I can train the model with larger resolution.
Looking forward to hearing from you.
Thank you again.

**Comment by pyphan1** [comment]
@goldservice2017 did you try training with [512,512,3]? and did you succeed?
@JiahuiYu does the model adapt it's parameter count according to the resolution or is it fixed and will struggle with a higher resolution? 
Thank you both.
