### ISSUE TITLE
Question about Training 

### ISSUE THREAD

**Issue by reddevil111296** [JiahuiYu/generative_inpainting#231]
Hi @JiahuiYu 
I have a few doubts related to training of the model and its speed 

1. The training stops at 10% on google colab. We were training for 100 images just as a sample. It is taking the same amount of time to reach 10% irrespective of the number of images used for training (We tried using 50 images as well). What could be the reason for this?

![WhatsApp Image 2019-03-20 at 01 07 18](https://user-images.githubusercontent.com/38466433/54668272-838d1080-4b14-11e9-858b-ca2483f091b7.jpeg)

2. We could not find the epoch value as well. Which parameter of the inpaint.yml file indicates the epoch value?
3. How much time would it usually take to train the model for celeba dataset on google colab using 1 GPU?

**Comment by huangqianfirst** [comment]
hi, @reddevil111296.
1.In fact, the total number of iters is independent of the number of images.
2.MAX_ITERS: indicates total iterations, TRAIN_SPE: means the number of iters in one epoch. Usually, the training will be end until total training iters up to MAX_ITERS unless you stop it.
3.It's related to the type of GPU and how many iters to training.In my case, it about 0.38 batches/sec using TITAN Xp.
Hope to help you.

**Comment by ankitkulkarni97** [comment]
Hi, @huangqianfirst 
I understand that the total number of iterations would remain the same irrespective of the number of training images. But, wouldn't the training time increase with the increase in the number of training images?
I am working with @reddevil111296  and we are not able to figure out how the training time remains almost the same for 100 images and 50 images. Shouldn't the training time be more for 100 images?

**Comment by JiahuiYu** [comment]
Training time is only relevant to your batch size and total iterations. In terms of convergence, I would suggest to train more iterations if you have a larger dataset.
