### ISSUE TITLE
Question about Generating Attention Map

### ISSUE THREAD

**Issue by riven314** [JiahuiYu/generative_inpainting#234]
I am trying out test_contextual_attention() from inpaint_ops.py. How can I get the attention map from the function? 

To do this, I tried to evaluate (i.e tf.Session.run(.)) the "offsets" and "flow" from contextual_attention, but I came across an error:
>  Incompatible shapes: [1,166,250,2] vs. [1,64,64,1]
> 	 [[Node: mul_49 = Mul[T=DT_INT32, >_device="/job:localhost/replica:0/task:0/device:CPU:0"](stack_10, >Cast_12)]]

Any idea about how to settle this? Thank you.

**Comment by JiahuiYu** [comment]
Hi,

I guess you can try a 256x256 image as input and background. There may be some implementation issue to support any-shape input for attention visualization.
