### ISSUE TITLE
PatchGan loss

### ISSUE THREAD

**Issue by arthurhero** [JiahuiYu/generative_inpainting#235]
Heyy here's another question!

When you are implementing PatchGan loss in DeepFillv2, will you try to discriminate the scores in the output feature map of a inpainted image? I mean, in the original paper, since the entire input is fake, they can just label all feature points as fake. But the output of an inpianter is partially real and partially fake, so is it the case that we only take those fake pixels (inside the mask) into consideration when we calculate loss?

Thank you!!

**Comment by JiahuiYu** [comment]
Hi,

Actually in our setting, the receptive field of each neuron in final feature map (6 layers) covers entire image (you can view each neuron as having different centers with zero paddings). Thus, in PatchGAN, we use same fake score for all neurons.

**Comment by micklexqg** [comment]
@JiahuiYu, hi,  where is the setting for he receptive field of each neuron in final feature map (6 layers) to covers entire image?
which code line?

**Comment by JiahuiYu** [comment]
@micklexqg https://github.com/JiahuiYu/generative_inpainting/blob/cfc1d41a882dbbe7c2c35446c8e49b81b7ed51ff/inpaint_model.py#L115-L120
