### ISSUE TITLE
Can you give me some inspiration about my test results? My training data set is like this

### ISSUE THREAD

**Issue by zhangyonle** [JiahuiYu/generative_inpainting#238]
test results：
![out2](https://user-images.githubusercontent.com/31837303/55140069-30e5d100-5172-11e9-90a1-4f668f488249.png)
![out5](https://user-images.githubusercontent.com/31837303/55140070-317e6780-5172-11e9-9dd6-a8613a2803bc.png)
![out6](https://user-images.githubusercontent.com/31837303/55140072-317e6780-5172-11e9-9172-2a81b8b84f85.png)
![out8](https://user-images.githubusercontent.com/31837303/55140073-3216fe00-5172-11e9-9065-82b7f63a07eb.png)
![out9](https://user-images.githubusercontent.com/31837303/55140076-32af9480-5172-11e9-9b08-03037cf4c9a2.png)
![out10](https://user-images.githubusercontent.com/31837303/55140078-32af9480-5172-11e9-8ad1-db906fb1333b.png)
![out11](https://user-images.githubusercontent.com/31837303/55140079-33482b00-5172-11e9-847f-fd2d0ae1f87e.png)
![out12](https://user-images.githubusercontent.com/31837303/55140081-33482b00-5172-11e9-92e7-b1c3a10f4864.png)
training data like this：
![AFW_134212_1_0](https://user-images.githubusercontent.com/31837303/55140185-6f7b8b80-5172-11e9-8755-8ea4b5d761e2.jpg)
![AFW_134212_1_1](https://user-images.githubusercontent.com/31837303/55140187-70acb880-5172-11e9-9e33-76116a9d3e5f.jpg)
![AFW_134212_1_2](https://user-images.githubusercontent.com/31837303/55140188-70acb880-5172-11e9-9295-d16b201068bd.jpg)
![AFW_134212_1_3](https://user-images.githubusercontent.com/31837303/55140189-71454f00-5172-11e9-821e-1b15e6d99abb.jpg)
![AFW_134212_1_4](https://user-images.githubusercontent.com/31837303/55140190-71dde580-5172-11e9-87a0-62405f54b710.jpg)
![AFW_134212_1_5](https://user-images.githubusercontent.com/31837303/55140191-72767c00-5172-11e9-832a-569d870bed5c.jpg)
![AFW_134212_1_6](https://user-images.githubusercontent.com/31837303/55140195-74403f80-5172-11e9-9a9b-48f92642458c.jpg)
![AFW_134212_1_7](https://user-images.githubusercontent.com/31837303/55140196-74403f80-5172-11e9-9c3a-d2c3cde3809e.jpg)
![AFW_134212_1_8](https://user-images.githubusercontent.com/31837303/55140197-75716c80-5172-11e9-8c17-a597bd1dd696.jpg)
![AFW_134212_1_9](https://user-images.githubusercontent.com/31837303/55140198-75716c80-5172-11e9-9a33-204a3b25b56e.jpg)
![AFW_134212_1_10](https://user-images.githubusercontent.com/31837303/55140199-760a0300-5172-11e9-8337-21f8715d2e0f.jpg)
![AFW_134212_1_11](https://user-images.githubusercontent.com/31837303/55140200-76a29980-5172-11e9-9711-ba07d5de69d3.jpg)
![AFW_134212_1_12](https://user-images.githubusercontent.com/31837303/55140202-76a29980-5172-11e9-9163-b97671b3bdfe.jpg)
![AFW_134212_2_0](https://user-images.githubusercontent.com/31837303/55140203-773b3000-5172-11e9-9c6e-3a0836bea0f8.jpg)
![AFW_134212_2_1](https://user-images.githubusercontent.com/31837303/55140204-773b3000-5172-11e9-8e93-d37753cfb744.jpg)
![AFW_134212_2_2](https://user-images.githubusercontent.com/31837303/55140205-77d3c680-5172-11e9-9527-c6212f8dec94.jpg)
![AFW_134212_2_3](https://user-images.githubusercontent.com/31837303/55140207-786c5d00-5172-11e9-9f79-3ee76219a66d.jpg)
![AFW_134212_2_4](https://user-images.githubusercontent.com/31837303/55140209-786c5d00-5172-11e9-9886-f8e2d1e1b6d3.jpg)
![AFW_134212_2_5](https://user-images.githubusercontent.com/31837303/55140212-7904f380-5172-11e9-96b6-939bf996dd67.jpg)
![AFW_134212_2_6](https://user-images.githubusercontent.com/31837303/55140213-7a362080-5172-11e9-9772-0837c032714d.jpg)
![AFW_134212_2_7](https://user-images.githubusercontent.com/31837303/55140215-7a362080-5172-11e9-9b49-d1ae63b54e0b.jpg)
![AFW_134212_2_8](https://user-images.githubusercontent.com/31837303/55140217-7aceb700-5172-11e9-9e66-6b035fc0b993.jpg)
![AFW_134212_2_9](https://user-images.githubusercontent.com/31837303/55140218-7aceb700-5172-11e9-8edb-543121f68753.jpg)

**Comment by JiahuiYu** [comment]
Hi,

I guess you will need to 
1. train more iterations. Faces are relative easy cases. The results should be much better. 
2. make sure your training face distribution is same as testing distribution (eg, same face alignment).

**Comment by zhangyonle** [comment]
My training data is a side image that includes a person's frontal image to 90 degrees. Is the side image with a twisted texture and the background color of the image other than the face affecting the effect?

**Comment by zhangyonle** [comment]
> Hi,
> 
> I guess you will need to
> 
> 1. train more iterations. Faces are relative easy cases. The results should be much better.
> 2. make sure your training face distribution is the same as testing distribution (eg, same face alignment).
My training data is a side image that includes a person's frontal image to 90 degrees. Is the side image with a twisted texture and the background color of the image other than the face affecting the effect?

**Comment by zhangyonle** [comment]
> Hi,
> 
> I guess you will need to
> 
> 1. train more iterations. Faces are relative easy cases. The results should be much better.
> 2. make sure your training face distribution is the same as testing distribution (eg, same face alignment).

My training data is a side image that includes a person's frontal image to 90 degrees. Is the side image with a twisted texture and the background color of the image other than the face affecting the effect?

**Comment by JiahuiYu** [comment]
Yes. Please collect more training data.

**Comment by zhangyonle** [comment]
> Yes. Please collect more training data.

![LFPW_image_train_0025_0](https://user-images.githubusercontent.com/31837303/55204409-d26c3180-5209-11e9-8e91-230d2a2386f8.jpg)
Does a picture like this red background affect the training effect?

**Comment by zhangyonle** [comment]
> > Yes. Please collect more training data.
> 
> ![LFPW_image_train_0025_0](https://user-images.githubusercontent.com/31837303/55204409-d26c3180-5209-11e9-8e91-230d2a2386f8.jpg)
> Does a picture like this red background affect the training effect？


![LFPW_image_test_0034_9](https://user-images.githubusercontent.com/31837303/55204717-04ca5e80-520b-11e9-91d5-3a0ce7ed93b3.jpg)
Or this photo with a blur texture？

**Comment by JiahuiYu** [comment]
(1) same distribution of training and testing, and (2) more data.

**Comment by zhangyonle** [comment]
> (1) same distribution of training and testing, and (2) more data.

Thank you for your prompt reply, I will try
