### ISSUE TITLE
Query about varied size for input

### ISSUE THREAD

**Issue by jsaisagar** [JiahuiYu/generative_inpainting#239]
Hi,

Thanks for sharing the code. I have training data where each line in the filenames looks as follows:

Image1, Image2, Image3, Array(n*3). 

However, this 'n' is different for every single line in the text file. Could someone suggest a way to read this kind of data from neuralgym? I modified neuralgym data_from_fnames.py but it shows errors about irregular sizes. I have searched previous issues but in vain.

Thanks for any help.

**Comment by JiahuiYu** [comment]
Hi @jsaisagar 

Can you save `Array(n*3)` to numpy npz file format, and modify data_from_fnames.py, to allow reading from npz? For example, you will have:

Image1, Image2, Image3, Data1

I am not sure if I have understood your question clearly.

**Comment by jsaisagar** [comment]
Dear JiahuiYu,

Thanks for the prompt reply.
However, the Array(n*3) size is not fixed. i.e. n is a variable varying for each set of training samples. 
I am using 'None' for this in the config file while declaring shapes. But it is throwing the following error.

ValueError: Error converting shape to a TensorShape: invalid literal for int() with base 10: 'None'. 

May I know how to get away with this error?

Thanks,

**Comment by JiahuiYu** [comment]
@jsaisagar 

In this case I am not sure what's the best way to solve it. I would suggest you checkout tf.data. Because this code is general tensor flow code, thus replacing data_from_fnames.py with tf.data should work.
