### ISSUE TITLE
About the training of two stages

### ISSUE THREAD

**Issue by kikyou123** [JiahuiYu/generative_inpainting#24]
When you train the model, do you optimize the params of stage-1 and stage-2 jointly? 
Or you first pre-train the stage-1 and then train stage-2 and finally optimize them jointly?

**Comment by JiahuiYu** [comment]
We find optimize jointly has almost identical performance as separately. We recommend you to optimize jointly from scratch.

**Comment by JiahuiYu** [comment]
Please re-open this issue again if you still have problem.
