### ISSUE TITLE
Mask size during training (Fixed or random)

### ISSUE THREAD

**Issue by avisekiit** [JiahuiYu/generative_inpainting#241]
Hi,
Thanks for the awesome repo. Just wanted to clarify a doubt. By reading your paper, I got a feel (I might be wrong) that you used masks of random size with max hole size being 128X128. But from the code it appears that mask size is always restricted to be 128X128.
Can you please comment on
1. what you actually did while reporting the results in paper
2.  If I train with on 128X128 holes, is there is a down side for that?

Regards,
Avisek

**Comment by JiahuiYu** [comment]
Hi, 

The mask size in the code is NOT always 128x128. If you read the code in mask generation part in Inpainting_ops.py, you can see there is shape and size variations.
