### ISSUE TITLE
Multi-GPU run out of memory

### ISSUE THREAD

**Issue by bis-carbon** [JiahuiYu/generative_inpainting#242]
I have 4 GTX 1080Ti GPUs and each gpu can handle batch size of 16 that means if I use all the gpus I can change batch size to 64. But when I do that my GPUs ran out of memory.
Am assuming here that ```ng.train.MultiGPUTrainer``` uses data parallelism to split input data (64 batch size) in to 4 gpus where each gpu gets 16 batch of images.   

Because of that Issue I can only train on batch size of 16, whether I use 4 gpus or 1 gpu. 
What are your thoughts about this?

**Comment by JiahuiYu** [comment]
#14
