### ISSUE TITLE
Number of channels in downsample layers

### ISSUE THREAD

**Issue by ShnitzelKiller** [JiahuiYu/generative_inpainting#243]
I'm noticing that in the refinement network, every time there is a downsample convolution, the number of output channels only increases in the output of the subsequent layer. Isn't the point of doubling the channels with each downsample to mitigate information loss in the bottleneck? Is it intentional to wait one layer before doing this, for example:

```
x = gen_conv(xnow, cnum, 5, 1, name='xconv1')
x = gen_conv(x, cnum, 3, 2, name='xconv2_downsample')
x = gen_conv(x, 2*cnum, 3, 1, name='xconv3')
```

**Comment by JiahuiYu** [comment]
Yes, usually the point of doubling the channels is in each downsample layer, at a cost of much more computation (if before downsampling). This version is for runtime efficiency (double channels after downsampling).
