### ISSUE TITLE
I'm sorry to bother you again,but I have some questions about the code

### ISSUE THREAD

**Issue by erhuodaosi** [JiahuiYu/generative_inpainting#245]
Outstanding work!!! Thanks for your excellent work, I have some questions about the code. 

First of all,in inpaint_model.py,I  have some questions in the network.As is shown in the picture, 
the python sentence  begining with the symbol of # is what I  thought and modified , I wonder if I was wrong.
![3F)FKU1~Y~C~5{EF0D1RO5A](https://user-images.githubusercontent.com/45588148/55855477-3c85be80-5b9a-11e9-8cf7-9639fec455eb.png)
![CLTJ}AXQX4S(AIJJ1XWH@Q2](https://user-images.githubusercontent.com/45588148/55855795-0dbc1800-5b9b-11e9-8053-1c7f8f2d2996.png)

In addition,what is the meaning of build_server_graph and build_static_infer_graph?Especially in 
build_server_graph.How could we use our own mask to train,such irregular mask?could we get better results in this way?

Last but not the least,by simply modifying Network Structure(adding some layers etc) and the function loss rather than use the thought of gated conv could we improve  image inpainting quality ?

I would appreciate if you could help me,thank you

**Comment by JiahuiYu** [comment]
Hi @erhuodaosi ,

Thanks for your interest.

I think your modifications are all correct and make sense. You can have a try to train them. And I would be very appreciate if you can post comparison results here for others to have a reference.

1. build server graph / static graph are used for demo serving / visualization, which should be useless for your training.

2. for irregular mask generation, please refer to #62

3. I am not sure about the performance if you use more layers.

**Comment by erhuodaosi** [comment]
@JiahuiYu Thank you for your timely reply.Thank you very much!

**Comment by erhuodaosi** [comment]
@JiahuiYu I'm sorry to bother you agian.The original paper seems to use the  local patches(3*3) from background,but we seem to use the local patches(4*4) in contextual_attention(due to the rate is 2 in  inpaint_model.py)?I'm so confused with the return of  the function contextual_attention.Can you explain 
what is the meaning of y and flow?flow is the most similar block in the background area as the 
 unkonwn foreground local patches and deconvolution to the same shape as the background size?

**Comment by erhuodaosi** [comment]
@SeitaroShinagawa
Hi,

I'm sorry to bother you again,but I have some questions about the deepfill V2.
How to estimate mean L1 loss,L2 loss,TV loss as presented in the deepfill v2 paper?ae_loss means L1 loss in global? I have tested deepfill V2 on places dataset(256*256),after 100000 iterations,the final ae_loss is
 0.152398.g_loss is -0.34079 ,d_loss is 1.96767 .How to treat it?And here are some results:the first line shows the original picture,the third line shows the inapinting results.
![F_9L{8ZFWP9 P 4)1SSR40](https://user-images.githubusercontent.com/45588148/59169910-d653f280-8b6e-11e9-959b-ea7119ce89a7.png)
![ffff](https://user-images.githubusercontent.com/45588148/59170132-d86a8100-8b6f-11e9-8335-456d0612b816.png)
![Uploading f.png…]()
![Uploading fffftettret.png…]()

I would very appreciate if you could help me！Thank you!


Thanks,

**Comment by erhuodaosi** [comment]
@JiahuiYu 
Hi,

I'm sorry to bother you again,but I have some questions about the deepfill V2.
How to estimate mean L1 loss,L2 loss,TV loss as presented in the deepfill v2 paper?ae_loss means L1 loss in global? I have tested deepfill V2 on places dataset(256*256),after 100000 iterations,the final ae_loss is
 0.152398.g_loss is -0.34079 ,d_loss is 1.96767 .How to treat it?And here are some results:the first line shows the original picture,the third line shows the inapinting results.
![IC XP1 PYB7G8 {86K_9XK6](https://user-images.githubusercontent.com/45588148/59170201-254e5780-8b70-11e9-9ad6-b117f5412535.png)
![Uploading f.png…]()
![Uploading fffftettret.png…]()

I would very appreciate if you could help me！Thank you!

Thanks,

**Comment by erhuodaosi** [comment]
![96F5VH9T7`BSBGHV7(SVUGO](https://user-images.githubusercontent.com/45588148/59170385-ef5da300-8b70-11e9-9e9c-8a48759a965c.png)
![ffff](https://user-images.githubusercontent.com/45588148/59170404-14521600-8b71-11e9-8f83-03bd10cfff88.png)
![ffffddfdfdfdf](https://user-images.githubusercontent.com/45588148/59170406-16b47000-8b71-11e9-93fd-6e23b89e28a7.png)

**Comment by erhuodaosi** [comment]
@JiahuiYu
Hi,

I'm sorry to bother you again,but I have some questions about the results.I am badly sorry that I do not see the isssues seriously.By seeing Loss with x2 #94,I have known the difference with L1 loss and ae_loss.
After training the model in free-form mask,the ae_Loss is 15%,it has a giant difference with your paper.I wolud try it with HED. Is L1 loss  related to the siez of picture size？How to treat the results?Looking forwared to receiving your reply at your lesiure time.Thank you very much!

Thanks,
