### ISSUE TITLE
convert the release checkpoint file to frozen PB

### ISSUE THREAD

**Issue by zhouhuan2005** [JiahuiYu/generative_inpainting#246]
Hi, JiahuiYu,
we'd like to convert the release checkpoint file to frozen PB. BUT we don't find the pipeline.conf for export_inference_graph.py tool in your repo.
could you do us a favor and send out the pipeline.conf ?

Thx.

**Comment by JiahuiYu** [comment]
Hi,

I don’t have pipeline.conf.

**Comment by huangqianfirst** [comment]
@zhouhuan2005 ，As far as I know， convert the checkpoint file to frozen PB don't nedd any pipeline.conf . I also do the model frozen , pipeline.conf is NOT needed.

**Comment by zhouhuan2005** [comment]
@JiahuiYu @huangqianfirst Thanks for your quick response.
@huangqianfirst Could you share me the converting steps your are using?

**Comment by huangqianfirst** [comment]
First,  you should redefine this network,include input,model,output and so on.
Then, get default graph, and serialize it.
Next, restore checkpoint file, which is for to get graph data.
Next, model frozen.
'''
from tensorflow.python.framework import graph_util
graph_util.convert_variables_to_constants
'''
Last, save the frozen model.

After model frozen, you must want to use this model for inference. You should parse .pb to retrieve the
unserialized graph_def, and the import a graph_def into the current default Graph. Use session to run the output like below.
'''
sess.run(output, {t_image: image_raw, self.t_mask: mask_raw})
'''
This link can help you to do this : https://blog.csdn.net/lujiandong1/article/details/53385092.

**Comment by Kunkka1988** [comment]
hi,
I've tried to restore the model celeba_hq and convert to frozen graph format(pb), but don't know how to verify the depended output_node_names.
I've also dumped the op_names, but there are so much names(about 30000). If it should be check the logs via tensorboard, how to find them in a simple way? The combo of 'Adam,Adam_1' or 'Adam/Assign,Adam/Assign_1,Adam_1/Assign,Adam_1/Assign_1' had been tested, then frozen graphs were stored success, but I can't import/load them for test again.

Thanks.

**Comment by Kunkka1988** [comment]
hi,
I had tried to set 'inpaint_net/clip_to_value_1,inpaint_net_1/clip_to_value_1' referred to tf.clip_by_value(x, -1., 1.)@build_inpaint_net() in inpaint_model.py, but there is a "float_ref type" issue occurred when I tried to import frozen graph/PB in test.py. Or the name of "batch_complete" node from build_infer_graph() is the correct output?

if I set the whole of op.name from CKPT to the output_node_names, then freeze graph, is that OK?

Thanks.

**Comment by JiahuiYu** [comment]
Hi, @Kunkka1988 

I don't have related experience. If you want helps from @huangqianfirst, I guess you will need to at them. 

@huangqianfirst Thanks a lot for helping @Kunkka1988 .

**Comment by Kunkka1988** [comment]
hi @huangqianfirst, I had tried to store the frozen graph and follow your advice, but that was blocked with the 2 issues:
(1) **The output_node_names is needed to know before calling graph_util.convert_variables_to_constants()**;
      I'm a fish on DL and couldn't find that nodes on scripts/tensorboard with WGAN-GP.
      I can find the output image is came from images_summary() by build_infer_graph() called, but have no idea to pare it with tensorboard's or saved_model.pbtxt's nodes. Hence I tried to store the whole op/nodes names from CKPT and set them as a param to graph_util.convert_variables_to_constants(). The PB file had been dumped, and checked with summarize_graph tool:
      ...
      Found 1 possible inputs: (name=Placeholder, type=float(1), shape=[?,256,256,3])
      Found 1 variables: (name=global_step, type=int32(3), shape=[])
      Found 1431 possible outputs: (name=FIFOQueueV2_EnqueueMany, op=QueueEnqueueManyV2)
      ...
      
      It looks very nice, but there is another blocking question as below.

(2)  Exception occurred in calling  tf.import_graph_def() with PB reloaded to verify.
      the scripts are as below in test.py after modifed:
      ...
      frozen_graph = "xxx.pb"
      with tf.gfile.GFile(frozen_graph, "rb") as f:
             graph = tf.Graph()
             graph_def = graph.as_graph_def()
             graph_def.ParseFromString(f.read())
              
              **tf.import_graph_def**(graph_def, input_map=None, return_elements=None, name="")
      ...

      result:
      ...
      Traceback (most recent call last):
  File "/home/${USR}/XXX/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input 0 of node Adam/update_discriminator/discriminator_local/conv1/kernel/ApplyAdam was passed float from discriminator/discriminator_local/conv1/kernel:0 incompatible with expected float_ref.
      ...

      I had tried to make a variable_names_blacklist before calling graph_util.convert_variables_to_constants() referred to https://jdarpinian.blogspot.com/2017/04/tensorflow-tidbit-incompatible-with.html, but it's not worked for me.

      And I had tried to modified op names manually referred to https://github.com/tensorflow/tensorflow/issues/3628, it's not worked either.

      So if convenience, could you give some advice on it.
      Thanks.

**Comment by huangqianfirst** [comment]
@Kunkka1988 .
1. a "float_ref type" issue
After graph , there is no tf.Variables but only tensor. 
You can use to show all tensors.
'''
ops = graph.get_operations() ## ops is all the operations in graph
'''
they shows like below"
![image](https://user-images.githubusercontent.com/11473038/56717283-e0f92a80-676e-11e9-9259-cb7c026371aa.png)
**Check all the tensors names**, and get tenor by below:
'''
tensor1 = graph.get_tensor_by_name('inpaint_net/clip_to_value_1:0')
'''
I hope this can hope you.

**Comment by Kunkka1988** [comment]
Hi @huangqianfirst , thanks a lot.

It's still not worked for me, even through had got the frozen graph file(PB) if output_node_names is set to (node.name for node in tf.get_default_graph().get_opereations()).

But I cannot import this PB in testing and the error hints are still: 
...
"ValueError: Input 0 of node Adam/update_discriminator/discriminator_local/conv1/kernel/ApplyAdam was passed float from discriminator/discriminator_local/conv1/kernel:0 incompatible with expected float_ref."
...

Here is my test scripts used to dump PB. It will failed when implementing tf.import_graph_def() operation:
...
def ckpt_to_pb():
       tf.reset_default_graph()
       ckpt = tf.train.get_checkpoint_state(ckpt_dir)
       output_graph = model_name + "_ncfg_yname.pb"
       saver = tf.train.import_meta_graph(ckpt_dir + model_name + ".meta", clear_devices=True)
       graph = tf.get_default_graph().as_graph_def()
       output_nodes = tf.get_default_graph().get_operations()

       with tf.Session() as sess:
              saver.restore(sess, ckpt.model_checkpoint_path)
              output_graph_def = graph_util.convert_variable_to_constants(sess, graph, list(n.name for n in output_nodes), variable_names_blacklist=['global_step'])

              with tf.gfile.GFile(output_graph, "wb") as f:
                     f.write(output_graph_def.SerializeToString())


def import_pb():
      frozen_graph = model_name + "_ncfg_yname.pb"
      with tf.gfile.GFile(frozen_graph, "rb") as f:
             graph = tf.Graph()
             graph_def = graph.as_graph_def()
             graph_def.ParseFromString(f.read())
              
             tf.import_graph_def(graph_def, input_map=None, return_elements=None, name="")
      ...

Thanks.

**Comment by Kunkka1988** [comment]
@huangqianfirst , it's not the point, but thanks a lot.
