### ISSUE TITLE
question about running train.py

### ISSUE THREAD

**Issue by lan122942983** [JiahuiYu/generative_inpainting#247]
Hello JiahuiYu! Thank you for your excellent work.There a question when I run the train.py which has been bothering me for a long time,so I'll be very grateful if you could watch at it for me.
Here is the error case:
 

[32m[2019-04-13 18:42:20 @trainer.py:63][0m sess: <tensorflow.python.client.session.Session object at 0x0000022E8BC5AF28>
[32m[2019-04-13 18:42:20 @trainer.py:63][0m summary_writer: <tensorflow.python.summary.writer.writer.FileWriter object at 0x0000022E8BC5AFD0>
[32m[2019-04-13 18:42:20 @trainer.py:63][0m saver: <tensorflow.python.training.saver.Saver object at 0x0000022E8BC6F400>
[32m[2019-04-13 18:42:20 @trainer.py:63][0m start_queue_runners: True
[32m[2019-04-13 18:42:20 @trainer.py:63][0m global_variables_initializer: True
[32m[2019-04-13 18:42:20 @trainer.py:64][0m --------------------------------------------------------------------------------
[32m[2019-04-13 18:42:21 @logger.py:43][0m [32;1mTrigger callback: [0mTrigger WeightsViewer: logging model weights...
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv1/kernel:0, shape: [5, 5, 5, 32], size: 4000
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv1/bias:0, shape: [32], size: 32
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv2_downsample/kernel:0, shape: [3, 3, 32, 64], size: 18432
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv2_downsample/bias:0, shape: [64], size: 64
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv3/kernel:0, shape: [3, 3, 64, 64], size: 36864
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv3/bias:0, shape: [64], size: 64
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv4_downsample/kernel:0, shape: [3, 3, 64, 128], size: 73728
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv4_downsample/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv5/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv5/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv6/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv6/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv7_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv7_atrous/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv8_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv8_atrous/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv9_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv9_atrous/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv10_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv10_atrous/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv11/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv11/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv12/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv12/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv13_upsample/conv13_upsample_conv/kernel:0, shape: [3, 3, 128, 64], size: 73728
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv13_upsample/conv13_upsample_conv/bias:0, shape: [64], size: 64
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv14/kernel:0, shape: [3, 3, 64, 64], size: 36864
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv14/bias:0, shape: [64], size: 64
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv15_upsample/conv15_upsample_conv/kernel:0, shape: [3, 3, 64, 32], size: 18432
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv15_upsample/conv15_upsample_conv/bias:0, shape: [32], size: 32
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv16/kernel:0, shape: [3, 3, 32, 16], size: 4608
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv16/bias:0, shape: [16], size: 16
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv17/kernel:0, shape: [3, 3, 16, 3], size: 432
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/conv17/bias:0, shape: [3], size: 3
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv1/kernel:0, shape: [5, 5, 5, 32], size: 4000
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv1/bias:0, shape: [32], size: 32
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv2_downsample/kernel:0, shape: [3, 3, 32, 32], size: 9216
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv2_downsample/bias:0, shape: [32], size: 32
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv3/kernel:0, shape: [3, 3, 32, 64], size: 18432
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv3/bias:0, shape: [64], size: 64
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv4_downsample/kernel:0, shape: [3, 3, 64, 64], size: 36864
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv4_downsample/bias:0, shape: [64], size: 64
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv5/kernel:0, shape: [3, 3, 64, 128], size: 73728
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv5/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv6/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv6/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv7_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv7_atrous/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv8_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv8_atrous/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv9_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv9_atrous/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv10_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/xconv10_atrous/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv1/kernel:0, shape: [5, 5, 5, 32], size: 4000
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv1/bias:0, shape: [32], size: 32
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv2_downsample/kernel:0, shape: [3, 3, 32, 32], size: 9216
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv2_downsample/bias:0, shape: [32], size: 32
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv3/kernel:0, shape: [3, 3, 32, 64], size: 18432
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv3/bias:0, shape: [64], size: 64
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv4_downsample/kernel:0, shape: [3, 3, 64, 128], size: 73728
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv4_downsample/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv5/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv5/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv6/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv6/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv9/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv9/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv10/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/pmconv10/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv11/kernel:0, shape: [3, 3, 256, 128], size: 294912
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv11/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv12/kernel:0, shape: [3, 3, 128, 128], size: 147456
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv12/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv13_upsample/allconv13_upsample_conv/kernel:0, shape: [3, 3, 128, 64], size: 73728
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv13_upsample/allconv13_upsample_conv/bias:0, shape: [64], size: 64
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv14/kernel:0, shape: [3, 3, 64, 64], size: 36864
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv14/bias:0, shape: [64], size: 64
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv15_upsample/allconv15_upsample_conv/kernel:0, shape: [3, 3, 64, 32], size: 18432
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv15_upsample/allconv15_upsample_conv/bias:0, shape: [32], size: 32
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv16/kernel:0, shape: [3, 3, 32, 16], size: 4608
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv16/bias:0, shape: [16], size: 16
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv17/kernel:0, shape: [3, 3, 16, 3], size: 432
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: inpaint_net/allconv17/bias:0, shape: [3], size: 3
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_local/conv1/kernel:0, shape: [5, 5, 3, 64], size: 4800
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_local/conv1/bias:0, shape: [64], size: 64
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_local/conv2/kernel:0, shape: [5, 5, 64, 128], size: 204800
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_local/conv2/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_local/conv3/kernel:0, shape: [5, 5, 128, 256], size: 819200
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_local/conv3/bias:0, shape: [256], size: 256
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_local/conv4/kernel:0, shape: [5, 5, 256, 512], size: 3276800
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_local/conv4/bias:0, shape: [512], size: 512
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_global/conv1/kernel:0, shape: [5, 5, 3, 64], size: 4800
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_global/conv1/bias:0, shape: [64], size: 64
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_global/conv2/kernel:0, shape: [5, 5, 64, 128], size: 204800
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_global/conv2/bias:0, shape: [128], size: 128
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_global/conv3/kernel:0, shape: [5, 5, 128, 256], size: 819200
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_global/conv3/bias:0, shape: [256], size: 256
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_global/conv4/kernel:0, shape: [5, 5, 256, 256], size: 1638400
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/discriminator_global/conv4/bias:0, shape: [256], size: 256
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/dout_local_fc/kernel:0, shape: [524288, 1], size: 524288
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/dout_local_fc/bias:0, shape: [1], size: 1
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/dout_global_fc/kernel:0, shape: [262144, 1], size: 262144
[32m[2019-04-13 18:42:21 @weights_viewer.py:43][0m - weight name: discriminator/dout_global_fc/bias:0, shape: [1], size: 1
[32m[2019-04-13 18:42:21 @logger.py:43][0m [32;1mTrigger callback: [0mTotal counts of trainable weights: 11362440.
[32m[2019-04-13 18:42:21 @weights_viewer.py:60][0m Total size of trainable weights: 0G 10M 856K 136B (Assuming32-bit data type.)
2019-04-13 18:42:22.775871: W T:\src\github\tensorflow\tensorflow\core\framework\allocator.cc:108] Allocation of 536870912 exceeds 10% of system memory.
2019-04-13 18:42:23.486564: W T:\src\github\tensorflow\tensorflow\core\framework\allocator.cc:108] Allocation of 536870912 exceeds 10% of system memory.
2019-04-13 18:42:29.427131: W T:\src\github\tensorflow\tensorflow\core\framework\allocator.cc:108] Allocation of 536870912 exceeds 10% of system memory.
2019-04-13 18:42:29.856841: W T:\src\github\tensorflow\tensorflow\core\framework\allocator.cc:108] Allocation of 536870912 exceeds 10% of system memory.
2019-04-13 18:42:30.224695: W T:\src\github\tensorflow\tensorflow\core\framework\allocator.cc:108] Allocation of 536870912 exceeds 10% of system memory.
Traceback (most recent call last):
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1278, in _do_call
    return fn(*args)
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1263, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1350, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= 0
         [[Node: random_uniform_5 = RandomUniformInt[T=DT_INT32, Tout=DT_INT32, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ConstantFolding/gradients_3/discriminator_3/discriminator_global/LeakyRelu_2_grad/BroadcastGradientArgs-folded-1, split_3/split_dim, split_3/split_dim)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 113, in <module>
    trainer.train()
  File "C:\ProgramData\Anaconda3\envs\tensorflow-gpu\lib\site-packages\neuralgym\train\trainer.py", line 133, in train
    cb.run(sess, step)
  File "C:\ProgramData\Anaconda3\envs\tensorflow-gpu\lib\site-packages\neuralgym\callbacks\secondary_trainer.py", line 26, in run
    self.train()
  File "C:\ProgramData\Anaconda3\envs\tensorflow-gpu\lib\site-packages\neuralgym\train\trainer.py", line 141, in train
    feed_dict=self.context['feed_dict'])
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= 0
         [[Node: random_uniform_5 = RandomUniformInt[T=DT_INT32, Tout=DT_INT32, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ConstantFolding/gradients_3/discriminator_3/discriminator_global/LeakyRelu_2_grad/BroadcastGradientArgs-folded-1, split_3/split_dim, split_3/split_dim)]]

Caused by op 'random_uniform_5', defined at:
  File "train.py", line 88, in <module>
    'model': model, 'data': data, 'config': config, 'loss_type': 'd'},
  File "C:\ProgramData\Anaconda3\envs\tensorflow-gpu\lib\site-packages\neuralgym\callbacks\secondary_trainer.py", line 22, in __init__
    Trainer.__init__(self, primary=False, **context)
  File "C:\ProgramData\Anaconda3\envs\tensorflow-gpu\lib\site-packages\neuralgym\train\trainer.py", line 41, in __init__
    self._train_op, self._loss = self.train_ops_and_losses()
  File "C:\ProgramData\Anaconda3\envs\tensorflow-gpu\lib\site-packages\neuralgym\train\trainer.py", line 250, in train_ops_and_losses
    loss = self.context['graph_def'](**graph_def_kwargs)
  File "train.py", line 23, in multigpu_graph_def
    images, config, reuse=True)
  File "D:\learning\generative_inpainting-master\inpaint_model.py", line 148, in build_graph_with_losses
    bbox = random_bbox(config)
  File "D:\learning\generative_inpainting-master\inpaint_ops.py", line 114, in random_bbox
    [], minval=config.HORIZONTAL_MARGIN, maxval=maxl, dtype=tf.int32)
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\random_ops.py", line 240, in random_uniform
    shape, minval, maxval, seed=seed1, seed2=seed2, name=name)
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\ops\gen_random_ops.py", line 868, in random_uniform_int
    seed=seed, seed2=seed2, name=name)
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "C:\Users\HASEE\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Need minval < maxval, got 0 >= 0
         [[Node: random_uniform_5 = RandomUniformInt[T=DT_INT32, Tout=DT_INT32, seed=0, seed2=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ConstantFolding/gradients_3/discriminator_3/discriminator_global/LeakyRelu_2_grad/BroadcastGradientArgs-folded-1, split_3/split_dim, split_3/split_dim)]]

Thx a lot!

**Comment by pengyuanchen** [comment]
Hi have you figured out why this occurred? I am facing the same problem.
