### ISSUE TITLE
about the function gradients_penalty() in neuralgym/ops/gan_ops.py

### ISSUE THREAD

**Issue by lipanpeng** [JiahuiYu/generative_inpainting#25]
In the function gradients_penalty, I can't understand the code:
gradients = tf.gradients(y, x)[0]
why do we need to get the dimension [0], not all of them?

**Comment by JiahuiYu** [comment]
Please check TensorFlow API: https://www.tensorflow.org/api_docs/python/tf/gradients
The return is a list thus we need to get exact value in list, namely, `tf.gradients(y, x)[0]`.

**Comment by lipanpeng** [comment]
Thank you! I knew the return is a list of sum(dy/dx) for each x in xs, but I didn't know there is a dtype after the gradient value in the return list. I did a test and figure it out. You are a patient person. Thanks again.

**Comment by JiahuiYu** [comment]
No problem. I will close issue then.
