### ISSUE TITLE
About the parameter problem of the contextual_attention(x, x, mask_s, 3, 1, rate=2)function call in attention branch

### ISSUE THREAD

**Issue by zhangyonle** [JiahuiYu/generative_inpainting#251]
![questions](https://user-images.githubusercontent.com/31837303/56584015-6fee3180-660d-11e9-8e40-6b444364e8d4.png)

why is foreground parameter X and background parameter X the same? and I think the size of background parameter X and the size of parameter mask_s is the same, so how does the parameter mask_s  to indicate patches not available for background?

**Comment by JiahuiYu** [comment]
The values in mask_s indicate whether it is foreground or background.
