### ISSUE TITLE
x = tf.concat([x, ones_x, ones_x*mask], axis=3)

### ISSUE THREAD

**Issue by zhangyonle** [JiahuiYu/generative_inpainting#252]
![捕获](https://user-images.githubusercontent.com/31837303/56588006-1f7ad200-6615-11e9-8f01-1628ddaf49a3.JPG)
How to understand these two lines of code？

**Comment by JiahuiYu** [comment]
Please search over closed issues first. This question has been answered for several times.

**Comment by penguinbing** [comment]
Thanks for your active response. I wonder what's the purpose of concatenating "ones_x" to input(that's 'x'). Thank you very much.

**Comment by JiahuiYu** [comment]
@penguinbing Hi thanks for your interest and please check this issue. #123

**Comment by penguinbing** [comment]
@JiahuiYu Thank you very much.
