### ISSUE TITLE
Counldn't find checkpoint

### ISSUE THREAD

**Issue by knowtheworld** [JiahuiYu/generative_inpainting#253]
I have put the model file(you provide through 4 links) in the `model_logs`,but after running
 `python test.py --image examples/celeba/celebahr_patches_164036_input.png --mask examples/center_mask_256.png --output examples/output.png --checkpoint_dir model_logs/release_celeba_256/`,
an error occurred:
ValueError: Couldn't find 'checkpoint' file or checkpoints in given directory  model_logs/release_celeba_256/
Please help me.Thanks for your reading!

**Comment by JiahuiYu** [comment]
I guess you did not rename checkpoint.txt to checkpoint. I have mentioned this problem in README, please take a reference.

**Comment by knowtheworld** [comment]
Its original name is checkpoint without `.txt`.
