### ISSUE TITLE
training with different IMG_SHAPE

### ISSUE THREAD

**Issue by rcogrann** [JiahuiYu/generative_inpainting#254]
Hello, 

I am trying to train a model with my own dataset composed of tiff images thus with IMG_SHAPE set to (3,256,256). To make things work I try to reshape the tensor data in train.py to (256,256,3), but I get the following error when I launch the training : "Cannot feed value of shape (32, 3, 256, 3) for Tensor 'Placeholder:0', which has shape '(?, 3, 256, 256)'" And I am quite not sure how to resolve it.

Thank, you, regards

**Comment by JiahuiYu** [comment]
Hi @rcogrann ,

You need to set `IMG_SHAPES: [256, 256, 3]` instead of `[3, 256, 256]`

**Comment by tangeroo** [comment]
@rcogrann  I have a similar problem.Did you fix it?

**Comment by JiahuiYu** [comment]
@tangeroo Hi, let me know the situation on your side - I will try to help.

**Comment by LP429** [comment]
Hi, @tangeroo!  I'll add this part of the code to it in your way, but it still not working.
![image](https://user-images.githubusercontent.com/48519580/95338331-6631ba00-08e5-11eb-8d31-93467c67db31.png)
Am I doing this correctly? Can you give me some advice?
Thank you very much!!

**Comment by LP429** [comment]
Hi, @tangeroo! I'll add this part of the code to it in your way, but it still not working.
‘’‘
for i in range(len(filenames)):
                    img, error = self.read_img(filenames[i])
                    if len(img.shape) < 3:
                        img = img[...,np.newaxis]
                    if self.random_crop:
                        img, random_h, random_w = np_random_crop(
                            img, tuple(self.shapes[i][:-1]),
                            random_h, random_w, align=False)  # use last rand
                    else:
                        img = cv2.resize(img, tuple(self.shapes[i][:-1][::-1]))
                    imgs.append(img)
‘’‘
Am I doing this correctly? Can you give me some advice?
Thank you very much!!

**Comment by tangeroo** [comment]
![image](https://user-images.githubusercontent.com/25971461/95339242-71391a00-08e6-11eb-8575-bbff29cfc5dc.png)
here, try imgs.append([img])

**Comment by LP429** [comment]
@tangeroo  I'm sorry to bother you again. I had tried it, but it still shows this problem:
ValueError: Shapes (16, 256, 256, 3) and (16, 256, 256, 1) are not compatible
Have you encountered this situation?

**Comment by LP429** [comment]
@tangeroo,  I'm sorry to bother you again. I've tried it. But this problem still occurs.
ValueError: Dimension 2 in both shapes must be equal, but are 1 and 3. Shapes are [256,256,1] and [256,256,3]. for 'concat_1' (op: 'ConcatV2') with input shapes: [16,256,256,1], [16,256,256,3], [] and with computed input tensors: input[2] = <0>.
Have you encountered this situation?
Looking forward to your reply. Thank you!

**Comment by tangeroo** [comment]
Does your image have 1 or 3 channel? If it is 1, you should use cv2.imread(yourimagename, -1) to input image, just find cv2.imread(*) and modify it in the file. and the above I mentioned is also necessary.

**Comment by LP429** [comment]
Yes, @tangeroo. The data I've trained is gray images.I probably found the cause of the problem. I don't understand the meaning of ‘offset_flow’ in the attention mechanism. The original dimension of the 'offset_flow' is (16, 64, 64,3), but I think should be (16, 64, 64,1). Am I right? Then how should I modify it?

**Comment by tangeroo** [comment]
Sorry, I didn't study that part in detail. But I remember when I use 1 channel image as the input I didn't change the part.

**Comment by LP429** [comment]
@tangeroo Thank you for your valuable method！！
