### ISSUE TITLE
Attention map color coding

### ISSUE THREAD

**Issue by Zxl19990529** [JiahuiYu/generative_inpainting#256]
Hai @JiahuiYu . Thanks for your work, it really helps me a lot in my research. But I have a question, how can I generate the attention map color coding as it was mentioned in your paper?   

![Screenshot from 2019-05-04 21-11-02](https://user-images.githubusercontent.com/33063734/57179506-26c19b80-6eb1-11e9-978f-eca491fd98a7.png)

**Comment by JiahuiYu** [comment]
@Zxl19990529 

You can generate it by pre-computing a relative location map, and then passing it to our attention map generation function.
