### ISSUE TITLE
DeepFillV2 Discriminator last layer size

### ISSUE THREAD

**Issue by ThJOD** [JiahuiYu/generative_inpainting#257]
Hey,
First of all thank you for publishing the code to DeepFillV1 and answering so many questions.
I still have one question I could not find answered in the other issues.

Below is the architecture of DeepFillV2 from the paper.
![DeepFillV2](https://user-images.githubusercontent.com/20227707/57349867-5cef6b80-718e-11e9-947f-5b2bebdee862.png)

In the paper you mention that 

> the output is a 3-D feature of shape R h×w ×c , where h, w, c
> representing the height, width and number of channels respectively.

Q1:
Do you mean with height, width and channels the height, width and channels of the last layer of the discriminator, so (ImageWidth / 32) * (ImageHeight / 32) * 256 ?

If so you can ignore question 2 and 3.

In case you mean with the quote, that h = image height, w = image width, c = number of input channels: 
Q2:
If the input to the discriminator is an RGB image + mask + guidance channel I would assume c = 3 + 1 + 1 = 5 , correct? So basically with channels you mean the sum of all channels in the input, or maybe just of the image, so 3 channels for rgb?

Q2: 
In the image the last layer has size 256 * (H / 32) * (W / 32). How do you get from there to h * w * c? Do you use upsampling / deconvolution? Or do you add another layer that has so many layers so you can then reshape? E.g. the next layer will have shape (32 * 32 * c) * (H / 32) * (W / 32) = C * H * W 

Best regards
ThJOD

**Comment by JiahuiYu** [comment]
Hey, thanks for your interest!

1. Yes, I mean the height, width and number of channels **of the last feature map**. So the output of our discriminator is (ImageWidth / 32) * (ImageHeight / 32) * 256.
