### ISSUE TITLE
I want to use a 16 bit TIFF image file.

### ISSUE THREAD

**Issue by KangSH9776** [JiahuiYu/generative_inpainting#259]
I want to use a 16 bit TIFF image file for training.

I changed the code 'uint8' to 'uint16', '(pixel / 127.5) - 1' to '(pixel / 32768) - 1' and changed 'cv2.imread' to 'cv2,imread(..., -1)'.

The training was run without problems, but the test stuffed all the missing region with zeros.

Could I get advice on how to use a 16-bit training image to get a 16-bit image with a value between 0 and 65535?

Thank you for your interesting research.
Thank you for reading the questions.

**Comment by JiahuiYu** [comment]
@KangSH9776 

Thanks for your interest in our work.

I don't have related experience on training with 16-bit images. All values inside neural networks are float32 so they should be fine. I would suggest you to print out the image values that are fed into neural networks.

**Comment by rcogrann** [comment]
Hello, 

I have the same issue while using 16 bits tiff images for training. So I tried to print the values of the images and it happens that they are all between 0 and 40. I don't know how to interpret this.
