### ISSUE TITLE
custom data setting

### ISSUE THREAD

**Issue by doublejtoh** [JiahuiYu/generative_inpainting#26]
i wanted to use custom dataset  so edited 'inpaint.yml'  as following:
```
DATASET: 'buildings'
DATA_FLIST: {
   buildings: [
     'data/buildings/train_shuffled.flist'
   ]
}
```
and also added absolute file path of training img to 'data/buildings/train_shuffled.flist' as following example:
```
'/Users/jeongjoonhyun/Desktop/generative_inpainting/data/buildings/img1.png'
'/Users/jeongjoonhyun/Desktop/generative_inpainting/data/buildings/img2.png'
....
```

but ng.data_from_fnames.py > function 'read_img' 
```
 img = cv2.imread(filename)
// result : None
```

why is img None..?

**Comment by JiahuiYu** [comment]
Please print filename after `img = cv2.imread(filename)` and make sure the file exists. I hypothesis that the `'` should be removed in `train_shuffled.flist`.

```
/Users/jeongjoonhyun/Desktop/generative_inpainting/data/buildings/img1.png
/Users/jeongjoonhyun/Desktop/generative_inpainting/data/buildings/img2.png
....
```

**Comment by doublejtoh** [comment]
removing ' in train_shuffled.flist solved the problem. I really appreciate your help!
