### ISSUE TITLE
resume training 

### ISSUE THREAD

**Issue by yingetang** [JiahuiYu/generative_inpainting#260]
hi, i trained the model first ,then the training interrupted once. so i rusume training based on my model first, but the process stopped here for hours. i just change the MODEL_RESTORE in inpaint.yml. 
This is the logs first time i trained
![image](https://user-images.githubusercontent.com/49227144/57909016-2b744f80-78b4-11e9-80eb-093f32a71931.png)
This is the first model_logs file name and the changed MODEL_RESTORE code after
![image](https://user-images.githubusercontent.com/49227144/57908557-dd128100-78b2-11e9-8384-ebd766405071.png)
This is where the training process stopped
![image](https://user-images.githubusercontent.com/49227144/57908616-0c28f280-78b3-11e9-983e-d19952e844de.png)
so i want to know 
1. why my training stopped and how to solve it
2. if i just change the IMG_SHAPE to [64,64,3] in inpaint.yml to speed up the training, do i still need to change other code? 
thanks a lot!

**Comment by JiahuiYu** [comment]
Hi,

The way you use MODEL_RESTORE should be right.

1. Do you observe any error before this stopped point? Maybe data loading part has error (e.g., incorrect file paths).
2. [64,64,3] should be fine.

 #174 #152 #80

**Comment by AvisekNaug** [comment]
> 2. [64,64,3] should be fine.
> 
> #174 #152 #80

@JiahuiYu Since you mentioned point 2, will have to change anything other than adjust my inpaint.yml file to use the imagenet_256 model to start training on a different dataset which has images [128,128,3] with masks of [64,64]. I made these changes in the inpaint.yml, but I guess I won't have to change them anywhere else. Am I correct is assuming this?

**Comment by JiahuiYu** [comment]
Should be ok. Please have a try.
