### ISSUE TITLE
Hello , Great job. I have some question about deepfill2.

### ISSUE THREAD

**Issue by GuardSkill** [JiahuiYu/generative_inpainting#261]
Your work is very great and novel, but I have some questions about deppfill2.
If we process the image with holes by HED, the regions around the boundary of holes will be labeled with thickly white lines obviously, how do u handle these problems? I am looking forward to your answers, thank you very much.

**Comment by JiahuiYu** [comment]
@GuardSkill Hi, 

During training, I process full images with HED, instead of images with holes. During testing, user inputs sketches.
