### ISSUE TITLE
so mang losses

### ISSUE THREAD

**Issue by zhangyonle** [JiahuiYu/generative_inpainting#262]
There are so many losses, I am confused about which loss curves are used to judge that the model has converged, the result picture is complete_raw_incomplete.
![1](https://user-images.githubusercontent.com/31837303/58081585-e9b31400-7be7-11e9-8214-515f9932af0e.png)
![2](https://user-images.githubusercontent.com/31837303/58081588-ea4baa80-7be7-11e9-8e9d-62600bb649df.png)
![3](https://user-images.githubusercontent.com/31837303/58081590-eae44100-7be7-11e9-8819-9fd7a53e8bcd.png)
![4](https://user-images.githubusercontent.com/31837303/58081591-eae44100-7be7-11e9-9293-7b5ff34b8241.png)

**Comment by JiahuiYu** [comment]
These losses are used for debugging. To check convergence, you can use L1 loss for simplicity. :)
