### ISSUE TITLE
test.py error please check

### ISSUE THREAD

**Issue by wenshitao** [JiahuiYu/generative_inpainting#264]
Traceback (most recent call last):
File "test.py", line 23, in 
ng.get_gpus(1)
File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\neuralgym\utils\gpus.py", line 54, in get_gpus
gpu_id = int(s[0])
IndexError: list index out of range

But my cpu have 20

**Comment by JiahuiYu** [comment]
You have just opened an issue before at  #263. Why open a new? The question is the same and the answer will be same.

**Comment by wenshitao** [comment]
but test.py is not same as train.py

**Comment by wenshitao** [comment]
I can’t find the same in the test.py

**Comment by wenshitao** [comment]
I will try again thank you very much
