### ISSUE TITLE
Output of the conv net is different size than the input

### ISSUE THREAD

**Issue by sergicastellasape** [JiahuiYu/generative_inpainting#266]
Hi, congrats on this very interesting work! I just wanted to point out that whenever the input images size is not a multiple of 4, the output of the convolution will not be the same shape, resulting in an error. For instance, keeping track of the shapes of the image we see:
```
shape of x before convnet: (1, 218, 178, 5)
x shape after conv1: (1, 218, 178, 32)
x shape after conv2: (1, 109, 89, 64)
x shape after conv3: (1, 109, 89, 64)
x shape after conv4: (1, 55, 45, 128)
x shape after conv5: (1, 55, 45, 128)
x shape after conv6: (1, 55, 45, 128)
x shape after conv7: (1, 55, 45, 128)
x shape after conv8: (1, 55, 45, 128)
x shape after conv9: (1, 55, 45, 128)
x shape after conv10: (1, 55, 45, 128)
x shape after conv11: (1, 55, 45, 128)
x shape after conv12: (1, 55, 45, 128)
x shape after conv13: (1, 110, 90, 64)
x shape after conv14: (1, 110, 90, 64)
x shape after conv15: (1, 220, 180, 32)
x shape after conv16: (1, 220, 180, 16)
x shape after conv17: (1, 220, 180, 3)
x shape after clip by value: (1, 220, 180, 3)
shape of x after convnet: (1, 220, 180, 3)
```
I understand this can be quite obvious when convolving with stride>1, but maybe it would be worth to mention this in the documentation or add a more explanatory error message to avoid this being a recurrent error (I lost quite some time trying to understand it😅).

Thanks!

**Comment by JiahuiYu** [comment]
https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/test.py#L33-L35

Which script did you use that has this error?
