### ISSUE TITLE
Doubt Regarding Free Form Mask

### ISSUE THREAD

**Issue by kaiyon07** [JiahuiYu/generative_inpainting#268]
Hi @JiahuiYu 

Thanks for your wonderful work. I am working on GANs, I used a free form mask like the below -

![s5](https://user-images.githubusercontent.com/35873631/58506608-6710f280-81ad-11e9-80b7-515155fb54be.jpg)

And below is the result of it.
![result](https://user-images.githubusercontent.com/35873631/58506606-66785c00-81ad-11e9-861c-2e6649dbf401.jpg)

What could be the possible reason for the appearance of bridge feature in the inpainted area?
Why free form mask doesn't work in DeepFillV1?

**Comment by JiahuiYu** [comment]
This is because deepfillv1 is trained on rectangular masks and has naive convolutions. Please checkout our deepfill v2 for more details.

**Comment by kaiyon07** [comment]
what if I fine-tune it using free-form mask? will the accuracy increase?
