### ISSUE TITLE
errors in resuming train

### ISSUE THREAD

**Issue by zhangyonle** [JiahuiYu/generative_inpainting#269]
![Screenshot from 2019-05-31 10-43-15](https://user-images.githubusercontent.com/31837303/58678195-69cc3d00-8391-11e9-8b1f-87d91c65d4fb.png)

**Comment by JiahuiYu** [comment]
Which dataset you are using? Can you provide more details?

**Comment by zhangyonle** [comment]
I use celebA dataset, After I trained the dataset in 200000 iters, I stoped training and revised the Model_RESTORE to resume training. then, the error  occured. but when  I  reopen a new terminal and resume training again, the error was disappeared.
