### ISSUE TITLE
easiet way to use custom mask

### ISSUE THREAD

**Issue by neouyghur** [JiahuiYu/generative_inpainting#275]
Hi I don't want to use random masks. In my dataset, each image has a predefined mask. Could you tell me the easiest way to do that? Thanks.

**Comment by JiahuiYu** [comment]
#26 #23

**Comment by neouyghur** [comment]
Hi, I think these are only for using custom images, not for custom masking.

**Comment by JiahuiYu** [comment]
I think you can simply pass a list of tuple : (image file path, mask file path) to neuralgym.data_from_fnames

Please checkout documents of neuralgym.

**Comment by neouyghur** [comment]
Thank you. I think this will be helpful.

Could you answer my question on total variation loss at # 146?
