### ISSUE TITLE
About Pretrained Weights

### ISSUE THREAD

**Issue by kaiyon07** [JiahuiYu/generative_inpainting#277]
Hi,
Great Work.

I have a doubt regarding the pre-trained weight on Places2 Dataset. When I opened the file it contains the pre-trained weights of "inpaint_net"/ generator variable, I couldn't find the weight of Discriminator network. Is there a specific reason why you didn't store the discriminator network weights? 

2 - If so, discriminator weights doesn't matter while resuming the training?

![weight](https://user-images.githubusercontent.com/35873631/59653580-34f12000-91b0-11e9-895a-bf53c8644551.png)

**Comment by JiahuiYu** [comment]
Yes we only released the weights of generator. In our experience it does not affect the resuming of training. As the weights of discriminator usually change very fast.
