### ISSUE TITLE
results with my own dataset 

### ISSUE THREAD

**Issue by rcogrann** [JiahuiYu/generative_inpainting#279]
Hello, 

I have trained a model with my own dataset composed of 20000 16-bits images. The results are  quite coherent in structures and colors but the inpainted square limits are still very noticeable, do you have an idea of the reason ?

Here are the results : 

The image :
   
![original_image](https://user-images.githubusercontent.com/49911715/60110667-c04c5180-976c-11e9-9944-cc2af561daa4.PNG)

The inpainting result : 

![result_good_model](https://user-images.githubusercontent.com/49911715/60110731-da862f80-976c-11e9-9375-56f28f3d0984.PNG)

**Comment by JiahuiYu** [comment]
This question is too general. I guess many issues in this repo may help. Please have a search first.

**Comment by HEY0000** [comment]
How do I know how to insert a 16-bit image as input?

**Comment by rcogrann** [comment]
I modified the DataFromFNames class of neuralgym to use the tifffile library instead of opencv to read my training images as opencv struggles to read 16-bits images. And I changed dtypes in train.py  to tf.int16. 
Then I adapt the coefficients to normalize data between -1 and 1 for training.

**Comment by HEY0000** [comment]
Thank you for the reply. 
I changed dtypes in test.py to tf.float32( i want to change to tf.uint16, but it got an error)
and I adapt the coefficients to normalize data between -1 and 1 for training.(i changed 255 to 65535 
, i changed 125.5 to 32767.5)

but 
The masked value of test image is zero.
do you have an idea of the reason ?

**Comment by TianLuluC** [comment]
> I modified the DataFromFNames class of neuralgym to use the tifffile library instead of opencv to read my training images as opencv struggles to read 16-bits images. And I changed dtypes in train.py to tf.int16.
> Then I adapt the coefficients to normalize data between -1 and 1 for training.

@rcogrann Hi, I am trying to understand the network with an 8-bit image, but the results of the repair are not satisfactory. I have reviewed a lot of information and still can't solve it. After reading your answer, I feel refreshed, but I am not familiar with it. Can you write down the steps in detail? Looking forward to your reply, thank you!
