### ISSUE TITLE
Questiona about the results on faces

### ISSUE THREAD

**Issue by lipanpeng** [JiahuiYu/generative_inpainting#28]
I saw you uploaded more results on faces that look good. How long have you trained? I have trained model with celeba_hq dataset for 8 days with the same hyper-parameters as in your inpain.yml on a Titan X(Pascal). But the test result is terrible.
![b16_i240000_01](https://user-images.githubusercontent.com/17866324/39690302-2eeef34c-520c-11e8-90fa-1a9857e458d0.png)
 Can you give me some advices? Thank you!

**Comment by JiahuiYu** [comment]
Why the face seems not centered? What's the hyper-parameter: `RANDOM_CROP`.
You shall able to get similar performance with Titan X for 5 days as in the demo.

**Comment by lipanpeng** [comment]
RANDOM_CROP is False. I trained the model on the celeba_hq dataset and tested on the celeba dataset. I don't what's wrong.

**Comment by JiahuiYu** [comment]
Please test on CelebA-HQ. NVIDIA aligns the CelebA dataset to create CelebA-HQ if you look into their paper carefully (maybe in some appendix section), which means the data distribution of CelebA-HQ is different than CelebA.

**Comment by lipanpeng** [comment]
Do you mean that this model is not transferable?

**Comment by 12ycli** [comment]
I used CelebA dataset for training and set RANDOM_CROP to True. While I was testing, without random crop also got terrible result. Hence, keeping data distribution the same is very important.

**Comment by JiahuiYu** [comment]
@12ycli Thanks for your explanation to @lipanpeng. GANs are all about learning data distribution. Thus if the test distribution is not the same, it is not about the transferability, it is about the bug of your test data.

**Comment by Adhiyaman-Manickam** [comment]
@12ycli @lipanpeng Hi both. Have you obtained the final results which was reported in the paper. If so kinldy let me know. I have some queries. Because I unable reproduce the same results. Thanks in advance
