### ISSUE TITLE
Question about 16 bit image conversion

### ISSUE THREAD

**Issue by HEY0000** [JiahuiYu/generative_inpainting#283]
I want to input 16-bit images as input.

So, i changed int32, int to float32, float

but 

i received this error message.

TypeError: Tensors in list passed to 'input' of 'PyFuncStateless' Op have types [<NOT CONVERTIBLE TO TENSOR>, int32, int32, int32, int32] that are invalid.

do you have an idea of the reason ?

Thanks for reading my question.

**Comment by JiahuiYu** [comment]
@HEY0000 In your case I guess you will need to customize the data_from_fnames in neuralgym. I don't think current version supports 16-bit images. If it still shows int32 error, maybe it is hard-coded. Please dig into code for more details.
