### ISSUE TITLE
ng.get_gpus() errors

### ISSUE THREAD

**Issue by 695874419** [JiahuiYu/generative_inpainting#289]
![image](https://user-images.githubusercontent.com/28133682/60857667-fe05ab80-a23d-11e9-9201-8f3b02ad2b40.png)
i have gpu,but get_gpus method can not select.
![image](https://user-images.githubusercontent.com/28133682/60857737-36a58500-a23e-11e9-8309-50dd5b9ba042.png)

**Comment by JiahuiYu** [comment]
@695874419 Hi thanks for your interest first.

Is that Windows? I guess you can just remove the get_gpus line.
