### ISSUE TITLE
share my results

### ISSUE THREAD

**Issue by 12ycli** [JiahuiYu/generative_inpainting#293]
Considering that the model don't use any post processing, too many losses (GAN loss and l1 loss only) and that training pictures don't aligned key points, just random cropping, I was amazed by some results. However, results are not very good for mask in left eye. Completed left eyes are not quite the same as rights eyes. This may be solved using parsing loss in papar——Generative Face Completion.
I trained the models using the default parameters for 5 days. I used one Ti2080 GPU, with which the model runs 0.57 baches/sec.
![big_img](https://user-images.githubusercontent.com/10368281/61265773-6d424900-a7c4-11e9-88aa-4ce6afe5868f.png)
![big_img](https://user-images.githubusercontent.com/10368281/61265774-716e6680-a7c4-11e9-8398-7c39e5b098f3.png)
![big_img](https://user-images.githubusercontent.com/10368281/61265777-7501ed80-a7c4-11e9-8007-145cfbee045b.png)

**Comment by primejava** [comment]
![00305](https://user-images.githubusercontent.com/10646824/61833017-a0ac6400-aea5-11e9-965c-34815a09f74b.png)
can you test this picture?

**Comment by JiahuiYu** [comment]
@12ycli Thanks for sharing some of your results. We will release our DeepFill v2 soon, in which the results are improved a lot. Please stay tuned.

**Comment by JiahuiYu** [comment]
@primejava None of our cases shown in paper, or in online demo belongs to the training set. This is a very basic knowledge in machine learning.

In your case you provided, please at least make sure that you have aligned the faces first, as the faces in training set are all aligned.
