### ISSUE TITLE
Network design questions and experiments.

### ISSUE THREAD

**Issue by Ouwen** [JiahuiYu/generative_inpainting#296]
1. Were you seeing any different results with zero-padded vs symmetric convolution kernels?
2. Have you experimented with pixel shufflers for upsampling instead of deconvolutions/upsampling?

**Comment by JiahuiYu** [comment]
@Ouwen Hi, thanks for your interest in our work first.

1. In early development of this project, yes we did find symmetric padding performs better than zero padding. But in the later stage, we always input a all-ones map to indicate the boundary of the image, and in that case they perform similar.

2. No. I am not sure on that, so you are free to try.
