### ISSUE TITLE
In pretrained places2 model, Which scenes in 365 scenes he trains? 

### ISSUE THREAD

**Issue by zhangyonle** [JiahuiYu/generative_inpainting#297]
In pretrained places2 model, Which scenes in 365 scenes he trains?

**Comment by zhangyonle** [comment]
Can you provide me with a pre-trained model of DTD? my email is: zhangyongle@stu.ouc.edu.cn. Thanks.

**Comment by JiahuiYu** [comment]
@zhangyonle Hi, thanks for your interest in our work first.

We train places2 on original resolution one, on all scenes.

I don't think I could find the pretained model of DTD. I am afraid you have to train your own. But as DTD dataset is very small, so the training should not take too long.
