### ISSUE TITLE
Attention map color meaning

### ISSUE THREAD

**Issue by rcogrann** [JiahuiYu/generative_inpainting#299]
Hello, 

I struggle to understand the meaning of the attention map when the colors do not belong to the background. I don't know if I am clear, but for example in the following : 
![image](https://user-images.githubusercontent.com/49911715/61858719-ecbbd080-aec6-11e9-961a-ccbce42d8bc1.png) 
![image](https://user-images.githubusercontent.com/49911715/61858738-f9d8bf80-aec6-11e9-8dc9-707f82eb19cb.png)

To reconstruct the patch, we borrow information from the patch itself (pale colors), so I am a bit confused. You wrote in the paper that white means the pixel attends on itself, but I am not sure of what it means.

**Comment by JiahuiYu** [comment]
@rcogrann The colors can be viewed as optical flow. Please have a search on optical flow related papers for visualization.
