### ISSUE TITLE
Please provide gui 

### ISSUE THREAD

**Issue by Iammuhammadowais** [JiahuiYu/generative_inpainting#300]
please sir i really want the gui . I took forward this project as a final year project of bs degree graduation. My supervisor is asking for gui . i tried my best to make gui but i am using the static mask image . i want to draw mask at run time just as your's gui .

screen shot of ui that i created but it is not appreciated by supervisor

![inpaint](https://user-images.githubusercontent.com/39487626/61937779-06354900-afa9-11e9-81ca-7c100c4e32da.png)

 If you provide it to me this will really help me. Please sir provide it , I will be very thankful for you

**Comment by Iammuhammadowais** [comment]
Why not replying

**Comment by JiahuiYu** [comment]
#298
