### ISSUE TITLE
little question about gated convolution 

### ISSUE THREAD

**Issue by cmyyy** [JiahuiYu/generative_inpainting#301]
![1726](https://user-images.githubusercontent.com/26576058/62006117-f9625200-b16e-11e9-9f1e-cce680be8f2b.png)
![image](https://user-images.githubusercontent.com/26576058/62006620-91fbd080-b175-11e9-9208-ff56d4c9a5ae.png)

Here is the result of my model, which uses gated conv and trained on rectangles，and you can see the texture is strange if zoom in. Have you ever met this situation in deepfill2?

**Comment by JiahuiYu** [comment]
@cmyyy Hi thanks for your interest first.

In my experience, training more iterations will help.

**Comment by cmyyy** [comment]
@JiahuiYu ,thanks for your advice. And i want to make a comparison with deepfill2, do you think whether it's ok that i send you images,mask and test.py , so you only need to  import your model and change the path of checkpoint?

**Comment by JiahuiYu** [comment]
@cmyyy When do you need these results? I think we can release deepfill v2 model by ICCV 2019.

**Comment by cmyyy** [comment]
@JiahuiYu, I'm supposed to finish first draft of my paper before September.  So i probably can't wait for ICCV 2019 .

**Comment by JiahuiYu** [comment]
No problem. You can share a link of your examples (maybe google drive or Dropbox) and I will run for you ASAP. 

Ps: send the link to hi@jhyu.me

**Comment by cmyyy** [comment]
@JiahuiYu ,hello! I have send the link to you 9 days ago , have u received it?

**Comment by JiahuiYu** [comment]
@cmyyy Hi really sorry as I was overwhelmed in recent months. But we will release our pre-trained models of deepfill v2 this week. Please stay tuned!

**Comment by cmyyy** [comment]
@JiahuiYu , looking forward to deepfill v2~

**Comment by nywang2019** [comment]
waiting for Deepfill v2
