### ISSUE TITLE
Single-channel grayscale image restoration into color

### ISSUE THREAD

**Issue by TianLuluC** [JiahuiYu/generative_inpainting#302]
Sorry to bother you, I tried to repair the grayscale image with your network, and my training set is a small amount of grayscale image, but the restored image is colored. I tried changing the number of channels in the image to 1 in inpaint.yml, which would throw an error, and I tried to find the answer in the issue, but I didn't find it. Looking forward to your reply! Thank you

**Comment by JiahuiYu** [comment]
@TianLuluC Hi thanks for your interest first.

This is because our output channels in inpainting model is 3-channel output. Please try to replace with 1-channel in model construction function.

**Comment by LeonCurry** [comment]
Have you repaired the gray image with this network? I want to ask you some question.

**Comment by LeonCurry** [comment]
Have you repaired the gray image with this network? I want to ask you some question. @TianLuluC
