### ISSUE TITLE
Problem about the output

### ISSUE THREAD

**Issue by hyang23333** [JiahuiYu/generative_inpainting#303]
Hi, thank you for the great work! And I am very sorry to bother you. After I modified some layers based on your model and trained it again(Training process seems to be ok, I can print the value of all the variable ). It seems that during test the model I trained doesn't work and just output the input image as follows. Could you please give me some advice? Thank you so much!

![output6](https://user-images.githubusercontent.com/52700830/63223650-b33b6400-c1eb-11e9-971f-bc9edf1f3b5c.png)

**Comment by JiahuiYu** [comment]
@hyang23333 Hi, I would suggest to carefully check what you have changed by `git diff`.
