### ISSUE TITLE
should the concatenate axis be 3 instead?

### ISSUE THREAD

**Issue by fzhang612** [JiahuiYu/generative_inpainting#304]
In the test.py, the following line concatenate image and mask along axis = 2. But I think it should be axis 3, ie the channel dimension. Thanks.

https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/test.py#L40

**Comment by JiahuiYu** [comment]
Here I guess there is no batch dimension. Please have a second check. :-)

**Comment by fzhang612** [comment]
however the batch dimension is added in the previous two lines

https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/test.py#L38
https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/test.py#L39

**Comment by JiahuiYu** [comment]
@fzhang612 Ooops, my bad. I just checked the code. Concat on the second dimension (spatial dimension) is neither an error nor a typo.

Not an error: in model.build_server_graph, we also split on the second dimension. https://github.com/JiahuiYu/generative_inpainting/blob/06cd62cfca8c10c349b451fa33d9cbb786bfaa20/inpaint_model.py#L299

Not a typo: the model.build_server_graph is also used for our online demo, where the transmission API of input data by javascript cannot be 6-channel one. Thus in javascript, we concat the users images and masks on the spatial dimension, and send them to our server.

**Comment by fzhang612** [comment]
Understood now. Thanks for the quick response
