### ISSUE TITLE
How to do this attention visualization?

### ISSUE THREAD

**Issue by laolongboy** [JiahuiYu/generative_inpainting#306]
![微信图片_20190829103012](https://user-images.githubusercontent.com/25175047/63906189-8daf2580-ca49-11e9-902f-759d8d8f2dc4.png)
Shown at the end of the paper.

**Comment by Lxiangyue** [comment]
Hi, lanlongboy~ Looking that you have run this project in GPU sucessfully. Have you ever met some errors like this?
  TypeError: multigpu_graph_def() got an unexpected keyword argument 'data_flist'
Look forward to your reply～

**Comment by zhengbowei** [comment]
Hi, lanlongboy~ Looking that you have run this project in GPU sucessfully. I want to know how you adjusted 178 * 218 image to 256 * 256. The 256 * 256 image I adjusted did not work well.

**Comment by laolongboy** [comment]
> Hi, lanlongboy~ Looking that you have run this project in GPU sucessfully. Have you ever met some errors like this?
> TypeError: multigpu_graph_def() got an unexpected keyword argument 'data_flist'
> Look forward to your reply～



> Hi, lanlongboy~ Looking that you have run this project in GPU sucessfully. I want to know how you adjusted 178 * 218 image to 256 * 256. The 256 * 256 image I adjusted did not work well.

Sorry guys, I just want to draw the same visualization in my algorithm. Actually I didn't run this project.

**Comment by JiahuiYu** [comment]
@laolongboy I have lost the code for this kind of visualization. But the idea is to set a threshold and highlight the pixels being attended with values larger than the threshold.
