### ISSUE TITLE
Deepfillv2 Questions

### ISSUE THREAD

**Issue by muaxiu** [JiahuiYu/generative_inpainting#312]
Awesome work and very thanks @JiahuiYu for each answer, which has greatly helped my work.
However, I still have some questions to ask.
Q1：I see you say, the model that only contains the generator is only 4.1M. Does it contain two stages, stage1 and stage2? Are the two branches of Stage2 (normal series and attetion modules) included?
Q2: Is the end of stage1 also a tanh and clip_by_value end?
Q3: You said,”So the output of our discriminator is (ImageWidth / 32) * (ImageHeight / 32) * 256.” The number of discriminator layers is 6, so the stride of the first or the last layers is 1? 
Q4: Does the discriminator need a clip_by_value to keep the value between -1 and 1？

**Comment by JiahuiYu** [comment]
@muaxiu Hi the code will be released this week. Please stay tuned!

**Comment by muaxiu** [comment]
WOW， I am looking forward to your code！
