### ISSUE TITLE
Hi guys. From where can I download pretrained model?

### ISSUE THREAD

**Issue by HamLaertes** [JiahuiYu/generative_inpainting#313]
I want to use the pretrained model said in ReadMe file. But, Where is the models dir?

**Comment by ThJOD** [comment]
In the ReadMe file in section [pretrained files](https://github.com/JiahuiYu/generative_inpainting#pretrained-models) are hyperlinks for the different models, so you can download them. "Places2" has the weights for the model trained on the places2 dataset and so on.

**Comment by JiahuiYu** [comment]
@ThJOD Thank you again for your help to others!
