### ISSUE TITLE
Data Problem about training CelebA

### ISSUE THREAD

**Issue by ClayZhang0403** [JiahuiYu/generative_inpainting#317]
Thank you for your code, @JiahuiYu 
Here , I will train the CelebA,  i want to know , should i  crop the image to 128x128 or resize the image to 128x128 ？ 

Thanks again

**Comment by JiahuiYu** [comment]
@ClayZhang0403 Hi I crop the image first and then resize. Please checkout neuralgym data processing function for detail.
