### ISSUE TITLE
problem abot test

### ISSUE THREAD

**Issue by ClayZhang0403** [JiahuiYu/generative_inpainting#318]
Hi，Jiahui Yu @JiahuiYu   ， thanks for your code 
i have some problem in the test ，i use this command to test ‘python3.6 test.py --image examples/celeba/celebahr_patches_164036_input.png --mask examples/center_mask_256.png --output examples/output.png --checkpoint_dir model_logs/20191009214622181966_clay-MS-7B47_celeba_NORMAL_wgan_gp_full_model_celeba_256 ’ 

but have some trouble as follow:
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    ng.get_gpus(1)
  File "/usr/local/lib/python3.6/site-packages/neuralgym/utils/gpus.py", line 70, in get_gpus
    ' [(gpu id: num of processes)]: {}'.format(sorted_gpus))
SystemError: No enough gpus for dedicated usage. [(gpu id: num of processes)]: [(0, 7)]

Thanks for your reply

**Comment by JiahuiYu** [comment]
#35
