### ISSUE TITLE
argmax() got an expected keyword argument 'output_type'

### ISSUE THREAD

**Issue by micklexqg** [JiahuiYu/generative_inpainting#326]
i try the test script, but got error:
argmax() got an expected keyword argument 'output_type'

**Comment by JiahuiYu** [comment]
Hi, please use the suggested tensorflow version. Or you can try to modify the code because the API of tensorflow between different versions are not always the same.

**Comment by micklexqg** [comment]
![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)

**Comment by micklexqg** [comment]
tensorflow 1.1.0 + python 3.5 +linux
