### ISSUE TITLE
I can't get preferred result with my sample images/masks.

### ISSUE THREAD

**Issue by albingit70** [JiahuiYu/generative_inpainting#327]
Hi @JiahuiYu 
Thank you for your work.
I am excited with your work and tried to test your model on my machine.
I cloned your repository v2.0.0 and installed required dependencies successfully.
I downloaded pretrained model to model_logs directory and could run some example images in your folder.
But I can't get the result with my custom images, because its generating wrong result.
![output](https://user-images.githubusercontent.com/57055294/67919781-bc2db600-fbdc-11e9-8436-fc582f656a2c.png)
![test](https://user-images.githubusercontent.com/57055294/67919783-bc2db600-fbdc-11e9-8f39-7e7bc36c6950.png)
![test_mask](https://user-images.githubusercontent.com/57055294/67919784-bc2db600-fbdc-11e9-9c72-26dce49074a5.png)

Would you explain me why I get such result? It worked with your sample images, but does not work with my sample images.
Also is there any restriction in input/mask image resolution?
Because I saw your sample images have same resolution.

Looking forward to hearing from you asap.
Thank you

**Comment by Lixueqingqq** [comment]
maybe your mask is wrong, I read your mask found that the alpha channel of your mask is real mask, the R,G,B channel of your mask are all 255. when the code read your mask, it use ' mask = cv2.imread(args.mask)' , if cv2.imread not add cv2.IMREAD_UNCHANGED , the alpha channel is discarded by default. so your mask is changed all 255, It's a completely white picture, and the code would think that the whole picture was inpainted.
fixed your mask , I get the result:
![output](https://user-images.githubusercontent.com/35716636/67946731-ec954480-fc1c-11e9-9d8a-f5d800be50f4.png)
the result is not satisfactory, I think it may have something to do with the way of generating mask

**Comment by albingit70** [comment]
Thank you for quick response, @Lixueqingqq 
I will check mask image and try to fix it as you requested.
About my another question, it does work for all images with different image resolution?
Because I saw your all test images have the resolution of 680 X 512.
I would like to get it working for any resolution of images.
Thank you

**Comment by JiahuiYu** [comment]
@Lixueqingqq Thanks for your help to @albingit70.

Our released model can support any resolution of images. You can have a try without any modification. Moreover I checked the performance of your example and here are my results:

Output:
![_places2_Places365_val_00000005 jpg_output](https://user-images.githubusercontent.com/22609465/67969165-b503a980-fbd6-11e9-9e94-415a948a1795.png)

Input:
![_places2_Places365_val_00000005 jpg_input](https://user-images.githubusercontent.com/22609465/67969178-baf98a80-fbd6-11e9-94a1-5af47e466c46.png)

Mask:
![_places2_Places365_val_00000005 jpg_mask](https://user-images.githubusercontent.com/22609465/67969192-c482f280-fbd6-11e9-8e9d-75a326e722dd.png)

Can you have a try on the mask I draw? In general, please avoid inconsistent color (e.g., a small piece of black region in a uniform background) near the hole boundary.

**Comment by albingit70** [comment]
Hello @JiahuiYu 
Really thank for your help, I tested with your input/mask images and saw same result with yours.
Its really amazing work.

You've told me your released model will does work for any resolution of image, but what is that exactly? Would you give me the link?

Also how you could generate mask images? Would you give me the tool or code to generating them?
Because I generated mask images via Photoshop,but I couldn't road them exactly. its loading white color for transparent.

Looking forward to hearing from you.
Albin

**Comment by albingit70** [comment]
Also I resized your example images to 1000 X 753, then tried to run it on existing code.
But its crashed at the line 60:
```
result = sess.run(output)
```

There are resized images:
![test1](https://user-images.githubusercontent.com/57055294/67971623-0c8e2d80-fc48-11e9-86e2-ce8e4a49e8aa.png)
![test1_mask](https://user-images.githubusercontent.com/57055294/67971625-0d26c400-fc48-11e9-9d33-2ff610d47a6c.png)

Is this the reason I generated input/mask imaged in wrong way?
I just resized it in mac os x.

I would like to know about input/mask images and image resolution issue.
Thank you

**Comment by JiahuiYu** [comment]
@albingit70 Hi I generated the masks with some python utils, which is not trivial to release.

For any resolution image, can you try some size that is divisible by 8? How about 1000 X 752 instead of 753?

The command to test any resolution image should be exactly the same as in our README.

**Comment by Instantnoodles-madman** [comment]
> @albingit70 Hi I generated the masks with some python utils, which is not trivial to release.
> 
> For any resolution image, can you try some size that is divisible by 8? How about 1000 X 752 instead of 753?
> 
> The command to test any resolution image should be exactly the same as in our README.

i am novice. I don't know how to generate mask image ,can you share the tool or code with me,thank you
