### ISSUE TITLE
Question about mask_s = resize_mask_like(mask, x)

### ISSUE THREAD

**Issue by jat923** [JiahuiYu/generative_inpainting#328]
Hi,
I am a bit confused about mask_s = resize_mask_like(mask, x)
Here https://github.com/JiahuiYu/generative_inpainting/issues/251#issuecomment-485825081 you said it defines the background and foreground. 

q1. Why is the mask_s generated after conv6 layer of stage1?

q2. i am also having difficulties in understanding how it is seperating f and b. f is the squared unknown region and b is the known outside region. If that is it then how the mask_s is generated by resizing?

**Comment by JiahuiYu** [comment]
Hi, mask_s is just resized from a previous input mask. It is not learned or generated. The input mask is binary.
