### ISSUE TITLE
Training stuck / progress not shown

### ISSUE THREAD

**Issue by pengyuanchen** [JiahuiYu/generative_inpainting#329]
Hi I am trying to train on Places2 dataset using the latest updated version, but encountered the following problem:
![Screen Shot 2019-11-03 at 12 35 08 AM](https://user-images.githubusercontent.com/43361268/68081869-0c219e00-fdd2-11e9-9d1d-201c3ee24a10.png)
After this line appears, it just gets stuck there for a long time and I have to shut it off.
I read the issue about removing the progress bar, but I do not think this is the issue here because nvidia-smi shows that the GPU is not being utilized.
I checked to make sure that in train.py line 11 I use tf.device('/gpu:0'), and to use Trainer instead of MultiGPUTrainer since I am only using 1 GPU. 
For the yml file, I changed dataset to 'places2', random_crop to True, reduced max_iters and
val_psteps, and kept everything else the same.
My flists are in the correct place.

Really thank you for your contribution, and I would greatly appreciate your insight on what might have caused this problem.

**Comment by JiahuiYu** [comment]
#323

**Comment by LeonCurry** [comment]
> Hi I am trying to train on Places2 dataset using the latest updated version, but encountered the following problem:
> ![Screen Shot 2019-11-03 at 12 35 08 AM](https://user-images.githubusercontent.com/43361268/68081869-0c219e00-fdd2-11e9-9d1d-201c3ee24a10.png)
> After this line appears, it just gets stuck there for a long time and I have to shut it off.
> I read the issue about removing the progress bar, but I do not think this is the issue here because nvidia-smi shows that the GPU is not being utilized.
> I checked to make sure that in train.py line 11 I use tf.device('/gpu:0'), and to use Trainer instead of MultiGPUTrainer since I am only using 1 GPU.
> For the yml file, I changed dataset to 'places2', random_crop to True, reduced max_iters and
> val_psteps, and kept everything else the same.
> My flists are in the correct place.
> 
> Really thank you for your contribution, and I would greatly appreciate your insight on what might have caused this problem.

Have you solved this problem?

**Comment by haythemtellili** [comment]
I have the same problem, Have you solved this please ?
@LeonCurry @pengyuanchen @JiahuiYu

**Comment by WC-0525** [comment]
> Hi I am trying to train on Places2 dataset using the latest updated version, but encountered the following problem:
> ![Screen Shot 2019-11-03 at 12 35 08 AM](https://user-images.githubusercontent.com/43361268/68081869-0c219e00-fdd2-11e9-9d1d-201c3ee24a10.png)
> After this line appears, it just gets stuck there for a long time and I have to shut it off.
> I read the issue about removing the progress bar, but I do not think this is the issue here because nvidia-smi shows that the GPU is not being utilized.
> I checked to make sure that in train.py line 11 I use tf.device('/gpu:0'), and to use Trainer instead of MultiGPUTrainer since I am only using 1 GPU.
> For the yml file, I changed dataset to 'places2', random_crop to True, reduced max_iters and
> val_psteps, and kept everything else the same.
> My flists are in the correct place.
> 
> Really thank you for your contribution, and I would greatly appreciate your insight on what might have caused this problem.

I also encountered this problem. Have you solved it?
