### ISSUE TITLE
IndexError in training

### ISSUE THREAD

**Issue by pengyuanchen** [JiahuiYu/generative_inpainting#331]
I am using the latest version as of 2019.11.3. 23:55 to train on Places2 dataset.
Random crop in the yml is set to True.
This is the error I am receiving, I will greatly appreciate your help!
<img width="1440" alt="Screen Shot 2019-11-03 at 11 58 18 PM" src="https://user-images.githubusercontent.com/43361268/68106338-2329c400-fe96-11e9-9ab5-e82af23e7414.png">

**Comment by pengyuanchen** [comment]
Sorry could it be possible it is a problem in neuralgym/data/data_from_fnames.py?
Not sure why fnamelist[0] would cause an IndexError though.

**Comment by JiahuiYu** [comment]
@pengyuanchen Hi, what's the format of your filelist? I guess the devil is in your filelist. Please take a look at previous issues on filelist #20 #32 etc.

**Comment by pengyuanchen** [comment]
@JiahuiYu 
Thank you for your reply. I have read through the related issues, thanks for linking them for me! But I am still having this problem.

My flist is as following:

Training:
<img width="407" alt="Screen Shot 2019-11-04 at 9 34 39 PM" src="https://user-images.githubusercontent.com/43361268/68181238-7ad63700-ff4b-11e9-997e-a4c228085149.png">

Validation:
<img width="443" alt="Screen Shot 2019-11-04 at 9 35 01 PM" src="https://user-images.githubusercontent.com/43361268/68181254-832e7200-ff4b-11e9-9573-015c74a77d89.png">

I am just running a small sample training, hence I am using a very small subset of places2. Is it possible that it is because there are too few images? Or could any improper setting in my yml is causing the problem?

Here is my yml setting:
<img width="565" alt="Screen Shot 2019-11-04 at 9 48 22 PM" src="https://user-images.githubusercontent.com/43361268/68181663-0a301a00-ff4d-11e9-9eb0-79f0063947e1.png">

Really wanna say a big thank you for this amazing work and your help!

**Comment by pengyuanchen** [comment]
Sorry I realized it is because my static_view_size is larger than my validation size. This is solved.

**Comment by JiahuiYu** [comment]
@pengyuanchen Excellent!
