### ISSUE TITLE
CelebA dataset result is not good.

### ISSUE THREAD

**Issue by Adhiyaman-Manickam** [JiahuiYu/generative_inpainting#334]
Hi, 
I am trying to repeat your code that is contextual attention. but i got the following error.
Kindly let know, where i made a mistake

input image
![input4](https://user-images.githubusercontent.com/57310377/68187251-2da4a480-ffe1-11e9-8a8e-a92fb06051ea.png)

mask image

![input5](https://user-images.githubusercontent.com/57310377/68187279-3e551a80-ffe1-11e9-997e-b23e28808690.png)

output image
![output3](https://user-images.githubusercontent.com/57310377/68187297-4b720980-ffe1-11e9-858c-3a6874540fde.png)

**Comment by JiahuiYu** [comment]
@Adhiyaman-Manickam Our pre-trained model for DeepFill v2 is based on CelebA-HQ, instead of CelebA. For CelebA, please try to train a model on this specific dataset. Or you can use our DeepFill v1, which has CelebA pre-trained model released.

**Comment by Adhiyaman-Manickam** [comment]
Thanks for your kind reply. I have trained the model compeletly with CelebA Dataset only. Eventhough, the result is horrible. I am not using any pre-trained model. Kindly let me know, why it has happened.
