### ISSUE TITLE
how to set up train_spe and max_iters.

### ISSUE THREAD

**Issue by laolongboy** [JiahuiYu/generative_inpainting#335]
Sorry to bother again, I want to confirm how to set up train_spe and max_iters. 
Now I have a dataset with 60,000 images. I want to run 40 epoches with batchsize of 16.
Conventionally, that means 1 epoch = 60,000 / 16 = 3750 iterations.
So I set train_spe=3750, max_iters=3750*40
But according to the training speed (0.43batches/sec) , finish one epoch will need 7 hours.  
Comparing with other model training on Pytorch, that's too long.

**Comment by JiahuiYu** [comment]
@laolongboy Hi, setting train_spe and max_iters is purely for monitoring purpose, and should not affect the overall training procedure and performance. If one epoch takes 7 hours, you can decrease your train_spe. For related information, please take a look at: https://github.com/JiahuiYu/neuralgym/issues/3
