### ISSUE TITLE
InvalidArgumentError during training on my own dataset

### ISSUE THREAD

**Issue by pengyuanchen** [JiahuiYu/generative_inpainting#337]
Thank you for your great work! Here is a problem I met when I was training on my own dataset consisting of images of width 256 and height 128. I cannot fully understand this error, but I found an issue about the same problem (#247 ). Unfortunately the OP closed it without explaining how he solved it.

There was no error when I was training on square images from Places2, so I suspect it might be related to the size of images or yml settings? I would greatly appreciate it if you could help me!

<img width="1440" alt="Screen Shot 2019-11-05 at 10 59 10 PM" src="https://user-images.githubusercontent.com/43361268/68275290-120cbe80-0020-11ea-9c0b-b130812baaab.png">

**Comment by JiahuiYu** [comment]
@pengyuanchen Hi, from the error you showed here, it seems like is related to these hyper-parameters for randomly generating masks with random shapes.

https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint.yml#L55-L61

Please double check.
