### ISSUE TITLE
input, mask and output images

### ISSUE THREAD

**Issue by Adhiyaman-Manickam** [JiahuiYu/generative_inpainting#338]
Hi,
can you explain and give me an example for input and mask images to the test.py.
It is little bit confusing with research paper and github code.
Thanks in advance. kindly make it clear.

**Comment by JiahuiYu** [comment]
@Adhiyaman-Manickam Hi thanks for your interest!

Please checkout the instructions on README.

https://github.com/JiahuiYu/generative_inpainting#pretrained-models

**Comment by Adhiyaman-Manickam** [comment]
Thanks for your prompt reply. I have read that, but it consists some confusion for me. You have given an input and mask images are two types, they are

**Type:1**
Input Image
![input4](https://user-images.githubusercontent.com/57310377/68354171-9194ad80-0146-11ea-9e75-e467c618c08f.png)
Mask Image
![mask4](https://user-images.githubusercontent.com/57310377/68354181-9d806f80-0146-11ea-9f84-859300f144be.png)

**Type:2**
Input Image
![mask4](https://user-images.githubusercontent.com/57310377/68354206-b0933f80-0146-11ea-87ae-bf451df9d82f.png)
Mask Image
![mask5](https://user-images.githubusercontent.com/57310377/68354216-b8eb7a80-0146-11ea-8725-58eceac4009f.png)

**But I am not understanding that which is suitable for given code in GitHub.
Kindly let me know, where I made a mistake**

**Comment by JiahuiYu** [comment]
https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint_model.py#L151

Each one is fine, as anyway it will be converted into Type 2. Please read the code listed.

**Comment by Adhiyaman-Manickam** [comment]
Thanks @JiahuiYu .
