### ISSUE TITLE
Download error with celeba snap-0.data - errors out after 30MB

### ISSUE THREAD

**Issue by danny-wu** [JiahuiYu/generative_inpainting#340]
I have tried to download "snap-0.data-00000-of-00001" from two different PCs, four different browsers, on two different network connections, both signed in and out of my Google Account. Unfortunately, the download always fail at around the 30MB mark; on *all* of my PCs, browsers and network environments. 

Could you please try downloading this file? I think it is possible that it is corrupt in Google Drive. I have never seen a download fail halfway before from Google Drive.

Thank you!

**Comment by JiahuiYu** [comment]
@danny-wu Hi thanks for your interest in our work. I just downloaded the `release_places2_256_deepfill_v2/snap-0.data-00000-of-00001` and everything is normal. Which file are you trying to download in your case? I can help to double check.
