### ISSUE TITLE
Results seem to have more contextual attention than understanding edges

### ISSUE THREAD

**Issue by jat923** [JiahuiYu/generative_inpainting#341]
Hi,
After training on my dataset, the filled result seem to have more impact from contextual attention rather than the shapes. The model is not learning the feature and shape.
![landsat1429](https://user-images.githubusercontent.com/25399611/68328303-a284e680-0094-11ea-87ba-9b33d24f5c98.jpg)
![output1](https://user-images.githubusercontent.com/25399611/68328313-a6b10400-0094-11ea-9800-587cd5139f5c.png)

 Is there a way to minimize the imapct in the contextual layer?

**Comment by JiahuiYu** [comment]
Hi, the results you showed here is normal at the early training stage of a model. It does not relate to contextual attention. I would suggest you to debug on other aspects, for example, training with more iterations, making sure your dataset is relatively large, etc.

If you want to minimize the impact from contextual attention, you can simply remove that layer in the model file.

**Comment by jat923** [comment]
Thanks for the quick reply!
Well i trained for 20000 epochs with batch size 2 and 10 iter per epoch on around 50000 data.  Do you think its good enough and still getting such result means that somethings wrong?(may be with data)

**Comment by JiahuiYu** [comment]
Your batch size is too small. That's a big issue. Normally I use at least 16, otherwise the training will be very unstable and the results will not be good.

Please have a read of papers in GAN literature, e.g., BigGAN.
