### ISSUE TITLE
Transfer learning

### ISSUE THREAD

**Issue by GeorgiiVdovychenko** [JiahuiYu/generative_inpainting#342]
Hello.
JiahuiYu, first of all, thanks a lot for your brilliant work!
I'm new in GAN training and would like to ask you a few questions about training. 
Currently, I'm working on inpainting of texture of stone tiles and the goal is to remove cracks. To test the performance I've used the pre-trained places-2 models it gave me a relatively good result, but it still would be nice to improve it.
Obviously the domains of the places-2 and my dataset are different. 
How do you think is it worth to try to continue the training of the places-2 model on my data?

**Comment by JiahuiYu** [comment]
@GeorgiiVdovychenko Hi thanks for your interest. Yes it is worth trying. If your texture dataset is large, you can also try to train directly on your dataset simultaneously and compare the performance.
