### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by mxkai** [JiahuiYu/generative_inpainting#348]
Hi,can you tell me how to generate multiple patches on an image and a mask,I try to generate patches through inpaint.py, but only one patch can be generated on a mask.thanks

**Comment by JiahuiYu** [comment]
Hi I guess you can apply the sampling function multiple times.

**Comment by mxkai** [comment]
Sorry，I also have a question about how many patches to set in one image of training

**Comment by mxkai** [comment]
Sorry，I also have a question about how many patches are appropriate in one image of training
