### ISSUE TITLE
GPU speed - Reg

### ISSUE THREAD

**Issue by Adhiyaman-Manickam** [JiahuiYu/generative_inpainting#349]
Hi,
I am trying to use multi gpu for training. I have made significant changes on that based on the previous issues and as per your directions. I used the gpu's [0,2,7]

**I am working on python3**

**Note:
I have done the issues : #181** 

By checking nvidia-smi. It shows GPU memory usage in three gpu's (id: 0,2,7) but gpu utilization is single gpu (id :0).  Kindly let me know, where I made a mistake.

![WeChat Image_20191111151857](https://user-images.githubusercontent.com/57310377/68568845-a4391a80-0497-11ea-9fc8-2f8e13dad618.png)

**Kindly find the below batches speed:**

![WeChat Image_20191111152030](https://user-images.githubusercontent.com/57310377/68568984-f712d200-0497-11ea-8df1-759cbbfe8d19.png)

**Kinldy guide me, how to solve this or is it correct?**

**Note :  I have done the issues : #14** 

**I got the following error:**
![WeChat Image_20191111175139](https://user-images.githubusercontent.com/57310377/68577955-0ef45100-04ac-11ea-9b83-0b92b516797e.png)

Kinldy guide me about the difference. Why I unable to use multigputrainer.
Thanks in advance

**Comment by JiahuiYu** [comment]
@Adhiyaman-Manickam 

https://github.com/JiahuiYu/generative_inpainting/blob/master/train.py#L80-L92

Are you passing `num_gpus=3` to the API?

The current DeepFill v2 code (master branch) does support multi-GPU. You can compare and see what is missing.

**Comment by Adhiyaman-Manickam** [comment]
Thanks @JiahuiYu
