### ISSUE TITLE
flist format for batch_test.py

### ISSUE THREAD

**Issue by pengyuanchen** [JiahuiYu/generative_inpainting#352]
Hi Jiahui, thanks so much for your great work and patiently answering my previous questions. 

May I check in what format the flist should be in? Thanks in advance!

![Screen Shot 2019-11-12 at 11 14 23 PM](https://user-images.githubusercontent.com/43361268/68741431-755b9b00-05a2-11ea-84b7-0b27b88c8f59.png)

**Comment by pengyuanchen** [comment]
Would really appreciate it if there is an example/screenshot of some sort. Otherwise I am not sure how to arrange the input, mask and output in my flist. Thanks a lot!

**Comment by pengyuanchen** [comment]
Reading the code, my guess is that each line contains input, mask, output in this order, separated by a space?

**Comment by JiahuiYu** [comment]
Separated by a space should work. https://github.com/JiahuiYu/generative_inpainting/blob/master/batch_test.py#L63

**Comment by pengyuanchen** [comment]
Yup it worked. Thank you

**Comment by yangyang32111** [comment]
Sorry to bother you.Can you give me some guidence about how create a flist file in batch_test.py? Thank you very much!
