### ISSUE TITLE
Is there a missing argument in batch_test.py?

### ISSUE THREAD

**Issue by pengyuanchen** [JiahuiYu/generative_inpainting#353]
It seems there should be 2 arguments.

![Screen Shot 2019-11-13 at 9 03 29 PM](https://user-images.githubusercontent.com/43361268/68828109-4eac6b80-0659-11ea-85d7-dcac7f13434b.png)

**Comment by JiahuiYu** [comment]
@pengyuanchen Thanks for addressing the issue. #354

**Comment by pengyuanchen** [comment]
My pleasure. Thanks for the great work
