### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by godchengzhihang** [JiahuiYu/generative_inpainting#355]
@Hello, on deepfillv1 I replaced wgan-gp with relative GAN. During the training, I found that the blank part of the picture repaired by the rough network appeared to be a color. I thought for a long time, I don't know where the problem is, I hope you can help me!
![4~NIDFZ){RXC1IN3O$VVA0D](https://user-images.githubusercontent.com/55656735/68991182-e2b74680-0896-11ea-8f26-afa7f8c9ffd8.png)
![14 0`NGRNM97WN 9}P 5O(B](https://user-images.githubusercontent.com/55656735/68991183-e2b74680-0896-11ea-83d0-818aa01d5b53.png)

**Comment by JiahuiYu** [comment]
The training is totally failed. Please use our default WGAN-GP.
