### ISSUE TITLE
Multi- GPU Speed (contd with issue #350) - Reg

### ISSUE THREAD

**Issue by Adhiyaman-Manickam** [JiahuiYu/generative_inpainting#357]
Hi @JiahuiYu 
Sorry for the disturbance.

Previously, I have asked the questions about multi gpu for training. You have suggested that to use deepfill v2 for multi-gpu training. 
I have done that work based on your suggestion and it is working fine now.
But the training speed is lower than single gpu. Then you have informed me that gpu speed is multiply by batch speed. (For example :  0.39 * number of GPUs batch / sec)
I have used 3 gpu but speed is not performed the above manner.
Kindly see the below picture for reference
Hence, kindly let me know, where i made a mistake and where should i change the code.

Thanks in advance

![Untitled](https://user-images.githubusercontent.com/57310377/69406378-f6522980-0d3c-11ea-9ae2-534e5718a0e6.png)

**Comment by JiahuiYu** [comment]
@Adhiyaman-Manickam The speed on your **screen** should be 0.39 batch / sec. The epoch is defined by iteration, not by number of examples. So you should be good.
