### ISSUE TITLE
I can not see any progress on training.

### ISSUE THREAD

**Issue by goldservice2017** [JiahuiYu/generative_inpainting#358]
Hello @JiahuiYu 
When I tried to train model as your guide, I can't see it work.
I already posted [issue detail](https://github.com/JiahuiYu/generative_inpainting/issues/52#issuecomment-557593613) about this issue to #52 , but I couldn't get answer.
```
Hello @JiahuiYu and @luckybulldozer
I faced same error when I try to run python train.py
I downloaded place2 dataset and added some new images.
After this, I generated train.flist and val.flist file to use for training.
When I am running python train.py, I got same error like below:

Also there is my yaml file:

Also would you let me know about using multiple gpus for training?
I am not sure how to set num_gpus_per_job, num_cpus_per_job, num_hosts_per_job, memory_per_job.

Looking forward to hearing from you.
```

Actually I've waited for few hours after I faced this issue. Also it never using GPU memory.
Not sure what I need to do.
Please help me.

**Comment by JiahuiYu** [comment]
Hi the progress bar has been removed so you cannot see any progress. #323. To see if the training is happening, you can view tensorboard, or just confirm the GPU utilization   

The flags like num_gpus_per_job, num_cpus_per_job, num_hosts_per_job, memory_per_job is useless for your local machine. It is useful for cluster scheduling and should be ignored in your situation. 

Leave message here if you have more questions. I am happy to help. :)

**Comment by goldservice2017** [comment]
@JiahuiYu , thank you for your reply.
But I have the problem yet.
1). Training time
I have tried to use your pre-trained checkpoint as you wrote in the README.
`model_restore: '20180115220926508503_places2_model'`
I have enough GPU memory(4 nvidia tesla v100-sxm2), but its running very slowly.
![TinyTake23-11-2019-03-17-41_637100470639437486](https://user-images.githubusercontent.com/25535586/69454022-3f9d7b80-0d33-11ea-8083-5f4cbd594f35.png)
2). inpaint.yml
I am attaching inpaint.yml file for you to check. Please let me know any guide to run this successfully.
[inpaint.yml.txt](https://github.com/JiahuiYu/generative_inpainting/files/3881083/inpaint.yml.txt)


I am sorry for bordering you, but I would like to see it does work asap.
For now, I think that there is mistake, but not sure what is it.

Thank you

**Comment by JiahuiYu** [comment]
It seems like you training is on CPU only. The GPU utilization is zeros. Please make sure:

1. You have set CUDA VISIABLE DEVICES flag
2. Your tensorflow is of gpu version

**Comment by goldservice2017** [comment]
Hello @JiahuiYu 
Thank you for your quick response and I am really appreciate your advise.
1). I don't have enough knowledge about `CUDA VISIABLE DEVICES flag`, how I can set that on Ubuntu 16.04?
2). I have installed tensorflow-gpu(1.7.0) and comfortable Cuda/CuDNN(Cuda9.0.176, CuDNN 7005).

Thank you

**Comment by JiahuiYu** [comment]
@goldservice2017 You can search online: google search with keywords `CUDA VISIABLE DEVICES`. :)

Here is the link I found: https://devblogs.nvidia.com/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/

**Comment by goldservice2017** [comment]
Hello, @JiahuiYu 
Thank you for your advise again. I could fix `CUDA VISIABLE DEVICES flag` issue, so I can see model training is on gpu. 
But I have the problem while saving model in .pb(frozen graph) like #198.
I changed the [code](https://github.com/JiahuiYu/generative_inpainting/issues/198#issuecomment-482053928) as @muyue1238  mentioned, but I received an error related to `output_node_names`.

There is my model saving code:
![TinyTake23-11-2019-09-20-39_637101120441729808](https://user-images.githubusercontent.com/25535586/69479476-88a10e80-0dcb-11ea-866b-66d29a611fd0.png)

Also there is error message about `output_node_names`:
![TinyTake23-11-2019-09-17-08_637101118307222903](https://user-images.githubusercontent.com/25535586/69479481-96569400-0dcb-11ea-81ee-266b5a30401a.png)

I am really happy if you give me solution to fix this problem.
Thank you

**Comment by JiahuiYu** [comment]
I don’t have related experience on that. I’d suggest search and ask for help in the tensorflow community.

**Comment by goldservice2017** [comment]
Hello @JiahuiYu 
Thank you for your advice.
I collected **op** names as @huangqianfirst wrote [here](https://github.com/JiahuiYu/generative_inpainting/issues/246#issuecomment-486554630).

I am saving checkpoints and frozen pb file both, my exact code is there for it:
![TinyTake25-11-2019-11-53-09_637102507964021926](https://user-images.githubusercontent.com/25535586/69511205-51d31180-0f0d-11ea-8e98-d80eae4ca0c2.png)

But I have 2 serious problems more here:
1). When I trying to save checkpoints, I got tensorflow error. But I am not sure how you can fix it.
![TinyTake25-11-2019-11-53-09_637102507964021926](https://user-images.githubusercontent.com/25535586/69511324-aa0a1380-0f0d-11ea-8eda-86caa9e21d23.png)

![TinyTake25-11-2019-12-05-21_637102515233854277](https://user-images.githubusercontent.com/25535586/69511647-028de080-0f0f-11ea-8fa8-e16f87bf45f0.png)

I am following your default training steps, so I would like to know what is the solution for it.

2). When I try to run `test.py` with my checkpoints by ``` python test.py --image examples/input.png --mask examples/mask.png --output examples/output.png --checkpoint model_logs/your_model_dir ```, [its](https://github.com/JiahuiYu/generative_inpainting/blob/cfc1d41a882dbbe7c2c35446c8e49b81b7ed51ff/test.py#L58-L59) not loading few layers with "Read fewer bytes than requested.". 
I catched all vnames and error for this.
![TinyTake25-11-2019-12-03-06_637102513885831984](https://user-images.githubusercontent.com/25535586/69511576-a9be4800-0f0e-11ea-8a50-0a98179bb8dd.png)

Please help me how to use your trained model in test.py.
Thank you

**Comment by LeonCurry** [comment]
> Hello @JiahuiYu
> When I tried to train model as your guide, I can't see it work.
> I already posted [issue detail](https://github.com/JiahuiYu/generative_inpainting/issues/52#issuecomment-557593613) about this issue to #52 , but I couldn't get answer.
> 
> ```
> Hello @JiahuiYu and @luckybulldozer
> I faced same error when I try to run python train.py
> I downloaded place2 dataset and added some new images.
> After this, I generated train.flist and val.flist file to use for training.
> When I am running python train.py, I got same error like below:
> 
> Also there is my yaml file:
> 
> Also would you let me know about using multiple gpus for training?
> I am not sure how to set num_gpus_per_job, num_cpus_per_job, num_hosts_per_job, memory_per_job.
> 
> Looking forward to hearing from you.
> ```
> 
> Actually I've waited for few hours after I faced this issue. Also it never using GPU memory.
> Not sure what I need to do.
> Please help me.

I'm sorry to disturb you, did you solve this problem?
