### ISSUE TITLE
my training does converge and the result is bad

### ISSUE THREAD

**Issue by nywang2019** [JiahuiYu/generative_inpainting#360]
I used pretrained place2 weights to train my own dataset. no training parameter was modified, just used the one the author provided. 
there are about 10k images in my trainset with size 512X512. i trained nearly 200 epochs. the result is bad. it seems the all losses do not converge.  what's wrong? what should i do next?
![image](https://user-images.githubusercontent.com/55544699/69498179-d04e9580-0eb2-11ea-92a8-3b30ebd4b010.png)
![image](https://user-images.githubusercontent.com/55544699/69498186-e2c8cf00-0eb2-11ea-981f-47fa0c9dbf67.png)
![image](https://user-images.githubusercontent.com/55544699/69498208-fd02ad00-0eb2-11ea-91b7-e1ed214093b3.png)

**Comment by JiahuiYu** [comment]
I'd suggest you use a larger batch size ( and smaller image resolution is your GPUs are limited). Meanwhile please search over the closed issues - there are many other suggestions that may help you debug.

Also, try not to use places2 pre-trained model and instead train from scratch. From the curves above, the training is failed.
