### ISSUE TITLE
About visualizing the learned gating values

### ISSUE THREAD

**Issue by seeclearlyfirst** [JiahuiYu/generative_inpainting#363]
Hello, @JiahuiYu 

- Did you visualize the learned gating maps of different size just by resizing them to the size of the original image with interpolation method?

- It seems that different channels of the output feature map of the gated convolution layer focus on different parts (background, mask, and sketch) in the coarse network, is it exactly the same in the refinement network? Will the highlighted mask regions in the gating map shrink in the deeper layer of the refinement network?

Thank you very much :)

**Comment by JiahuiYu** [comment]
@WanderingMeteor The answer is Yes to both of your questions. The gating map will not shrink in refinement network.

**Comment by seeclearlyfirst** [comment]
Got it. Thanks!!
