### ISSUE TITLE
Inpainting results - Reg

### ISSUE THREAD

**Issue by Adhiyaman-Manickam** [JiahuiYu/generative_inpainting#364]
Dear @JiahuiYu 

Thanks for your continuous support.

I have seen many issues related to inpainting result is not good. You have answered those issues.  I have followed all those answers and tried with CelebA HQ dataset. 
However, I also got bad results.

I have done the mask as small a region for better results
![mask6](https://user-images.githubusercontent.com/57310377/69686647-59580d80-10fb-11ea-8d1b-0d161dc9c45c.jpg)

only 10 epoch with results. (seems to be somewhat good)

![output12](https://user-images.githubusercontent.com/57310377/69686532-05e5bf80-10fb-11ea-8bff-4d1c4dd7a3ec.jpg)

with 35 epoch results 
![output6](https://user-images.githubusercontent.com/57310377/69686579-26ae1500-10fb-11ea-92fe-5d72db567c8a.jpg)

**But by increasing an epoch, the result is deteriorating.**
**Till now i unable to produce good results after 100 epoch with CelebA HQ dataset.**

**Kinldy help me, where i have made a mistake and how to produce good results.**

Many thanks.

**Comment by JiahuiYu** [comment]
Hi I don’t know where you may have a problem yet. In your example, only a very small region is masked. Why the results are so different outside the region of masks?

**Comment by Adhiyaman-Manickam** [comment]
Thanks.

Yes. Still, i dont know too. Is there any problem with model collapse and not converge. So far, I unable to produce the same results as reported in the paper.

**Comment by JiahuiYu** [comment]
Which batch size are you using? Did you change the hyper parameters or other settings as in our released code?

**Comment by Adhiyaman-Manickam** [comment]
BATCH_SIZE: 16. I have changed such as RANDOM_CROP, MAX_ITERS, GPU_ID and NUM_GPUS. Otherwise, I have followed the same released code.

**Comment by JiahuiYu** [comment]
Oh I think you did not correctly use the test code. Please first of all try to run the results with **our** released model and test code. Then use **your** trained models to see if you can reproduce our results.

**Comment by Adhiyaman-Manickam** [comment]
Thanks @JiahuiYu
