### ISSUE TITLE
Share logdir to view  in tensor board

### ISSUE THREAD

**Issue by sandhyalaxmiK** [JiahuiYu/generative_inpainting#366]
Hi,
Thanks for sharing the code. Currently working on removing tattoo from human image. I am collecting raw image with tattoo, mask image as input (created using photo-shop) and an image by removing tattoo as an output. I need high quality images of 2k resolution. Can you help me of how to go further to continue my process??
Can you share pre-trained logdir (model directory) to view  the model in in tensor board which makes me to understand in an easy manner.

Thanks in advance.

Regards,
SandhyaLaxmi

**Comment by JiahuiYu** [comment]
@sandhyalaxmiK Hi, unfortunately I don't have a logdir in any of the server I am able to access now. But as we have released all the code essentially, you can run our code with the face dataset for a quick overview of tensorboard info.

**Comment by sandhyalaxmiK** [comment]
Hi. Thanks for your reply. How to train with high resolution images to get good quality.  Can you tell the process.
Thanks
Regards,
SandhyaLaxmi Kanna

**Comment by JiahuiYu** [comment]
@sandhyalaxmiK Hi, please follow our README instructions.

**Comment by sandhyalaxmiK** [comment]
Thank you.

**Comment by sandhyalaxmiK** [comment]
1)Taking more time and system is hanging to load images through neuralgym(ng.data.DataFromFNames) for the images of high resultion(1024x1024). Any alternative way is there?

**Comment by JiahuiYu** [comment]
@sandhyalaxmiK In this case, I don't think there could be much faster way to load images, unless you optimize code with programming languages except python (e.g., C++).

**Comment by sandhyalaxmiK** [comment]
can I load images directly without using ng.data.DataFromFnames like by using tfrecords or cv2.imread(), etc...

**Comment by JiahuiYu** [comment]
Why not? You can always definitely have a try. Please hack if you want. :)
