### ISSUE TITLE
1)Taking more time and system is hanging to load images through neuralgym(ng.data.DataFromFNames) for the images of high resultion(1024x1024). Any alternative way is there?

### ISSUE THREAD

**Issue by sandhyalaxmiK** [JiahuiYu/generative_inpainting#370]
1)Taking more time and system is hanging to load images through neuralgym(ng.data.DataFromFNames) for the images of high resultion(1024x1024). Any alternative way is there?

_Originally posted by @sandhyalaxmiK in https://github.com/JiahuiYu/generative_inpainting/issues/366#issuecomment-561605361_

**Comment by JiahuiYu** [comment]
#366
