### ISSUE TITLE
Some problem with the checkpoint

### ISSUE THREAD

**Issue by chensenmao** [JiahuiYu/generative_inpainting#374]
I train the model and break it. And then I want to resume the model,but it did not load the checkpoint. 
Could you please tell me how to resume the model.
I put the checkpoint in the ./logs, and the model_restore is also ./logs

**Comment by JiahuiYu** [comment]
#174 

https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint.yml#L11
