### ISSUE TITLE
Testing image results - Reg

### ISSUE THREAD

**Issue by Adhiyaman-Manickam** [JiahuiYu/generative_inpainting#378]
@JiahuiYu 

Thanks for you continuous support.

**The results are good in Tensorboard view during the training  but while testing it was bad.** 
Could you tell me, what is the reason for this.
I have tried many ways, but i could not find it.

Tensorboard view result during training process

![WeChat Image_20191202131622](https://user-images.githubusercontent.com/57310377/70957629-b1a67d80-20b1-11ea-8c1b-ff9db615fa75.png)

Testing result
![mask8](https://user-images.githubusercontent.com/57310377/70957687-def32b80-20b1-11ea-8534-07dad131c185.jpg)
![output82](https://user-images.githubusercontent.com/57310377/70957693-e4e90c80-20b1-11ea-8003-203dca391e41.jpg)

Thanks.

**Comment by JiahuiYu** [comment]
#364 

1. Why the results are different outside the region of masks? According to our code, it is NOT possible. https://github.com/JiahuiYu/generative_inpainting/blob/cfc1d41a882dbbe7c2c35446c8e49b81b7ed51ff/inpaint_model.py#L296
2. Please first of all try to run the results with our released model and test code.

ps: It may not be necessary to repeat your issue. Just leave message at the last issue.

**Comment by Adhiyaman-Manickam** [comment]
Hi @JiahuiYu 
Thanks for your continuous support. Now, I can reproduced all the results as you reported in the paper and understood the code clearly. 
Thanks.
