### ISSUE TITLE
contextual attention Implementation problem?

### ISSUE THREAD

**Issue by daisy-disc** [JiahuiYu/generative_inpainting#379]
Does the contextual attention layer default to using the same mask for all images in a batch?
` m = tf.extract_image_patches(
        mask, [1,ksize,ksize,1], [1,stride,stride,1], [1,1,1,1], padding='SAME')`
`m = tf.reshape(m, [1, -1, ksize, ksize, 1])`
`m = tf.transpose(m, [0, 2, 3, 4, 1])  # transpose to b*k*k*c*hw`
`m = m[0]`

**Comment by JiahuiYu** [comment]
#85
