### ISSUE TITLE
Tested on my own dataset.

### ISSUE THREAD

**Issue by Summer-lcz** [JiahuiYu/generative_inpainting#380]
May I add you on WeChat, I want to ask some questions

**Comment by JiahuiYu** [comment]
Please post your questions here and I will try my best to help. :)

**Comment by Summer-lcz** [comment]
Test on the TUM-rgbd dataset, where I generated a mask through Mask-RCNN. I want to complete the part of the picture covered by the mask. But I don't know how to use and set up your network. Thank you.

发件人：JiahuiYu <notifications@github.com>
发送日期：2019-12-24 12:52:54
收件人：JiahuiYu/generative_inpainting <generative_inpainting@noreply.github.com>
抄送人：Summer-lcz <liuchuanzheng@mail.sdu.edu.cn>,Author <author@noreply.github.com>
主题：Re: [JiahuiYu/generative_inpainting] Tested on my own dataset. (#380)
Please post your questions here and I will try my best to help. :)

**Comment by JiahuiYu** [comment]
Please follow README instructions.
