### ISSUE TITLE
according to to the loss, am I on the right way?

### ISSUE THREAD

**Issue by Zhong-gy** [JiahuiYu/generative_inpainting#383]
Hi, JiahuiYu:
Sorry to bother you. I am trying to using your network to inpaint tiny images, the losses is:
![Screenshot from 2019-12-26 13-53-46](https://user-images.githubusercontent.com/52098368/71460707-0059c300-27e8-11ea-94e6-d8e584e27f9a.png)
![Screenshot from 2019-12-26 13-54-05](https://user-images.githubusercontent.com/52098368/71460715-0a7bc180-27e8-11ea-8261-b3f14211bb0f.png)
The gan loss really confuses me. And the results are not very satisfying(The size of image is 64x64) :
![Screenshot from 2019-12-26 15-55-28](https://user-images.githubusercontent.com/52098368/71467254-35244500-27fd-11ea-88da-30f6a6f205ac.png)
![Screenshot from 2019-12-26 14-03-12](https://user-images.githubusercontent.com/52098368/71467259-39e8f900-27fd-11ea-9b13-ee8e14f1739a.png)
What's more, I found that in some case(Red rectangle border in result1.), the pixels near the reference pixels are fuzzy, while the piexls far away from the reference pixel (bottom right corner) are obvious dots. Could this be caused by Spatially_discounted_reconstruction_loss? In my case ,I set 0.95 to SPATIAL_DISCOUNTING_GAMMA.
And I also found that in very few case, these obvious dots appear in some area that should be supposed to be smooth! As shown:
![TIM图片20191226212457](https://user-images.githubusercontent.com/52098368/71477914-c01a3500-2827-11ea-8b9a-c0a3c6922e32.png)

I really want to know， according to to the loss, am I on the right way? If not, do you have any suggestions for me to solve the current dilemma?
Thank you so much!

**Comment by JiahuiYu** [comment]
You are on the right way.
