### ISSUE TITLE
places dataset

### ISSUE THREAD

**Issue by godchengzhihang** [JiahuiYu/generative_inpainting#385]
@JiahuiYu Hello, is the total number of high-resolution images of the Place2 dataset 1.8 million？

**Comment by tks-reply** [comment]
Yes!

**Comment by JiahuiYu** [comment]
@tks-reply Thanks!

**Comment by godchengzhihang** [comment]
thanks!Are the training and validation sets of the training model the training and validation sets of the original data set? That is 1.8 million training sets and 36500 validation sets? @JiahuiYu
