### ISSUE TITLE
user guide

### ISSUE THREAD

**Issue by tks-reply** [JiahuiYu/generative_inpainting#386]
What a wonderful work!
I am sorry to bother you,but I have some questions about user guide and model.
Q1:Could you share a model based on places2 (256 * 256) dataset and random mask?It is too long to retrain a model.
Q2:I have a question about user guide.I have searched  #375 #369,but I am still confused about it.I have corresponding places2 edge dataset.What should I do next?Set guieded to True  in inpaint.yml and rename the edge dataset as (image.jpg, guided_image.jpg)?
I would very appreciate if you could help me.
Thank you very much!

**Comment by JiahuiYu** [comment]
@tks-reply 

Q1: To my best understanding, the model of places2 is already shared. The link is at: https://github.com/JiahuiYu/generative_inpainting/tree/cfc1d41a882dbbe7c2c35446c8e49b81b7ed51ff#pretrained-models

Q2: Yes. Name is as `image.jpg, guided_image.jpg` for each line. Please also checkout our data loader for more detailed usage. https://neuralgym.readthedocs.io/data.html

**Comment by tks-reply** [comment]
Oh,I got it.
Thank you very much!

**Comment by tks-reply** [comment]
@JiahuiYu   
I have another question about the coarse result x1.
Q3: If I want to see the coarse result,just set all batch_predicted = x2 to batch_predicted = x1?I wonder if I am right.
I would very appreciate if you could help me,thank you!

**Comment by JiahuiYu** [comment]
Yes.

**Comment by tks-reply** [comment]
@JiahuiYu 
I have another question about the inpainting results which only use fine network.
Q4:I have modified the  python file but failed in test.

Here are some inpainting results from tensorboard:
![649485290d436341e8580a0a2c7441c](https://user-images.githubusercontent.com/59277770/71803905-f748db80-309c-11ea-85aa-8c65a8cd4a77.png)

Here are the loss viewed in tensorboard：
![a6128d19adecd6b93d9ec13752c7e62](https://user-images.githubusercontent.com/59277770/71804317-054b2c00-309e-11ea-884e-762c0f3dbc91.png)
![e0d3cb50a763d3dcfb6ae5afeddb432](https://user-images.githubusercontent.com/59277770/71804318-054b2c00-309e-11ea-8e2f-60cf77bcaa88.png)
![f58012e5cf894d626677826c0fb43c1](https://user-images.githubusercontent.com/59277770/71804321-05e3c280-309e-11ea-85dc-047b0ecf710e.png)

Here is the output:
![output](https://user-images.githubusercontent.com/59277770/71804377-40e5f600-309e-11ea-9034-70d6d6dc2282.png)
I wonder the reasons of the result.There are no changes in test.py.
I would very appreciate if you could help me,thank you!

**Comment by tks-reply** [comment]
@JiahuiYu 
Thank you!I have solved Q4 by deleting offset_flow=None,and the result could inpaint as normal.
Q5:
I have modified inpaint_model.py as follows.
At line 68:
x_stage1 = x
      for i in range(5):
            img_Guassian = cv2.GaussianBlur(x_stage1, (3, 3), 0)
            x_stage1 = img_Guassian
Return:Src is not a numpy array, neither a scalar
What should I do if I want to use cv2.GaussianBlur?
I would very appreciate if you could help me,thank you very much!

**Comment by redaghanem** [comment]
please can you help me as you run this code i think you understand code so I would very appreciate if you could help me,thank you very much!

when i run code with any image in example folder all result is good 

if i need to test new image 

original image
![input2](https://user-images.githubusercontent.com/43389843/73122675-2feb1f00-3f90-11ea-8cb4-fd51389463ee.png)

![input3](https://user-images.githubusercontent.com/43389843/73122672-1ea21280-3f90-11ea-8d24-da9bafa58d22.png)


what correct method to remove the region from it like eye from face image and how to create mask image of it to run this code 

!python test.py --image examples/input.png --mask examples/mask.png --output examples/output.png --checkpoint release_celeba_hq_256_deepfill_v2

i use google colab 

please help me
