### ISSUE TITLE
input of train and test

### ISSUE THREAD

**Issue by balablb** [JiahuiYu/generative_inpainting#388]
hello,@JiahuiYu .I want to train model on my own dataset .Here is my understanding:
input of train are original images (flist format),don't need a mask.
input of test contain image(with free-form mask) and mask image.
Am I right？
Thank you ~

**Comment by JiahuiYu** [comment]
Yes.

**Comment by redaghanem** [comment]
@edgexspear 

can you tell me what step to create a mask for any input image

**Comment by balablb** [comment]
> @edgexspear
> 
> can you tell me what step to create a mask for any input image

Do u mean test with a mask?
