### ISSUE TITLE
Eager execution - Reg

### ISSUE THREAD

**Issue by Adhiyaman-Manickam** [JiahuiYu/generative_inpainting#390]
Hi @JiahuiYu 

Sorry for disturbing you.

Does code support eagar execution? 
I am trying to convert tensor into numpy in some part of your code but it does not support. 
Hence, I used eagar execution then I got the the following error

ValueError: tf.enable_eager_execution must be called at program startup.

I tried and used the eagar_execution in the begining of the code. Again I got the same error.
I have tried many ways. I could not figured out. That's why, I approched you.

Again, sorry for disturbing you.
Kindly let me know my mistake and does code support eagar execution.

Thank you so much.

**Comment by JiahuiYu** [comment]
No eager mode is not supported yet.
