### ISSUE TITLE
The grad flow of contextual_attention

### ISSUE THREAD

**Issue by weizequan** [JiahuiYu/generative_inpainting#392]
In the function of contextual_attention, i don't know which is the right grad flow?

1, y->wi_center->raw_w->b->x [in fact, b=x.  x, offset_flow = contextual_attention(x, x, mask_s, 3, 1, rate=2)]. This means tf.extract_image_patches (Line 283 in inpaint_ops.py) doesn't break grad flow.

2, y->yi->xi->f_groups->f->x [f =x. contextual_attention(x, x, mask_s, 3, 1, rate=2)] This mean resize operation (Line 289 and 290 in inpaint_ops.py) doesn't break grad flow.

Both guesses may be wrong. Thanks a lot!

**Comment by JiahuiYu** [comment]
I think both resize and extract_patch DO have gradients. Extract_patch is basically the re-indexing. Resizing in tensorflow has gradients.
