### ISSUE TITLE
image loses pixels in its size after inpainting

### ISSUE THREAD

**Issue by elfifo4** [JiahuiYu/generative_inpainting#394]
Hi Jiahui

Sometimes when I apply inpainting on some images, image is getting trimmed a little bit in its width or height.

please see this original image:
![1050x1400](https://user-images.githubusercontent.com/13766004/71883717-a938e400-313f-11ea-9071-5dd42aa9088d.jpg)

and the result:
![1048x1400](https://user-images.githubusercontent.com/13766004/71884023-34b27500-3140-11ea-856e-7768638d68aa.jpg)

width decreased from 1050px to 1048px.

Thanks in advance!

**Comment by JiahuiYu** [comment]
Yes. I guess it is because the downsampling and upsapling layers in neural networks. Please make sure your input resolution is divisible by 8.
