### ISSUE TITLE
I want to ask for samples of image.png,image_edge.png sample 

### ISSUE THREAD

**Issue by MahmoudSamiRDI** [JiahuiYu/generative_inpainting#395]

**Comment by MahmoudSamiRDI** [comment]
As I want to use these repo to keep the layout of an image after removing text lines in the image using its mask but the output was not fine so, I want to train using images and its mask without any irregularity in the mask also without the random mask

**Comment by JiahuiYu** [comment]
Edge maps are extracted from HED edge detector. Currently I don’t have an example in hand.
