### ISSUE TITLE
Could you please help me to address the problem about transfer learning?

### ISSUE THREAD

**Issue by Yaohongchen** [JiahuiYu/generative_inpainting#396]
Thank you for your awesome work. I am a beginner and I want use a small dataset for a transfer learning based on pretrained model of places2. The dataset has 50 images (resolution: 512 by 512), could you please rerecommend some parameter settings or a specific guidance?
The other question is why you set the beta1=0.5 for AdamOptimizer ? Thank you for your help

**Comment by JiahuiYu** [comment]
Hi, in fact I don’t have such experience.

**Comment by Yaohongchen** [comment]
Thank you~ I want to know why set the beta1=0.5 for AdamOptimizer ?
