### ISSUE TITLE
How to use deepfill-v2 for transfer learning based on small dataset

### ISSUE THREAD

**Issue by Yaohongchen** [JiahuiYu/generative_inpainting#398]
Hi Jiahui, thanks for your amazing work and open source code. I hope this approach can also be used for the inpainting of the images with small missed area. I want to try transfer learning based on the model which was pre-trained by you as the initialization parameters. But I have no idea if I should retrain from the concat of the two branch in Refinement Network, or retrain from overall Refinement network and freeze the Coarse Network, or retrain the both Coarse Network and Refinement Network. Could you please provide some suggestions for me? BTW, I have a small dataset which is composed of 40 images with resolution 512 by 512.

**Comment by JiahuiYu** [comment]
I would suggest to train both stages of the network.

**Comment by Yaohongchen** [comment]
Thank you for your suggestion.
