### ISSUE TITLE
why when i test a new image result not good

### ISSUE THREAD

**Issue by redaghanem** [JiahuiYu/generative_inpainting#401]
why when i test a new image result not good, i use your model 

/content/drive/My Drive/Colab Notebooks/generative_inpainting-master/release_celeba_hq_256_deepfill_v2

i run this code in google colab and test image from your folder example result is very good

but when try this image using this code

!python test.py --image examples/input3.png --mask examples/mask3.png --output examples/output.png --checkpoint release_celeba_hq_256_deepfill_v2

this is an input image and mask

![input3](https://user-images.githubusercontent.com/43389843/73110421-0342f300-3f0f-11ea-9e1d-7030ed74524c.png)
![mask3](https://user-images.githubusercontent.com/43389843/73110422-03db8980-3f0f-11ea-9875-885b868a8fdb.png)

i get this result

![f2944162-9199-4f74-9f05-066e8d10912e](https://user-images.githubusercontent.com/43389843/73110572-99771900-3f0f-11ea-8922-c8d950c03c91.png)

why?

**Comment by redaghanem** [comment]
also this images from your example folder when i make a litle change in image remove region from right position

![input5](https://user-images.githubusercontent.com/43389843/73110678-0094cd80-3f10-11ea-9634-3199b31138d6.png)
![mask5](https://user-images.githubusercontent.com/43389843/73110679-0094cd80-3f10-11ea-9a40-ca60d68515a4.png)



i get this result

![7128f763-46ea-4b57-96db-7b63027068fc](https://user-images.githubusercontent.com/43389843/73110690-07234500-3f10-11ea-99e5-2ebdcaa08d86.png)


i think i do something wrong please help me?

**Comment by JiahuiYu** [comment]
Please carefully follow our README to run. Based on current information you provided, I have no idea on what is wrong.

**Comment by redaghanem** [comment]
I think i make a mistake in create a mask

Can you tell me if i want to test model for a new image .png from internet 

What required to make it as valid input  and how create it's mask


I usually open it in photoshop and remove area 
Is this correct please?  help me
