### ISSUE TITLE
what steps to create mask for this image

### ISSUE THREAD

**Issue by redaghanem** [JiahuiYu/generative_inpainting#402]
what steps to create mask for this image

![input2](https://user-images.githubusercontent.com/43389843/73122387-07adf100-3f8d-11ea-9136-6ce5f34c7068.png)
![input3](https://user-images.githubusercontent.com/43389843/73122388-07adf100-3f8d-11ea-88e2-e7c7ddfbf5f2.png)

i need to test code on this image how can i create mask .png image

**Comment by redaghanem** [comment]
when i run code with any image in example folder all result is good 

if i need to test new image how i remove region from it like eye from face image and how to create mask image of it?

please help me

**Comment by srianandbs** [comment]
Hi redaghanem, can you help me to run this code...!

**Comment by redaghanem** [comment]
I have a problem to run code on a new image


What error you had to help you to run test

**Comment by srianandbs** [comment]
I am new to this kind of code, so i need a complete guidance from the initial setup to final output. can i contact you personally?. Also i have another questions too.

**Comment by JiahuiYu** [comment]
To create mask, you just fill the pixels to ones and background to zeros, using whichever tool you can.
