### ISSUE TITLE
Understanding input tensors

### ISSUE THREAD

**Issue by avisekiit** [JiahuiYu/generative_inpainting#405]
Dear Authors,
Thanks for open-sourcing your awesome paper.

I had some specific doubts regarding the input which is fed to the network.  I know ALMOST similar questions have been asked on this topic but, unfortunately, I could not get a full picture about the exact nature of the inputs which are fed to the network.

For example, if we consider the main input [line:](https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint_model.py#L41)
tf.concat([x, ones_x, ones_x*mask], axis=3). My doubts are:

1. I understand (x) is the INCOMPLETE normalized image in [-1, 1]. Do you make the masked pixels = 0 in (x) or you make masked pixels = 1 in (x)

2. Why do we need to input the (ones_x) tensor ? It is simply an all-white input? Is it explicitly used anywhere for inpainting purpose?

3. Is the (mask) tensor = 0 on masked pixels or is it = 1 on masked pixels ?

Thanks,
Avisek

**Comment by JiahuiYu** [comment]
1. I remember that masked pixels are zeros, but you are encouraged to check the code. 

2. Please search over history issues as this one has been answered for several times. The short answer is that all-ones channel indicate the image boundary. 

3. In masks, the masked regions are ones and again you are encouraged to check the code.
