### ISSUE TITLE
How to train Deepfill v2

### ISSUE THREAD

**Issue by dayeguilaiye** [JiahuiYu/generative_inpainting#406]
set "guided" to true, and get a dataset from HED edge detection, and train it from scratch?

or

set "guided" to false, then train it with places256(or others), then change to "guided: true", and train it with HED?

if the first one, How big the dataset should be?
if the second one, it seems like different network between "guided: true/false", how to resume training?

Thanks a lot if you can answer me!

**Comment by JiahuiYu** [comment]
The first one is correct. I use the entire places2 dataset. Currently NO guided pretrained model is provided.
