### ISSUE TITLE
Question about batch testing on gpu

### ISSUE THREAD

**Issue by Dominoer** [JiahuiYu/generative_inpainting#407]
Hi, JiahuiYu. Thanks for your useful code first. 
I want to do batch testing on multi-GPU, could you please tell me how to enable GPU testing?
Sorry for the dumb question.

**Comment by Dominoer** [comment]
Sorry, I installed a cpu-version instead of gpu-version. closed

**Comment by LetsGoFir** [comment]
How to do this?
