### ISSUE TITLE
about the loss function l1 loss and ae loss

### ISSUE THREAD

**Issue by kikyou123** [JiahuiYu/generative_inpainting#42]
In your paper, I can only find the l1 loss, I am confused about the ae loss?

**Comment by JiahuiYu** [comment]
In code, we use l1 loss to regress only the masked regions, and use ae loss to regress the unmasked regions. This simply means `l1 + ae` = `ae loss of entire image`. The paper's description is correct.

**Comment by wuyxiquanquan** [comment]
Where does the AE loss come from?

**Comment by buchholzmd** [comment]
@wuyxiquanquan this is the auto-encoder loss (as in BEGANs). The l1 loss regresses the holes (masked regions) to the ground truth regions. The ae loss is the standard auto-encoder loss to reconstruct the rest of the image. Note that the Generator loss is `l1 + ae`, as described above.
