### ISSUE TITLE
test results error

### ISSUE THREAD

**Issue by summerwbb** [JiahuiYu/generative_inpainting#420]
Thank you very much for sharing the code！
Using test.py, the effect of testing my own data is not consistent with your effect. Can you help me to have a look?
![image](https://user-images.githubusercontent.com/40291885/77554127-a0f77600-6ef0-11ea-86f8-36896c9213e7.png)
![image](https://user-images.githubusercontent.com/40291885/77554134-a5239380-6ef0-11ea-93fc-dcfa987a0fb2.png)
![image](https://user-images.githubusercontent.com/40291885/77554149-a81e8400-6ef0-11ea-8e08-7ad85f7865d1.png)

**Comment by seanyuner** [comment]
Same problem. 
I mainly care about the white area in the inpainted image. After I trained the model on my own data, they still exist in some cases.

**Comment by JiahuiYu** [comment]
The failure is likely due to the mask being too big, larger than the masks during training.
