### ISSUE TITLE
My test results are not good. Could you give me some advice?

### ISSUE THREAD

**Issue by chestnut1996** [JiahuiYu/generative_inpainting#421]
Hi!

My experiments were performed on 30 pathological datasets with resolution of 1000X1000 pixel. 

I want to remove the nucleus from the background and get a pure background picture, like this:
![issue](https://user-images.githubusercontent.com/45276020/77657769-b46a1600-6fb0-11ea-9318-26cd299581a7.png)

But the model I trained was bad. The nucleus cannot be completely removed from the background.
My result is:
![my result](https://user-images.githubusercontent.com/45276020/77658506-c304fd00-6fb1-11ea-8a32-99f33c72ff84.png)

The losses look like converged.
![loss](https://user-images.githubusercontent.com/45276020/77658687-01022100-6fb2-11ea-9496-82613c4ec77c.png)

I trained the model on four pieces of 2080Ti.

Here is my profile :
```
num_gpus_per_job: 4  # number of gpus each job need
num_cpus_per_job: 6  # number of gpus each job need
num_hosts_per_job: 1
memory_per_job: 32  # number of gpus each job need
gpu_type: 'nvidia-2080Ti'

name: TCGA_2  
model_restore: 'logs/tcga_2_coarse' 
dataset: 'tcga'  
random_crop: True  
val: True  
log_dir: logs/tcga_2_refine

gan: 'sngan'
gan_loss_alpha: 1
gan_with_mask: True
discounted_mask: True
random_seed: False
padding: 'SAME'

train_spe: 4000
max_iters: 100000000
viz_max_out: 10
val_psteps: 2000

static_view_size: 1
img_shapes: [256, 256, 3]
height: 128
width: 128
max_delta_height: 32
max_delta_width: 32
batch_size: 8
vertical_margin: 0
horizontal_margin: 0

ae_loss: True
l1_loss: True
l1_loss_alpha: 1.

guided: False
edge_threshold: 0.6
```

I also searched for other issue, but I still don't know what the problem is. Could you give me some advice?

**Comment by buchholzmd** [comment]
The primary architecture here is an autoencoder. The coarse/fine generator is optimized using l1 reconstruction loss. It is being trained to inpaint the holes to reconstruct the original image, in addition to using the background information to infer/hallucinate the foreground.

Considering your images are very sparse (in terms of the holes), there may not be much background information for the model to utilize and it is relying more on the l1 reconstruction loss, and is doing a good job reconstructing the nuclei.

However, this is only my speculation; the author may have deeper insight than I.

**Comment by chestnut1996** [comment]
> The primary architecture here is an autoencoder. The coarse/fine generator is optimized using l1 reconstruction loss. It is being trained to inpaint the holes to reconstruct the original image, in addition to using the background information to infer/hallucinate the foreground.
> 
> Considering your images are very sparse (in terms of the holes), there may not be much background information for the model to utilize and it is relying more on the l1 reconstruction loss, and is doing a good job reconstructing the nuclei.
> 
> However, this is only my speculation; the author may have deeper insight than I.

So should I need to adjust `L1_loss_ alpha`?

**Comment by chestnut1996** [comment]
I train the refine step after adjusting the `L1_loss_alpha` from 1 to 0.5, and I find the result is better. 

I will retrain the whole process. 

Here are my latest results.
![批注 2020-05-30 092832](https://user-images.githubusercontent.com/45276020/83316424-34825580-a258-11ea-8f34-cd0bc260b3cd.png)

**Comment by yongshuaihuang** [comment]
Can to give me some advice on how to modify the code  and  training my owndata with  mask?
