### ISSUE TITLE
Tensorflow model

### ISSUE THREAD

**Issue by nanox77** [JiahuiYu/generative_inpainting#425]
Hi there!
I have a question: how to generate tensorflow model?. I downloaded a checkpoint and it's work really good, but I need generate a model.

Thank you!

**Comment by seanyuner** [comment]
If you mean you want a pb file, you can check [here](https://stackoverflow.com/questions/45864363/tensorflow-how-to-convert-meta-data-and-index-model-files-into-one-graph-pb).
