### ISSUE TITLE
g_loss is negative and decreasing. The smaller g_loss, the better the generated model, is it?

### ISSUE THREAD

**Issue by GuanRainy** [JiahuiYu/generative_inpainting#426]
@JiahuiYu ,Thanks for your research!I am very sorry to bother you. when I train my custom dataset, the d_loss are fast converging, but the g_loss is negative and decreasing, Does the smaller g_loss(negative), the better the generated model performance?

**Comment by JiahuiYu** [comment]
G_loss decreases to negative is normal. Keep training.

**Comment by GuanRainy** [comment]
@JiahuiYu  Thanks for the reply. Sorry to bother you again.
Does the smaller g_loss(negative), the better the generated model performance?

**Comment by JiahuiYu** [comment]
Not necessary.
