### ISSUE TITLE
Dear author, I still have some doubts about sketch instruction training

### ISSUE THREAD

**Issue by jialiang66** [JiahuiYu/generative_inpainting#427]
![1589555467(1)](https://user-images.githubusercontent.com/53569533/82065913-495fd480-9701-11ea-9371-f4e67f50ee61.jpg)
This is a list of my training files. On the left is a picture, and on the right is a sketch. When I change the guided parameter to true, the training is performed. The program is stuck in the interface below, and does not occupy the graphics card memory.
![QQ截图20200515231500](https://user-images.githubusercontent.com/53569533/82066286-c5f2b300-9701-11ea-85a4-7636994445bc.png)
What is the problem?

**Comment by JiahuiYu** [comment]
There should be an issue before this log of "callback". I think it is a data file issue. Please try to locate and fix it.

**Comment by jialiang66** [comment]
![image](https://user-images.githubusercontent.com/53569533/82109509-1ea96680-9769-11ea-9cf7-2e35d73e52c6.png)

thank you for your reply. What I also think is that the data is not loaded, but I have created it according to the file list format you recommended, `image.jpg, guided_image.jpg`such as the first picture, and this problem still occurs. Do you have any suggestions to solve this problem?

**Comment by nsalminen** [comment]
@jialiang66 please check out the following line: https://github.com/JiahuiYu/generative_inpainting/blob/cfc1d41a882dbbe7c2c35446c8e49b81b7ed51ff/train.py#L34

Either consider changing your .flist and folder structure, or change line 34 of train.py to the following:
```python
fnames = [fname.split(', ') for fname in fnames]
```

**Comment by jialiang66** [comment]
@nsalminen Thank you for your answer. I have made some changes to the code based on your answer and have already started training. Your help is greatly appreciated.
Excuse me, I have another question. If I want to use a pre-trained model to guide repair, which test program should I run? Is it this one?
`guided_batch_test.py`

**Comment by nsalminen** [comment]
@jialiang66 No problem! Yes you're right
