### ISSUE TITLE
on Tensorflow 2

### ISSUE THREAD

**Issue by dragen1860** [JiahuiYu/generative_inpainting#429]
Dear author: 
   Thanks for this paper and repo. it's really neat and well-documented!
   However, Tensorflow 1 is extremely hard to use. It would be easy to use if you can adapt it to tensorflow 2.0 version. Thank you again.

**Comment by vutuanhai237** [comment]
You can use this sentence: `tf_upgrade_v2 --infile old_file.py --outfile new_file.py` but some line/block you must to back to tf 1.x to use it.

**Comment by JiahuiYu** [comment]
@vutuanhai237 Thanks! Let me keep this issue on the issue page.
