### ISSUE TITLE
module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'

### ISSUE THREAD

**Issue by kikyou123** [JiahuiYu/generative_inpainting#43]
when I run the code, the error module 'tensorflow.python.ops.nn' has no attribute 'leaky_relu'. how can I fix it?

**Comment by JiahuiYu** [comment]
I saw the API of leaky_relu still exists in TensorFlow. https://www.tensorflow.org/api_docs/python/tf/nn/leaky_relu

Which version of TensorFlow you are using?

**Comment by kikyou123** [comment]
I rewrite the leaky_relu with myself, I use 1.3.0

**Comment by JiahuiYu** [comment]
Ok, I will close issue now.
