### ISSUE TITLE
mobile device friendly context attention

### ISSUE THREAD

**Issue by dragen1860** [JiahuiYu/generative_inpainting#430]
Dear author: 
   Thanks for the context attention approach proposed.
    Currently I'm trying to convert this model to mobile device. But I found the context attention module is not mobile device friendly. In other world, the extract_image_patches ops is not well supported in mobile device in tflite. 
    Hence I wonder Is there any alternative approach to replace contextual attention? Can we just remove the context attention module from the network? Does it significantly drop the performance? 

   Thank you very much .

**Comment by JiahuiYu** [comment]
#431
