### ISSUE TITLE
What is the ground truth for the object removal task?

### ISSUE THREAD

**Issue by LeileiCao** [JiahuiYu/generative_inpainting#433]
Dear Dr.Yu,
Thank you for creating this awesome work. I am a little confusing about the object removal and user-guided editing. If we train the network using the object removal task, what is the ground truth? Or the network could be directly extended to object removal and creative editing tasks witout fine tunning?

**Comment by JiahuiYu** [comment]
We train on randomly sampled masks. By random sampling, most likely the masks are at backgrounds. Thus, after training, when you mask out an object, it is likely that the region will be filled with backgrounds.

There is no ground truth.
