### ISSUE TITLE
if the uninpainting region is colorful ,the inpaint region is uncoordinating.

### ISSUE THREAD

**Issue by DavideHe** [JiahuiYu/generative_inpainting#435]
I inpaint a cole flowers picture with a person mask using your trained model.cole flowers is colorful,and the inpaint region is uncoording to the whole picture .But the texture is ok.Could you give some advice?

**Comment by JiahuiYu** [comment]
Are you using our released checkpoint or re-training a new one?

**Comment by DavideHe** [comment]
> Are you using our released checkpoint or re-training a new one?
yes,I use the released checkpoint on Places2.  
You could try it using the picture where people stand before the  cole flowers.
