### ISSUE TITLE
Mode collapse or just training?

### ISSUE THREAD

**Issue by somepago** [JiahuiYu/generative_inpainting#439]
Hi JiahuiYu, congratulations on the excellent inpainting work. I am trying to train the model on celebahq dataset, around 100k iterations into the training,  it is showing mode collapse behavior (For example, all the validation images on tensorboard having the same eye type in predictions when eyes are masked). Did you face any such issue? If yes, how did you resolve it?

**Comment by JiahuiYu** [comment]
If mode collapse happens, it is usually better to re-train from scratch.
