### ISSUE TITLE
Issue during testing with my own examples

### ISSUE THREAD

**Issue by CyrilShch** [JiahuiYu/generative_inpainting#448]
Dear authors, could you please tell me what could be wrong, I use my own image and its generated mask for testing, I got the following error: 

WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/neuralgym/ops/layers.py:142: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/neuralgym/callbacks/npz_model_loader.py:31: The name tf.get_variable_scope is deprecated. Please use tf.compat.v1.get_variable_scope instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/neuralgym/ops/gan_ops.py:138: The name tf.layers.Conv2D is deprecated. Please use tf.compat.v1.layers.Conv2D instead.

---------------------------------- APP CONFIG ----------------------------------
num_gpus_per_job: 1
num_cpus_per_job: 4
num_hosts_per_job: 1
memory_per_job: 32
gpu_type: nvidia-tesla-p100
name: places2_gated_conv_v100
model_restore: 
dataset: celebahq
random_crop: False
val: False
log_dir: logs/full_model_celeba_hq_256
gan: sngan
gan_loss_alpha: 1
gan_with_mask: True
discounted_mask: True
random_seed: False
padding: SAME
train_spe: 4000
max_iters: 100000000
viz_max_out: 10
val_psteps: 2000
data_flist: 
  celebahq: ['data/celeba_hq/train_shuffled.flist', 'data/celeba_hq/validation_static_view.flist']
  celeba: ['data/celeba/train_shuffled.flist', 'data/celeba/validation_static_view.flist']
  places2: ['data/places2/train_shuffled.flist', 'data/places2/validation_static_view.flist']
  imagenet: ['data/imagenet/train_shuffled.flist', 'data/imagenet/validation_static_view.flist']
static_view_size: 30
img_shapes: [256, 256, 3]
height: 128
width: 128
max_delta_height: 32
max_delta_width: 32
batch_size: 16
vertical_margin: 0
horizontal_margin: 0
ae_loss: True
l1_loss: True
l1_loss_alpha: 1.0
guided: False
edge_threshold: 0.6
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/content/generative_inpainting/test.py", line 32, in <module>
    assert image.shape == mask.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by stmunees** [comment]
1. Use an older version of Tensorflow, like 1.13.0 for the depreciation warning.
`pip install tensorflow==1.13.1`

2. The 'NoneType' object has no attribute means the folder is having something that is not an image and when read by the code generally, it is given NoneType. So make sure you have just images in the folder. Also, there is a possibility that the image is corrupted.

#### _Tips for point 2 if you're using a Mac_
Generally, Mac creates a `.DS_Store` file, which is a system file used for maintaining attributes by OS. There is a possibility that is interfering. 

- `cd` into the folder containing the image.
- `ls -a` to see all files including hidden file.
- `rm -f .DS_Store` to remove it and try again the code. If it runs, you can create an exception to not take that in code in future.

While there could be better solutions, this is a quick fix.

**Comment by CyrilShch** [comment]
@snitch30 thanks!
