### ISSUE TITLE
Loss negative

### ISSUE THREAD

**Issue by nhutthanh340** [JiahuiYu/generative_inpainting#450]
Hi, I am researching on your great project, but I have some confusion about the convergence of D. I do not know that when D converges, which value will D come to? (How the curve will change). If possible, please send pictures of the curve that have D-convergenced. Thank you very much. 

In below, there are 3 curve which I trained in 12 epochs (I am worry about the negative of loss)

![image](https://user-images.githubusercontent.com/36669308/85254359-50a99900-b48a-11ea-9ae1-c8147e60a6c2.png)

**Comment by JiahuiYu** [comment]
#305
