### ISSUE TITLE
When does model converge? (deep v1)

### ISSUE THREAD

**Issue by huynhhoanghuy** [JiahuiYu/generative_inpainting#452]
Hi sir,

I am reading your paper and reimplement your code. I see that in your Algorithm has sentence: "while G has not converged". 
Q1: In your code, you write https://github.com/JiahuiYu/neuralgym/blob/88292adb524186693a32404c0cfdc790426ea441/neuralgym/train/trainer.py#L121
I found and no see anything about difference of (pre_epoch_loss, current_epoch_loss) < threshold, or stop-when-updates-slow, ... If do the same, whether after the loop ended, loss has converged, doesn't it?
![image](https://user-images.githubusercontent.com/32119423/85971919-a5a05e80-b9f8-11ea-9e5a-46a20d6566e5.png)

Q2: I know your code apply 1-Lipzchit countinous. However, will your model be always 100% converge?
Q3: What do you rely on to determine the best size of hole in raw_image (256x256)?
Thank you.

**Comment by JiahuiYu** [comment]
Hey sorry for the late reply.

Q1: Good question, we don't have a good metric to measure convergence. So if the visual results are good, stop training.
Q2: No.
Q3: Regarding the mask sizes, one golden rule is to be consistent between training and testing.
