### ISSUE TITLE
How to check the output effect of the network during the training process

### ISSUE THREAD

**Issue by xiaoweiii** [JiahuiYu/generative_inpainting#455]
Sorry to bother you,I want to input some pictures during the training process and check the output effect of the network. What should I do?

**Comment by nsalminen** [comment]
@xiaoweiii You can use [Tensorboard](https://www.tensorflow.org/tensorboard/get_started) for intermediate visualizations and measurements for training and validation. ([info](https://github.com/JiahuiYu/generative_inpainting#tensorboard))

**Comment by xiaoweiii** [comment]
> @xiaoweiii您可以使用[Tensorboard](https://www.tensorflow.org/tensorboard/get_started)进行中间可视化和测量，以进行培训和验证。（[信息](https://github.com/JiahuiYu/generative_inpainting#tensorboard)）

Thank you very much, I will try to use tensorboard to check the training effect

**Comment by Laputa-tu** [comment]
> @xiaoweiii You can use [Tensorboard](https://www.tensorflow.org/tensorboard/get_started) for intermediate visualizations and measurements for training and validation. ([info](https://github.com/JiahuiYu/generative_inpainting#tensorboard))
How to show l1_loss on Tensorboard?

**Comment by JiahuiYu** [comment]
@nsalminen Thank you!

**Comment by Cristy94** [comment]
Any easy way to also show a test validation image (before/after infill) example in tensorboard?
