### ISSUE TITLE
How to read fnames for each batch by setting return_fnames=True on data.data_from_fnames()

### ISSUE THREAD

**Issue by jelujelu** [JiahuiYu/generative_inpainting#456]
Hi,
I want to apply different mask for each image within the same batch using the annotated facial landmarks.
If I understand correctly, I need to first read the fnames within each batch by setting `return_fnames=True` when creating the data object.

The data pipeline returns me `<tf.Tensor 'FIFOQueueV2_DequeueMany:1' shape=(16,) dtype=string>`, however I have trouble with viewing/reading this tensor using tf.run(). What would be the correct way to obtain the filenames for each batch?

Thanks,

**Comment by JiahuiYu** [comment]
It returns string tensor and should be easy to view in tf.run() by tf.Print? It's a tf-related question so you might also want to checkout tensorflow communities.
