### ISSUE TITLE
AE_LOSS, L1 LOSS

### ISSUE THREAD

**Issue by nhutthanh340** [JiahuiYu/generative_inpainting#458]
Hi, can you explain and help me with a problem? If I do not use ae_loss to measure the error of background and l1 for the foreground, but I only use l1 for the generated image, what is the problem? Thanks.

**Comment by Laputa-tu** [comment]
> Hi, can you explain and help me with a problem? If I do not use ae_loss to measure the error of background and l1 for the foreground, but I only use l1 for the generated image, what is the problem? Thanks.

How to show l1_loss on Tensorboard?

**Comment by JiahuiYu** [comment]
#42
