### ISSUE TITLE
consistency of train and test data image resolution

### ISSUE THREAD

**Issue by DragonDeux** [JiahuiYu/generative_inpainting#459]
Hello :D 

I have a basal question about, should we resize the test image resolution same to training date image resolution? during the training process, the image shapes are 256*256, but what about if i use a image of 1920*1080 for testing?

kind regards,
dD

**Comment by JiahuiYu** [comment]
Hey, you can still do it. I think what matters more is the mask size, i.e., your training mask sizes should match your test ones.
