### ISSUE TITLE
Tensorflow v2 compatibility

### ISSUE THREAD

**Issue by Cristy94** [JiahuiYu/generative_inpainting#462]
I am trying to run it using Tensorflow v2, but I get several errors.  I used this [upgrade tool](https://www.tensorflow.org/guide/upgrade) to try to fix it, but it still complains about ` module 'tensorflow' has no attribute 'contrib'`.

I noticed that the only functions used are `arg_scope` and `add_arg_scope` from `tensorflow.contrib.framework.python.ops`.

Any suggestions on how to fix/replace those calls?

```
from tensorflow.contrib.framework.python.ops import arg_scope
from tensorflow.contrib.framework.python.ops import add_arg_scope
```

EDIT: 
Oh, neuralgym also seems to be using contrib.

```
neuralgym\ops\layers.py", line 93, in <module>
    activation_fn=None, w_init=tf.contrib.layers.xavier_initializer_conv2d(),
AttributeError: module 'tensorflow' has no attribute 'contrib'
```

**Comment by Cristy94** [comment]
I managed to make it run by using the upgrade tool on both this repo and neuralgym and removing the uses of `arg_scope`. It seems to run and start training, but there is no model file created, the tensorboard only contains the graph and the training progress is not showing in the console (might be because I am on Windows).

Any idea why logging doesn't work? The Secondary Trainer has `log_progress` set to `False`, but for the Primary Trainer I set it to `True`, yet it doesn't log anything after training starts. Might be related to the fact that no checkpoint file is created, after how many iterations is the checkpoint saved?

**Comment by JiahuiYu** [comment]
Hey, we disabled the log in the latest neuralgym, but you can enabled it by #323

**Comment by Cristy94** [comment]
Thanks for the link, I understand the logging can be fixed, but this issue was more about compatibility with Tensorflow V2 and if there are any plans to update the repo to work by default with TF v2, as all the changes I had to make felt very hacky and could highly affect performance.

**Comment by JiahuiYu** [comment]
We do hope to freeze the code as much as possible, as any change may lead to degradation of model training. So officially we don't have plan to upgrade. We apologize.

**Comment by Cristy94** [comment]
Ok, thank you. I downgraded my TF to v1.15 and seems to work fine now.

**Comment by yick2232** [comment]
> I am trying to run it using Tensorflow v2, but I get several errors. I used this [upgrade tool](https://www.tensorflow.org/guide/upgrade) to try to fix it, but it still complains about ` module 'tensorflow' has no attribute 'contrib'`.
> 
> I noticed that the only functions used are `arg_scope` and `add_arg_scope` from `tensorflow.contrib.framework.python.ops`.
> 
> Any suggestions on how to fix/replace those calls?
> 
> ```
> from tensorflow.contrib.framework.python.ops import arg_scope
> from tensorflow.contrib.framework.python.ops import add_arg_scope
> ```
> 
> EDIT:
> Oh, neuralgym also seems to be using contrib.
> 
> ```
> neuralgym\ops\layers.py", line 93, in <module>
>     activation_fn=None, w_init=tf.contrib.layers.xavier_initializer_conv2d(),
> AttributeError: module 'tensorflow' has no attribute 'contrib'
> ```

if you want to inference with tf-2.0, just remove "arg_scope" and "add_arg_scope", like the code below, it's work fine.
```python
import tensorflow as tf
# from tensorflow.contrib.framework.python.ops import arg_scope # remove arg_scope
```
and 
```python
        # with tf.compat.v1.variable_scope(name, reuse=reuse), \
        #        arg_scope([gen_conv, gen_deconv],
        #                   training=training, padding=padding):
        with tf.compat.v1.variable_scope(name, reuse=reuse):
```

**Comment by Afsaneh299** [comment]
Hi
arg_scope in tensorflow 2 got remove.
How can I this code convert to tensorflow 2?

    with tf.variable_scope("network"):
        with contrib.framework.arg_scope(
                [contrib.layers.fully_connected, slim.layers.conv2d],
                # he initialization
                weights_initializer=contrib.layers.variance_scaling_initializer(),
                # l2 regularization
                weights_regularizer=contrib.layers.l2_regularizer(reg_lambda),
                # BN
                normalizer_fn=contrib.layers.batch_norm,
                normalizer_params={
                    "is_training": is_training,
                    "scale": True,
                    "updates_collections": None
                }
        ):
