### ISSUE TITLE
Confusing about the Deepfillv2 training d_loss

### ISSUE THREAD

**Issue by ewrfcas** [JiahuiYu/generative_inpainting#467]
Sorry to bother you but I have some problems while reimplement training the deepfillv2 model.
The d_loss is converged to 1.0 which means that the discriminator output the same value for both real and fake samples.
Should I train the netD for few times (maybe 5?) after once train the netG?
For some reason I can't use the tensorboard. Here is the manual loss pic.
![image](https://user-images.githubusercontent.com/12042259/92068440-80a1e080-edd9-11ea-8d5b-5ac92a184c20.png)
![image](https://user-images.githubusercontent.com/12042259/92068445-87305800-edd9-11ea-9ba6-331968e16a7d.png)
![image](https://user-images.githubusercontent.com/12042259/92068460-92838380-edd9-11ea-8efb-9fe1a71293e5.png)

The model results are not good
![image](https://user-images.githubusercontent.com/12042259/92068533-c2328b80-edd9-11ea-9736-3c4f469c3377.png)

**Comment by JiahuiYu** [comment]
D_loss is not stable which is common in GAN training. I think the loss you plotted is reasonable.
