### ISSUE TITLE
No enough gpus for dedicated usage.

### ISSUE THREAD

**Issue by KangSH9776** [JiahuiYu/generative_inpainting#47]
Hello, I have a question and I am writing. 
I want to 'test' the 'canyon_input.png' image in the 'examples' folder.
I also want to 'train' the 'places2' dataset
Look for your github and save the files to be stored in 'model_logs'
I wrote an error below the article saying that an error occurred in 'neuralgym'.
Your answers I'll wait.

<Error
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    ng.get_gpus(1)
  File "/home/pmi/Documents/Songhee/songhee/lib/python3.5/site-packages/neuralgym/utils/gpus.py", line 70, in get_gpus
    ' [(gpu id: num of processes)]: {}'.format(sorted_gpus))
SystemError: No enough gpus for dedicated usage. [(gpu id: num of processes)]: [(0, 3)]

**Comment by JiahuiYu** [comment]
Please see #35 #41.

**Comment by ChristophWu** [comment]
> Hello, I have a question and I am writing.
> I want to 'test' the 'canyon_input.png' image in the 'examples' folder.
> I also want to 'train' the 'places2' dataset
> Look for your github and save the files to be stored in 'model_logs'
> I wrote an error below the article saying that an error occurred in 'neuralgym'.
> Your answers I'll wait.
> 
> <Error
> Traceback (most recent call last):
> File "test.py", line 23, in 
> ng.get_gpus(1)
> File "/home/pmi/Documents/Songhee/songhee/lib/python3.5/site-packages/neuralgym/utils/gpus.py", line 70, in get_gpus
> ' [(gpu id: num of processes)]: {}'.format(sorted_gpus))
> SystemError: No enough gpus for dedicated usage. [(gpu id: num of processes)]: [(0, 3)]

I have the same problem. Have you already figured it out?

**Comment by JiahuiYu** [comment]
@ChristophWu If you only have one GPU, starts from 0. please add os.environ['CUDA_VISIBLE_DEVICES']='0' in test.py, and remove the line of ng.get_gpus(1). Please see #35 #41.
