### ISSUE TITLE
test result error

### ISSUE THREAD

**Issue by wangshuo2020** [JiahuiYu/generative_inpainting#470]
![add_res](https://user-images.githubusercontent.com/50904331/94246101-e05d5880-ff4d-11ea-828b-381e6ec7e664.jpg)
![case2_mask](https://user-images.githubusercontent.com/50904331/94246109-e5baa300-ff4d-11ea-81f9-5e05bfd926e5.png)
![case1_output](https://user-images.githubusercontent.com/50904331/94246236-14387e00-ff4e-11ea-9ffa-a46e9b727067.png)

Why is the training result like this? I tried several times, but no good results. I used the places2 pre-training model.

**Comment by JiahuiYu** [comment]
I think the mask you provided is difficult, in terms of leaked person legs. I think it would work better for object removal, which is the main use case for inpainting.
