### ISSUE TITLE
Inpainting_model.py uses the ReLU activation function before the contextual attention.

### ISSUE THREAD

**Issue by huoxiangzuo** [JiahuiYu/generative_inpainting#474]
Hey, thank you for your excellent work and shared code. Before contextual attention in inpainting_model.py, the gated convolution layer uses the ReLU activation function instead of the ELU. Is there any benefit to doing this?
`            x = gen_conv(x, 4*cnum, 3, 1, name='pmconv6',
                                activation=tf.nn.relu)`

**Comment by JiahuiYu** [comment]
Ah I forgot why.. Maybe you can do some ablation studies on that.
