### ISSUE TITLE
Doesn't use GPUs to train when 7 GPUs available

### ISSUE THREAD

**Issue by skoshx** [JiahuiYu/generative_inpainting#475]
Hello, i am renting a 7 GPU (GTX 1080 TI) machine from vast.ai. I have changed inpaint.yml, changed the num_gpus_per_job to 7. Also tested it with value of 1.

When i run the train.py script, even 10 iterations takes a REALLY long time. When i check nvidia-smi, it doesn't show almost any usage. Here is the result from nvidia-smi:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.66       Driver Version: 450.66       CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:05:00.0  On |                  N/A |
|100%   19C    P8    14W / 250W |      0MiB / 11175MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 00000000:06:00.0 Off |                  N/A |
|100%   21C    P8    14W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  On   | 00000000:07:00.0 Off |                  N/A |
|100%   22C    P8    21W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  On   | 00000000:0A:00.0 Off |                  N/A |
|100%   21C    P8    13W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  On   | 00000000:0B:00.0 Off |                  N/A |
|100%   21C    P8    15W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  On   | 00000000:0C:00.0 Off |                  N/A |
|100%   19C    P8    16W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  On   | 00000000:0D:00.0 Off |                  N/A |
| 90%   20C    P8    14W / 250W |      0MiB / 11178MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

The temperatures are all room temperature. No work is being done on the GPUs. How can i fix this??

Thank you in advance!

**Comment by JiahuiYu** [comment]
#92 #68 #14 #308 Please take a look at these issues. I think you will need to comment out neuralgym.get_gpus, as that set environmental #GPU to use.
