### ISSUE TITLE
about this problem

### ISSUE THREAD

**Issue by atztao** [JiahuiYu/generative_inpainting#477]
![image](https://user-images.githubusercontent.com/16068578/97424313-80424380-194b-11eb-9cf1-074945f382cd.png)
![image](https://user-images.githubusercontent.com/16068578/97424300-7b7d8f80-194b-11eb-9a61-1878197f35d5.png)
![image](https://user-images.githubusercontent.com/16068578/97424350-89331500-194b-11eb-9c57-ce2c01a87cef.png)

hey, can you meet this problem? i want to know, this problem cause by the training time not enough or others ?

**Comment by Pinakee15** [comment]
> ![image](https://user-images.githubusercontent.com/16068578/97424313-80424380-194b-11eb-9cf1-074945f382cd.png)
> ![image](https://user-images.githubusercontent.com/16068578/97424300-7b7d8f80-194b-11eb-9a61-1878197f35d5.png)
> ![image](https://user-images.githubusercontent.com/16068578/97424350-89331500-194b-11eb-9c57-ce2c01a87cef.png)
> 
> hey, can you meet this problem? i want to know, this problem cause by the training time not enough or others ?

Hey did you train on custom dataset or the places2 dataset. Thanks

**Comment by atztao** [comment]
> > ![image](https://user-images.githubusercontent.com/16068578/97424313-80424380-194b-11eb-9cf1-074945f382cd.png)
> > ![image](https://user-images.githubusercontent.com/16068578/97424300-7b7d8f80-194b-11eb-9a61-1878197f35d5.png)
> > ![image](https://user-images.githubusercontent.com/16068578/97424350-89331500-194b-11eb-9c57-ce2c01a87cef.png)
> > hey, can you meet this problem? i want to know, this problem cause by the training time not enough or others ?
> 
> Hey did you train on custom dataset or the places2 dataset. Thanks

I used custom dataset with the places2. Thanks.

**Comment by atztao** [comment]
I found small holes is good, but some large holes has the problem.Do you meet this?

**Comment by JiahuiYu** [comment]
No on standard benchmarks. Maybe you can start to train with small holes then progressively change to big holes.
