### ISSUE TITLE
Original log from tensorboard and reproducing Celeb-A results

### ISSUE THREAD

**Issue by hukkelas** [JiahuiYu/generative_inpainting#479]
Hi! Thanks for sharing your code open-source, it makes it very easy to understand your paper!

I'm trying to reproduce your result on the Celebrity-A dataset by retraining your model. 
I've split the Celeb-A dataset into 27K train / 3K val images and trained the model with the original source code and the config given in: https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint.yml

However, when validating on center mask images I'm seeing quite a performance drop compared to your original model (see below for metrics). I trained the model for ~24 hours on a V100-32GB, which is the same as 160K training steps on tensorboard.

**My questions are:**
1. Do you have the original tensorboard logs when you trained the model, then I can compare and try to see where the difference is.
2. What is the config file you used for Celeb-A (if it's not the one I linked).
3. How long did you train your model for in number of training steps?

### Validation metrics on Celeba-HQ 256x256 center mask

**Your model checkpoint given in the github readme.md:** 
 L1: 0.019221259281039238
L2: 0.05457606166601181
PSNR: 25.547083021850874
SSIM: 0.8014083052799579
LPIPS: 0.058718740940093994

**Retrained model for 160K steps with the config file linked above:** 
L1: 0.02299271896481514
L2: 0.06465483456850052
PSNR: 24.07686822468923
SSIM: 0.7864461851499979
LPIPS: 0.07174131274223328

**Comment by JiahuiYu** [comment]
@hukkelas Hi I think you will just need to train more iterations to match the performance of ours. The config should be correct.
