### ISSUE TITLE
why there is a hole in the inpainted result

### ISSUE THREAD

**Issue by Himan000** [JiahuiYu/generative_inpainting#489]
Hi @JiahuiYu ,
In the first place, your paper and model is great. But in some case, there is a hole in the result.
Image:
![image](https://user-images.githubusercontent.com/12414107/106433578-5b5def00-64ab-11eb-986c-54daa794c00e.png)

Mask:
![image](https://user-images.githubusercontent.com/12414107/106433623-6add3800-64ab-11eb-8312-c62d7cc6d031.png)

Result:
![image](https://user-images.githubusercontent.com/12414107/106433673-7b8dae00-64ab-11eb-8219-ce222008d977.png)

what's the problem? Thanks.
I use your pretrained model [places2](https://drive.google.com/drive/folders/1y7Irxm3HSHGvp546hZdAZwuNmhLUVcjO?usp=sharing)
If someone else could tell me why, it is ok too. Thanks.

**Comment by tmanh** [comment]
Short answer: the deep model tend to only work well on the dataset which it is trained on. So, you need to train the network on your dataset first. Then, you use it if it is good enough.

Longer answer: the deep model is trained to remember certain patterns, textures. When they see something similar, they just create something in a similar manner. Even though there is contextual attention module, it first needs to copy and then modify. And, the way it modifies is based on the learned patterns, and textures. Furthermore, if the size of a hole is too big (by big I mean absolute size, not relatively), the model will not work. Imagine CNN like a feature extractor with window size equals N x N. If the size of the hole is M x M with M = 2 * N. The network cannot cover the hole and fill in meaningful textures.

**Comment by Himan000** [comment]
Hi @tmanh ,

Got it, thanks. It's hard to fit arbitrary dataset. I should retrain the model. I close the issue/question. Thanks.
