### ISSUE TITLE
Different input size during testing stage

### ISSUE THREAD

**Issue by minmax100** [JiahuiYu/generative_inpainting#49]
During the testing stage (test.py), the network has to be built with a fixed size of image, such as

------------------
    #the image size is determined here 
    input_image = np.concatenate([image, mask], axis=2)

    sess_config = tf.ConfigProto()
    sess_config.gpu_options.allow_growth = True
    with tf.Session(config=sess_config) as sess:
        input_image = tf.constant(input_image, dtype=tf.float32)
        #the inference can now only accept a pre-defined size of image
        output = model.build_server_graph(input_image)
------------------

Just wander can I build an inference network that can accept various input size (i.e., with no need to pre-define the image size)?

or to be more specific, can I build a inference network that can achieve

output = model.build_server_graph(input_image)

where the input_image is a tensor of (batch_size, width, height, channel) = (1, None, None, 3)

**Comment by JiahuiYu** [comment]
Currently the function [here](https://github.com/JiahuiYu/generative_inpainting/blob/a2637d141727b2a7f9c3d2087e92691538eceb85/inpaint_ops.py#L243) does not support input with None shape. Once tensorflow supports it, you can inference on any shape with one graph.
