### ISSUE TITLE
about the tensorflow or pytorch

### ISSUE THREAD

**Issue by kikyou123** [JiahuiYu/generative_inpainting#51]
I wonder if you have implemented it with pytorch? I want to implement it using pytorch. Will the performance be decreased a lot?

**Comment by JiahuiYu** [comment]
The performance should not be related to which framework you use. Feel free to implement with pytorch.

**Comment by jeejeeli** [comment]
I found a repo [https://github.com/WonwoongCho/Generative-Inpainting-pytorch](url)
