### ISSUE TITLE
Trouble getting to work using AWS.

### ISSUE THREAD

**Issue by luckybulldozer** [JiahuiYu/generative_inpainting#52]
Fantastic work here, can't wait to get it running for some cultural preservation work.

I'm trying to run on an AWS deep learning GPU compute instance under ubuntu 16.04.  Anyway, I've got a few issues getting everything to work that I'm hoping are simple to fix.

Starting with training, I've copied the contents of the google drive into a data/celeba_hq/ folder.  When I run train.py, the process freezes with:
```[2018-05-28 05:14:54 @weights_viewer.py:60] Total size of trainable weights: 0G 10M 184K 136B (Assuming32-bit data type.)```
(aborting via control-c won't work, so I have to suspend the task and then ```killall python```

Does anything need to be altered in ```inpaint.yml``` to get the default celeb data set to work?  Your notes say to alter DATA_FLIST, LOG_DIR, IMG_SHAPES, however I can only see LOG_DIR as a parameter. 

Sorry for the questions which I'm sure will have obvious answers!

**Comment by JiahuiYu** [comment]
See [DATA_FLIST](https://github.com/JiahuiYu/generative_inpainting/blob/a2637d141727b2a7f9c3d2087e92691538eceb85/inpaint.yml#L32-L52), [IMG_SHAPES](https://github.com/JiahuiYu/generative_inpainting/blob/a2637d141727b2a7f9c3d2087e92691538eceb85/inpaint.yml#L55).

You will only need these parameters when you want to train a new model.

Cultural persevation with inpainting looks cool. Good luck!

**Comment by luckybulldozer** [comment]
This could really help our data sets look amazing, we do photogrammetry of ancient sites, so this could help us fill in missing parts of models etc.  How do I get it to run 1000's of iterations?
``` python test.py --image examples/viv_grass.png --mask examples/viv_grass.png --output examples/output.png --checkpoint model_logs/  ``` seems to only do a first pass.  I have a Tensorboard client running on my local machine ok, but can't seem to figure out any more due to my lack of experience here.
Thanks heaps!  -- also I've uncommented out line 23 as it keeps saying I don't have enough GPUs, is this ok?

**Comment by goldservice2017** [comment]
Hello @JiahuiYu  and @luckybulldozer 
I faced same error when I try to run `python train.py`
I downloaded place2 dataset and added some new images.
After this, I generated train.flist and val.flist file to use for training.
When I am running `python train.py`, I got same error like below:
![TinyTake22-11-2019-11-13-15_637100324029267881](https://user-images.githubusercontent.com/25535586/69443066-af077100-0d1b-11ea-8601-7a3bfaafb935.png)


Also there is my yaml file:
[inpaint.yml.txt](https://github.com/JiahuiYu/generative_inpainting/files/3880337/inpaint.yml.txt)

Also would you let me know about using multiple gpus for training?
I am not sure how to set `num_gpus_per_job`, `num_cpus_per_job`, `num_hosts_per_job`, `memory_per_job`.

Looking forward to hearing from you.
