### ISSUE TITLE
test.py only runs one iteration.

### ISSUE THREAD

**Issue by luckybulldozer** [JiahuiYu/generative_inpainting#54]
How do I get it to run 1000's of iterations?
When I run ```python test.py --image examples/viv_grass.png --mask examples/viv_grass.png --output examples/output.png --checkpoint model_logs/``` it seems to only do a first pass. I have a Tensorboard client running on my local machine ok, but can't seem to figure out any more due to my lack of experience here.  Any help appreciated.

**Comment by JiahuiYu** [comment]
Actually I cannot understand the question. Our method is a feed-forward neural network that only runs one iteration.
