### ISSUE TITLE
Regarding paper

### ISSUE THREAD

**Issue by himmat1121** [JiahuiYu/generative_inpainting#57]
Why you are giving mask  and clear image as input.
why not  only corrupted  image as input.

**Comment by JiahuiYu** [comment]
The inpainting task is defined as it is since 1999.

**Comment by himmat1121** [comment]
python test.py --image examples/celeba/celebahr_patches_164036_input.png --mask examples/center_mask_256.png --output examples/output.png --checkpoint_dir model_logs/release_celeba_256/




in this what is mask of image. if we don't know which part of image to inpaint.

**Comment by JiahuiYu** [comment]
You can detect masked regions first with another method, then apply both image and mask to our inpainting framework.
