### ISSUE TITLE
Is the Places2 model trained on the entire Places2 dataset or a subset?

### ISSUE THREAD

**Issue by hanrelan** [JiahuiYu/generative_inpainting#6]
Is it trained against all the categories or a subset of categories?

**Comment by JiahuiYu** [comment]
Hi, the places2 model is trained on all the categories. High-resolution image patches are used for training.

**Comment by ljjcoder** [comment]
Because i can only download Data of Places365-Standard image_list, and the Places365-Challenge image list is unvalid. like this.
![image](https://user-images.githubusercontent.com/40750189/45955862-97fbbf00-c043-11e8-83f8-7be0cae80538.png)

**Comment by JiahuiYu** [comment]
@ljjcoder I think basically they are same, as long as your downloaded images are high-resolution ones instead of resized ones.

**Comment by ljjcoder** [comment]
Data of Places365-Challenge 2016 dataset is larger than  Data of Places365-Standard. the standard have 1.8 million images but the challenge have 8 million images.
