### ISSUE TITLE
Zero epoch for two days

### ISSUE THREAD

**Issue by xaggi** [JiahuiYu/generative_inpainting#60]
Hi, 
Congratulations on successfully carrying out this great work! I am trying to train the model from scratch on ~200,000 celebA images. Apparently, its stuck at this point with no further output in 2 days (see output below). Seems it hasn't finished even first epoch so far. Is it normal? 

I have 2 GPUs installed but I am only using 1 by setting NUM_GPUS: 0 in inpaint.yml (because for 1, gpus.py was giving GPU unavailability error). Please correct me if I am wrong, but here, by 0 I remember I read an issue where you said it means one GPU.

> [2018-06-13 01:43:34 @logger.py:43] Trigger callback: Trigger WeightsViewer: logging model weights...
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv1/kernel:0, shape: [5, 5, 5, 32], size: 4000
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv1/bias:0, shape: [32], size: 32
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv2_downsample/kernel:0, shape: [3, 3, 32, 64], size: 18432
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv2_downsample/bias:0, shape: [64], size: 64
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv3/kernel:0, shape: [3, 3, 64, 64], size: 36864
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv3/bias:0, shape: [64], size: 64
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv4_downsample/kernel:0, shape: [3, 3, 64, 128], size: 73728
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv4_downsample/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv5/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv5/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv6/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv6/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv7_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv7_atrous/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv8_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv8_atrous/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv9_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv9_atrous/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv10_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv10_atrous/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv11/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv11/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv12/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv12/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv13_upsample/conv13_upsample_conv/kernel:0, shape: [3, 3, 128, 64], size: 73728
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv13_upsample/conv13_upsample_conv/bias:0, shape: [64], size: 64
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv14/kernel:0, shape: [3, 3, 64, 64], size: 36864
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv14/bias:0, shape: [64], size: 64
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv15_upsample/conv15_upsample_conv/kernel:0, shape: [3, 3, 64, 32], size: 18432
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv15_upsample/conv15_upsample_conv/bias:0, shape: [32], size: 32
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv16/kernel:0, shape: [3, 3, 32, 16], size: 4608
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv16/bias:0, shape: [16], size: 16
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv17/kernel:0, shape: [3, 3, 16, 3], size: 432
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/conv17/bias:0, shape: [3], size: 3
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv1/kernel:0, shape: [5, 5, 5, 32], size: 4000
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv1/bias:0, shape: [32], size: 32
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv2_downsample/kernel:0, shape: [3, 3, 32, 32], size: 9216
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv2_downsample/bias:0, shape: [32], size: 32
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv3/kernel:0, shape: [3, 3, 32, 64], size: 18432
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv3/bias:0, shape: [64], size: 64
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv4_downsample/kernel:0, shape: [3, 3, 64, 64], size: 36864
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv4_downsample/bias:0, shape: [64], size: 64
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv5/kernel:0, shape: [3, 3, 64, 128], size: 73728
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv5/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv6/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv6/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv7_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv7_atrous/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv8_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv8_atrous/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv9_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv9_atrous/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv10_atrous/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/xconv10_atrous/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv1/kernel:0, shape: [5, 5, 5, 32], size: 4000
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv1/bias:0, shape: [32], size: 32
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv2_downsample/kernel:0, shape: [3, 3, 32, 32], size: 9216
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv2_downsample/bias:0, shape: [32], size: 32
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv3/kernel:0, shape: [3, 3, 32, 64], size: 18432
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv3/bias:0, shape: [64], size: 64
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv4_downsample/kernel:0, shape: [3, 3, 64, 128], size: 73728
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv4_downsample/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv5/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv5/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv6/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv6/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv9/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv9/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv10/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/pmconv10/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv11/kernel:0, shape: [3, 3, 256, 128], size: 294912
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv11/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv12/kernel:0, shape: [3, 3, 128, 128], size: 147456
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv12/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv13_upsample/allconv13_upsample_conv/kernel:0, shape: [3, 3, 128, 64], size: 73728
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv13_upsample/allconv13_upsample_conv/bias:0, shape: [64], size: 64
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv14/kernel:0, shape: [3, 3, 64, 64], size: 36864
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv14/bias:0, shape: [64], size: 64
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv15_upsample/allconv15_upsample_conv/kernel:0, shape: [3, 3, 64, 32], size: 18432
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv15_upsample/allconv15_upsample_conv/bias:0, shape: [32], size: 32
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv16/kernel:0, shape: [3, 3, 32, 16], size: 4608
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv16/bias:0, shape: [16], size: 16
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv17/kernel:0, shape: [3, 3, 16, 3], size: 432
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: inpaint_net/allconv17/bias:0, shape: [3], size: 3
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_local/conv1/kernel:0, shape: [5, 5, 3, 64], size: 4800
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_local/conv1/bias:0, shape: [64], size: 64
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_local/conv2/kernel:0, shape: [5, 5, 64, 128], size: 204800
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_local/conv2/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_local/conv3/kernel:0, shape: [5, 5, 128, 256], size: 819200
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_local/conv3/bias:0, shape: [256], size: 256
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_local/conv4/kernel:0, shape: [5, 5, 256, 512], size: 3276800
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_local/conv4/bias:0, shape: [512], size: 512
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_global/conv1/kernel:0, shape: [5, 5, 3, 64], size: 4800
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_global/conv1/bias:0, shape: [64], size: 64
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_global/conv2/kernel:0, shape: [5, 5, 64, 128], size: 204800
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_global/conv2/bias:0, shape: [128], size: 128
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_global/conv3/kernel:0, shape: [5, 5, 128, 256], size: 819200
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_global/conv3/bias:0, shape: [256], size: 256
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_global/conv4/kernel:0, shape: [5, 5, 256, 256], size: 1638400
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/discriminator_global/conv4/bias:0, shape: [256], size: 256
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/dout_local_fc/kernel:0, shape: [32768, 1], size: 32768
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/dout_local_fc/bias:0, shape: [1], size: 1
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/dout_global_fc/kernel:0, shape: [65536, 1], size: 65536
> [2018-06-13 01:43:34 @weights_viewer.py:43] - weight name: discriminator/dout_global_fc/bias:0, shape: [1], size: 1
> [2018-06-13 01:43:34 @logger.py:43] Trigger callback: Total counts of trainable weights: 10674312.
> [2018-06-13 01:43:34 @weights_viewer.py:60] Total size of trainable weights: 0G 10M 184K 136B (Assuming32-bit data type.)

**Comment by JiahuiYu** [comment]
Hi, first thanks for your interest. Please check carefully of the log. You must have errors before these logs. I highly doubt that the flistnames file is not correct. Please also have a look of #15 .

**Comment by xaggi** [comment]
Thank you very much for your reply. I checked the logs and I saw the errors about missing images:

> image is None, sleep this thread for 0.1s.

I will recheck the flist names. Thank you so much!
