### ISSUE TITLE
how to finetune

### ISSUE THREAD

**Issue by minitaitang** [JiahuiYu/generative_inpainting#61]
I am very grateful to the author's contribution. Recently I have collected some pictures of the clothing of the electric business. The result is not very good, so I want to know how to make a fine tuning on the Imagenet model. Thank you very much!!!

**Comment by JiahuiYu** [comment]
Hi, fine-tuning with pre-trained imagenet model is very easy.
1. Download the released imagenet model.
2. Follow resume training subsection [here](https://github.com/JiahuiYu/generative_inpainting/tree/e923d0956d53ef7cad92331764ee469fa805daab#run).

Note that you will need to prepare file lists mentioned adobe as well.
