### ISSUE TITLE
adding new image pre-trained model

### ISSUE THREAD

**Issue by KangSH9776** [JiahuiYu/generative_inpainting#64]
hello!

We did not get good results when We trained with new 1000 images, without changing the hyper-parameters
 We are trying to fine-tune it using pre-train model.

When trying to resume training new images based on pretrained model(restored model), do i have to train with not only new images but also previous trained images or with only new images?

I want to fine tune 1,000 additional images in the pre-trained model with places dataset

Can we initialize the weight value of pre-train model to weight value of train?
 By initializing the weight value of the 'training' to the weight value of the pre-trained model, is it possible to do additional training?
 Is there another way to 'train' with the information value of 'pre-train model'?

thank you

**Comment by JiahuiYu** [comment]
I think it is fine to train with new images alone. If on your dataset the performance is not good, I have a few suggestions:
1. Could you try ImageNet pre-trained model?
2. Can you collect more images?
3. Tune the hyper-parameters as told in issue #21 #53.

**Comment by Orchid0714** [comment]
Hi, sorry to borther you. There is a problem when i try to fine-tune it using pre-trained Places model. I added 20K images to continuely train based on the pretrained model you provided, and i don't change any parameters, but it seems stuck and didn't work. So I want to know is there any error and could you give me some suggestions about fine-tune? Thanks！
------------------loading information------------------------------
- restoring variable: inpaint_net/xconv8_atrous/bias/Adam_1:0
- restoring variable: inpaint_net/xconv8_atrous/bias:0
- restoring variable: inpaint_net/xconv8_atrous/kernel/Adam:0
- restoring variable: inpaint_net/xconv8_atrous/kernel/Adam_1:0
- restoring variable: inpaint_net/xconv8_atrous/kernel:0
- restoring variable: inpaint_net/xconv9_atrous/bias/Adam:0
- restoring variable: inpaint_net/xconv9_atrous/bias/Adam_1:0
- restoring variable: inpaint_net/xconv9_atrous/bias:0
- restoring variable: inpaint_net/xconv9_atrous/kernel/Adam:0
- restoring variable: inpaint_net/xconv9_atrous/kernel/Adam_1:0
- restoring variable: inpaint_net/xconv9_atrous/kernel:0
- restoring variable: lr:0
INFO:tensorflow:Restoring parameters from logs/pretrained_model_places\snap-0
