### ISSUE TITLE
inpaint_ops / contextual attention

### ISSUE THREAD

**Issue by GeorgeKaspar** [JiahuiYu/generative_inpainting#66]
# downscaling foreground option: downscaling both foreground and
# background for matching and use original background for reconstruction.

    f = resize(f, scale=1./rate, func=tf.image.resize_nearest_neighbor)
    b = resize(b, to_shape=[int(raw_int_bs[1]/rate), int(raw_int_bs[2]/rate)], func=tf.image.resize_nearest_neighbor)  # https://github.com/tensorflow/tensorflow/issues/11651

It should be raw_int_fs instead of raw_int_bs because of mathing b and f
Moreover if you try python inpaint_ops.py on images which have different shapes it will be error at offsets.set_shape(int_bs[:3] + [2])

**Comment by JiahuiYu** [comment]
Usually f and b are with same size in contextual attention. Contextual attention is a self-attention mechanism.
