### ISSUE TITLE
ValueError: Dimension 1 in both shapes must be equal, but are 166 and 64. Shapes are [1,166,250,2] and [1,64,64,2].

### ISSUE THREAD

**Issue by c1a1o1** [JiahuiYu/generative_inpainting#67]
inpaint_ops.py --imageA examples/style_transfer/bnw_butterfly.png  --imageB examples/style_transfer/bike.jpg --imag

 File "D:/work/work11/generative_inpainting-master/inpaint_ops.py", line 313, in contextual_attention
    offsets.set_shape(int_bs[:3] + [2])
  File "C:\Users\caocao\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 538, in set_shape
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 166 and 64. Shapes are [1,166,250,2] and [1,64,64,2].

**Comment by akshay951228** [comment]
how did you solve this issue I got the same issue

**Comment by devkicks** [comment]
How did you solve this?
