### ISSUE TITLE
neuralgym.get_gpus(1) return null gpu

### ISSUE THREAD

**Issue by merria28** [JiahuiYu/generative_inpainting#69]
I run test.py which points out “Error reading GPU information, set no GPU.” Actually, my computer has one GPU： GeForce GT 710, and I have run some tensorflow-based programs on it.

Can you give me some advice?

tensorflow 1.8+cuda 9+ cudnn7

**Comment by JiahuiYu** [comment]
Please try to remove line:
neuralgym.get_gpus(1) 

This line simply auto-selects an available GPU to use. Removing it will not affect performance.
