### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by pavibalaji** [JiahuiYu/generative_inpainting#7]
When I try to run the inference with test.py using the given command for CelebA 256 HQ images from the examples, I get the following error

File "/home/tbalaji/.local/lib/python2.7/site-packages/neuralgym/utils/config.py", line 21
    class Loader(yaml.Loader, metaclass=LoaderMeta):
                                       ^
SyntaxError: invalid syntax

Please guide me with fixing this.
I am using python 2.7 with TensorFlow 1.3 in Virtual env. Thanks

**Comment by JiahuiYu** [comment]
Hi this may due to python version. Please consider use python3 for testing. Sorry for the trouble and I have updated document for python3 only.

**Comment by csxmli2016** [comment]
I have the same problem. @pavibalaji. After using python3, it works!

**Comment by NerminSalem** [comment]
python3 test.py --image examples/celeba/celebahr_patches_164036_input.png --mask examples/center_mask_256.png --output examples/output.png --checkpoint_dir model_logs/
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    import neuralgym as ng
ImportError: No module named 'neuralgym'
 can u tell me how to install neuralgym?
thanks alot

**Comment by JiahuiYu** [comment]
@NerminSalem Please take a reference at issue #102 . Also please carefully read the instructions for test.
