### ISSUE TITLE
How does the fixed mask generated?

### ISSUE THREAD

**Issue by codaibk** [JiahuiYu/generative_inpainting#70]
Hi, Thank for your work.
I want to generate the fixed mask for my image with the mask's size = 1/2 image's size and the mask is on the right side of original image.
so what i should change to get that because so far your code generate random mask in r`andom_bbox` and `bbox2mask` function.
Original
![image](https://user-images.githubusercontent.com/28720676/42256770-a33cb2a6-7f85-11e8-9bd3-6af6fdd04894.png)

mask
![image](https://user-images.githubusercontent.com/28720676/42256673-422462a2-7f85-11e8-8f8b-7f35e29cffb4.png)
Thanks

**Comment by JiahuiYu** [comment]
You just need to change `random_bbox` and `bbox2mask` function by fixing the return results as your requirements. See lines [here](https://github.com/JiahuiYu/generative_inpainting/blob/3e915bcad4645c5a84defcd87195225d8289cf0d/inpaint_ops.py#L111-L117) where the output represents (top, left, height, width) bounding box.

**Comment by codaibk** [comment]
Yes. I am trying to change 2 those functions.
btw, can you explain 2 variables `delta_h `and `delta_w` used for what in these lines ?
h = np.random.randint(delta_h//2+1)
w = np.random.randint(delta_w//2+1))`
Thanks

**Comment by JiahuiYu** [comment]
@codaibk Hi, `delta_h` and `delta_w` is a way to random sample the aspect ratio of bounding box in our case. I believe in your case, you can simply set them to 0.

**Comment by codaibk** [comment]
@JiahuiYu . Hi , Thanks for your reply
About the fixed mask, i saw the result from tensorboard. it seems not every my mask is correct (it is shown in `static view `in the follow pict)
- The result with` raw_incomplete_predicted_complete`
![image](https://user-images.githubusercontent.com/28720676/42391254-586e6622-8181-11e8-840b-285fc5f4a1dc.png)
- The result with `statuc view`
![image](https://user-images.githubusercontent.com/28720676/42391274-6f811efe-8181-11e8-8fbe-278f66a7c94a.png)
- do you have any suggestion?
- This my code in `random_bbox `and `bbox2mask` function
```
def random_bbox(config):
    t = tf.constant(0)
    l = tf.constant(256)
    h = tf.constant(config.HEIGHT)
    w = tf.constant(config.WIDTH)
    return (t, l, h, w)
def bbox2mask(bbox, config, name='mask'):
    def npmask(bbox, height, width, delta_h, delta_w):
        mask = np.zeros((1, height, width, 1), np.float32)
        h = 0 
        w = 0
        mask[:, bbox[0]+h:bbox[0]+bbox[2]-h,
             bbox[1]+w:bbox[1]+bbox[3]-w, :] = 1.
        return mask
    with tf.variable_scope(name), tf.device('/cpu:0'):
        img_shape = config.IMG_SHAPES
        height = img_shape[0]
        width = img_shape[1]
        mask = tf.py_func(
            npmask,
            [bbox, height, width,
             config.MAX_DELTA_HEIGHT, config.MAX_DELTA_WIDTH],
            tf.float32, stateful=False)
        mask.set_shape([1] + [height, width] + [1])
    return mask

```

**Comment by xuyifeng-nwpu** [comment]
@codaibk  Why can not change the mask picture directly?
How to assign random_bbox value for bbox?   
Thanks.

**Comment by codaibk** [comment]
@xuyifeng-nwpu Because in this project, they generate the mask using bounding box. Therefore, you need to change `random_bbox `and `bbox2mask` functions to get your expected mask. and [here](https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint_model.py#L290-L291). just need to change these 2 lines by calling random_bbox function : `bbox = random_bbox(config)`

**Comment by xuyifeng-nwpu** [comment]
@codaibk 
If we test the random_bbox inpainting, do we need change the code  `--mask examples/center_mask_256.png` in the below code?

# ImageNet 256x256 input
python test.py --image examples/imagenet/imagenet_patches_ILSVRC2012_val_00000827_input.png --mask examples/center_mask_256.png --output examples/output.png --checkpoint_dir model_logs/release_imagenet_256

**Comment by codaibk** [comment]
@xuyifeng-nwpu i dont understand what you mean. Do you mean you will have random mask which is not same with this project? if yes, from my understanding, you need to change `--mask examples/center_mask_256.png` with corresponding mask in your case.

**Comment by xuyifeng-nwpu** [comment]
@codaibk 
When we  inpaint the right half part, did the mask picture set as follows?
![center_mask_256](https://user-images.githubusercontent.com/21265053/42580142-79a55e7a-855c-11e8-86fc-42456200558f.png)
explain:left black, right white.

The input image and  result show as follows:
input:
![009_im](https://user-images.githubusercontent.com/21265053/42580358-e550ff08-855c-11e8-9b77-ad831565d635.png)
the output:
![output](https://user-images.githubusercontent.com/21265053/42580371-f00ba2d6-855c-11e8-8c80-76da3bdfb704.png)

My result is not nice. How about your half-inpainting effect?
Do you use qq or wechat? I think you are a Chinese.

**Comment by codaibk** [comment]
@xuyifeng-nwpu. I am still running my model. it haven't finish yet. I think your mask is correct. Maybe you can ask the author of this paper about your result.
Btw, i am not chinese :)

**Comment by xuyifeng-nwpu** [comment]
Do you re-train your data?   I only use the author's imagenet model. I guess that the large area(half) inpainting of many categories of image maybe have not good result, especially on the edge of the image.   If you try the experiment in  a few kind  of image(such as skirt) , the model may be effective.  I look forward to your good results. Tell me please!

**Comment by JiahuiYu** [comment]
@codaibk Thanks for your help and answers to others! I appreciate!

@xuyifeng-nwpu Have you trained your model on your dataset with your masks?

**Comment by xuyifeng-nwpu** [comment]
@JiahuiYu 
Have you trained your model on your dataset with your masks? NO, now. I will train with my pictures.
The green apple image is selected from imagenet dataset. 
The test model is your imagenet model.  I guess that the large area inpainting is difficult.

**Comment by JiahuiYu** [comment]
@xuyifeng-nwpu Thanks for your information. During training, the largest mask width/height is half of image size. Which means if image is `256x256`, the maximum of mask during training is `128x128`. I guess that's the reason why it fails in your case (`128x256`). Because it never saw such mask during training.

**Comment by JiahuiYu** [comment]
@xuyifeng-nwpu But I have seen (in email) one who also tries to inpainting half of an image like yours. The performance is pretty good and I guess this code repo should work for your requirements. Just a reference.

**Comment by xuyifeng-nwpu** [comment]
@JiahuiYu 
Could you tell  me whether the good result (in email) generated by your model or other's retrain model?
Thanks!

**Comment by xuyifeng-nwpu** [comment]
@codaibk 
Hi, I have a question. If i retrain my dataset for right-half inpainting(128x256), should I change the inpaint_model.py?  Can you tell me how to change?

**Comment by JiahuiYu** [comment]
Hi the one retrain on half masks. To change, you need to understand how masks in this code are generated. There are related issues that may help you. (Sorry I am use phone to reply you thus can not point out the referenced issue.)
