### ISSUE TITLE
save checkpoint

### ISSUE THREAD

**Issue by KangSH9776** [JiahuiYu/generative_inpainting#71]
I want to save 'c' every 10 epochs during training. Which parts of the code should be modified?
thank you.

**Comment by JiahuiYu** [comment]
You can simply change the line [here](https://github.com/JiahuiYu/generative_inpainting/blob/3e915bcad4645c5a84defcd87195225d8289cf0d/inpaint.yml#L23) to the number of iterations you want.

For your reference, you might be interested in reading following [code](https://github.com/JiahuiYu/generative_inpainting/blob/master/train.py#L108).
