### ISSUE TITLE
How can check the result of mask, input image, result of stage 1 and result of stage 2 in training

### ISSUE THREAD

**Issue by codaibk** [JiahuiYu/generative_inpainting#72]
Hi,
I want to ask question about how i can see the result of mask, input image, result stage 1 and stage 2 in every epoch or iteration when training model ?
Thanks

**Comment by JiahuiYu** [comment]
Hi it is very simple. Please check: https://github.com/JiahuiYu/generative_inpainting/blob/3e915bcad4645c5a84defcd87195225d8289cf0d/inpaint_model.py#L151
You can view a few results directly in tensorboard. You can extract all results from tensorboard logs. See [here](https://stackoverflow.com/questions/47232779/how-to-extract-and-save-images-from-tensorboard-event-summary).

**Comment by codaibk** [comment]
Hi, Thanks for your reply
Actually, i am beginner of using tensorboard. so I dont know how to extract image from tensorboard. so far, i got my model and my tensorboard log just like the following pict. 
![image](https://user-images.githubusercontent.com/28720676/42385093-66c5e38e-816e-11e8-9496-a3c07d17d4ba.png)

Could you give me more direction to extract the image?
Thanks

**Comment by dulibubai** [comment]
Hi!As mentioned in the paper,you use the standard split of the celebA dataset, can you give me the list of the standard img_name_list of trainset, valset,and testset? I have found the standard split so long ,but failed!  Thanks very much!  Look forward to your reply!

**Comment by JiahuiYu** [comment]
@dulibubai http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html
Search 1Train/Val/Test Partitions`. It is so straight forward actually...

**Comment by dulibubai** [comment]
But I cant't download the file about the standard split of train,validation and test data,the link is not accessible.

**Comment by JiahuiYu** [comment]
@dulibubai You probably need to email cuhk for information. Currently I did not have filelist on hand (busying with other projects for conference ddl).

**Comment by dulibubai** [comment]
Thanks again!
