### ISSUE TITLE
question about deconvlution kernel size in contextual attention

### ISSUE THREAD

**Issue by han-qiu** [JiahuiYu/generative_inpainting#73]
kernel = 2*rate
    raw_w = tf.extract_image_patches(
        b, [1,kernel,kernel,1], [1,rate*stride,rate*stride,1], [1,1,1,1], padding='SAME')
for convolution, the kernel size is 3, but for deconvolution, why the kernel is `2*rate=4` with `stride=rate`?
why not use `3*3` kernel? Is there a reason for that?

**Comment by JiahuiYu** [comment]
Yes there is a reason. Please check others work [here](https://distill.pub/2016/deconv-checkerboard/).
