### ISSUE TITLE
question about SPATIAL_DISCOUNTING_GAMMA

### ISSUE THREAD

**Issue by han-qiu** [JiahuiYu/generative_inpainting#74]
quoted from the paper: `gamma is set to 0.99 in all experiment`
about in inpaint.yml
`SPATIAL_DISCOUNTING_GAMMA: 0.9`

So have you tested which is better, 0.9 or 0.99? or it doesn't matter?

**Comment by JiahuiYu** [comment]
We did test and `0.9` is better than `1.0`. So I still suggest you use `0.9` for training images with resolution of `256x256`.

**Comment by han-qiu** [comment]
JiahuiYu, thank you for your answer, another question, for deepfill2 do you use spatial discounting for freeform mask?
