### ISSUE TITLE
test.py Input Image size manipulation

### ISSUE THREAD

**Issue by unlugi** [JiahuiYu/generative_inpainting#76]
Thank you for your work.
My question is about the input image size manipulation done during the test.py in the following code segment:
` h, w, _ = image.shape`
`grid = 8` 
` image = image[:h//grid*grid, :w//grid*grid, :]`
 `mask = mask[:h//grid*grid, :w//grid*grid, :]`
` print('Shape of image: {}'.format(image.shape))`

I have run the code without these lines but of course I got errors. I could not understand the reason for this manipulation. Thank you.

**Comment by JiahuiYu** [comment]
@unlugi Hi, that is for upsample purpose of neural network. There are two downsample layers in our generative network. You can simply do some mirror padding if you want to keep all information as input.
