### ISSUE TITLE
Are the released model full trained?

### ISSUE THREAD

**Issue by 1900zyh** [JiahuiYu/generative_inpainting#77]
Hi Jiahui,

Thanks for your work very much! It's wonderful !
And I wonder are the released model full trained? I tested the release_imagenet_256 model in some cases as below

![don_diego_1024](https://user-images.githubusercontent.com/7473216/42355746-34e6d002-8101-11e8-95e6-04c231a0b88a.jpg)
![don_diego_1024](https://user-images.githubusercontent.com/7473216/42355753-3958bbfa-8101-11e8-9ab2-568d197a96ad.jpg)
![finger](https://user-images.githubusercontent.com/7473216/42355758-44e93756-8101-11e8-97f2-559750163c8a.jpg)
![finger](https://user-images.githubusercontent.com/7473216/42355763-49db1d4c-8101-11e8-920b-d5d155a0cb4f.jpg)

They looks not very good. And I think these are simple case, because the masked region are mostly background.  Do you have any idea why it failed in such cases ?

**Comment by JiahuiYu** [comment]
@1900zyh Hi, thanks for your interest. I wonder where are the masks in your cases? It seems the masks are irregular?

**Comment by 1900zyh** [comment]
@JiahuiYu  Yes, the masks are irregualr. As the previous image in each group show, the mask is irregular in the left top region of the image. 

Here are more cases on coco with "person" mask:
![18519](https://user-images.githubusercontent.com/7473216/42361695-53dc45b6-8122-11e8-84a9-08ca090ae262.jpg)
![18519](https://user-images.githubusercontent.com/7473216/42361703-5b35c468-8122-11e8-97be-ca4d65cb03a6.jpg)
![243148](https://user-images.githubusercontent.com/7473216/42361723-7189b922-8122-11e8-84e7-f4492ef61628.jpg)
![243148](https://user-images.githubusercontent.com/7473216/42361740-7e4bee6e-8122-11e8-8627-9a62a6fbfdc9.jpg)


They also generates something strange inside missing regions.

**Comment by JiahuiYu** [comment]
For irregular masks, please checkout our recent work of DeepFill v2: Free-Form image Inpainting with gated convolution.
