### ISSUE TITLE
Different GAN Loss

### ISSUE THREAD

**Issue by unlugi** [JiahuiYu/generative_inpainting#78]
Hello,
Is it possible to modify the code for a loss different than wasserstein? 
Thank you.

**Comment by JiahuiYu** [comment]
Sure. Please check code [here](https://github.com/JiahuiYu/generative_inpainting/blob/3e915bcad4645c5a84defcd87195225d8289cf0d/inpaint_model.py#L197-L225). You can implement any GAN loss.
