### ISSUE TITLE
Batch Inpainting

### ISSUE THREAD

**Issue by zzzace2000** [JiahuiYu/generative_inpainting#8]
Thank you for shaing your code!

I am trying to do batch infilling but I find it crashes in the function 'contextual_attention' in the file inpaint_op.py. I run the test.py with batch size set as 5, then I get the error:

``
 "/home/zzzace2000/Googledrive/Lab/nl_markov_network/exp/vbd_imagenet/generative_inpainting/inpaint_ops.py", line 308, in contextual_attention
    strides=[1,rate,rate,1]) / 4.
  File "/home/zzzace2000/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1187, in conv2d_transpose
    filter.get_shape()[3]))
ValueError: input channels does not match filter's input channels, 5120 != 1024
``

If I set the batch size as 1, the code runs flawlessly.
I can see from the code that it should be able to handle situation when batch size > 1.
Can you let me know where I might get it wrong?

Thank you!

**Comment by zzzace2000** [comment]
Thanks for the quick reply!
I just modify the input image from (1, 256, 512, 3) to (2, 256, 512, 3) by adding this line.
``
input_image = np.concatenate([input_image, input_image], axis=0)
print('Final shape:', input_image.shape)
``
And I get the following error:
``
Shape of image: (256, 256, 3)
Final shape: (2, 256, 512, 3)
Traceback (most recent call last):
  File "test.py", line 49, in <module>
    output = model.build_server_graph(input_ph)
  File "/home/zzzace2000/Googledrive/Lab/nl_markov_network/exp/vbd_imagenet/generative_inpainting/inpaint_model.py", line 307, in build_server_graph
    config=None)
  File "/home/zzzace2000/Googledrive/Lab/nl_markov_network/exp/vbd_imagenet/generative_inpainting/inpaint_model.py", line 97, in build_inpaint_net
    x, offset_flow = contextual_attention(x, x, mask_s, 3, 1, rate=2)
  File "/home/zzzace2000/Googledrive/Lab/nl_markov_network/exp/vbd_imagenet/generative_inpainting/inpaint_ops.py", line 309, in contextual_attention
    strides=[1,rate,rate,1]) / 4.
  File "/home/zzzace2000/anaconda2/envs/py36/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1187, in conv2d_transpose
    filter.get_shape()[3]))
ValueError: input channels does not match filter's input channels, 2048 != 1024
``

It seems that my final input image shape is (2, 256, 512, 3). Do I make a mistake here?

Thank you!

**Comment by JiahuiYu** [comment]
I see. Although the current implementation of `contextual_attention` support batch mode, the mask in each batch is with shape [1, H, W, 1], which means each batch share the same mask.

If this is your case, please checkout this commit bd73aebf3afbacd8757a73fd19159080323631bb to run batch inpainting (you will need to modify `test.py` to save batch images).

**Comment by zzzace2000** [comment]
Thank you for your help!

Is it possible to run multiple masks within one batch? I need this functionality to speed up.
Can you give me some hints about how I could do that?

Thank you!

**Comment by JiahuiYu** [comment]
Sure, but it need some modification of `contextual_attention`. Another naive approach is to:

1. build a static tensorflow graph using placeholder,
2. load model, and
3. feed your images and masks as feed_dict one by one.

That's the way how current [demo](jhyu.me/demo) is built. It is fast (less than 0.1s) on server side for an image with resolution 256x256.
