### ISSUE TITLE
The mode did not Resume from checkpoint

### ISSUE THREAD

**Issue by codaibk** [JiahuiYu/generative_inpainting#80]
Hi, I tried to resume my model when training but it didnt load my `checkpoint` to continue train the model. It will start from beginning with epoch 0. I changed my `MODEL_RESTORE `in inpaint.yml file [here](https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint.yml#L6) for sure.
Do i need to do anything to make model continue training with my checkpoint?
This is my `checkpoint `folder
![image](https://user-images.githubusercontent.com/28720676/42559864-e8daf9ce-8527-11e8-82d7-6b85ccf8af46.png)
Thanks

**Comment by JiahuiYu** [comment]
Currently I just use a different directory when resume training, which means new logs and checkpoints will be saved to new directory.

**Comment by codaibk** [comment]
@JiahuiYu Save in new directory is ok but i mean it doesn't continue train from my checkpoint. Example my first training is at epoch 9, then i stopped the training then resume the training again but it will start from epoch 1 instead of epoch 9.  So it means everything start from beginning again

**Comment by JiahuiYu** [comment]
No. Resume means that the pretrained weights/parameters are restored. It is not about which epoch or iteration to begin with. It is useful when you want to use this API to fine-tune on other datasets.
