### ISSUE TITLE
How to generate input for testing

### ISSUE THREAD

**Issue by codaibk** [JiahuiYu/generative_inpainting#81]
Hi, I saw you input the args when testing (corrupted image, mask). 
`python test.py --image examples/input.png --mask examples/mask.png --output examples/output.png --checkpoint model_logs/your_model_dir`
I want to ask how you generate these images files? what tool do you use?
Thanks,

**Comment by JiahuiYu** [comment]
You mean the mask files or image files? Basically `image file = original image * mask file`, where `*` means element-wise multiplication.

**Comment by codaibk** [comment]
@JiahuiYu Hi, I mean the mask file (black and white image), do you use the tool or some code to create it? can you share it to me. Thanks

**Comment by JiahuiYu** [comment]
The mask is generated with python numpy by setting bounding box to ones according to x,y-axis. The the numpy array is saved as an image using opencv.

**Comment by codaibk** [comment]
@JiahuiYu . Hi, i followed your guiding ` image file = original image * mask ` for generate image files from mask for testing but it seems it is wrong
This is mask : 
![center_mask_256](https://user-images.githubusercontent.com/28720676/42756363-56ec8b8a-892e-11e8-8928-04f563767459.png)
Original Image : 
![celeba](https://user-images.githubusercontent.com/28720676/42756373-5fa6018e-892e-11e8-91f9-0ddef543a0b7.jpg)
and the image file result : 
![inpaint](https://user-images.githubusercontent.com/28720676/42756391-6a6e4b3a-892e-11e8-8ea4-57d147538771.png)

i just use simple code with element-wise multiplication in python
```
from skimage import io
import cv2
import numpy as np
img = io.imread("celeba.jpg")

mask = io.imread("center_mask_256.png")
inpaint = np.multiply(img,mask)
cv2.imwrite("inpaint.png",inpaint)

```

**Comment by codaibk** [comment]
@JiahuiYu Please help me to answer this one because i want to test my new model so i need to generate the mask file and image which is input for testing
Thanks

**Comment by JiahuiYu** [comment]
After reading mask as numpy array, the values are between 0-255. Thus you should divide by 255 after np.multiply.

**Comment by codaibk** [comment]
@JiahuiYu The result is still wrong after dividing with 255
