### ISSUE TITLE
test pretrain model on celebA are strange

### ISSUE THREAD

**Issue by ljjcoder** [JiahuiYu/generative_inpainting#82]
Hi, Jiahui! i want to test the pretrain model on celebA. I download the pretrain model of celebA and put it at ./model_logs/celebA_model. 
   when I run  python test.py --image examples/celeba/celebahr_patches_164787_input.png --mask examples/center_mask_256.png --output examples/output.png --checkpoint_dir model_logs/celebA_model
,I get the very bad result.
![celebahr_patches_164787_input](https://user-images.githubusercontent.com/40750189/42636183-ad4bf266-861a-11e8-838c-5f20d5c38377.png)

![output3_pretrain](https://user-images.githubusercontent.com/40750189/42635264-306d1b32-8618-11e8-9e08-383745fc9332.png)
I don't know why it happens. can you help me?

**Comment by JiahuiYu** [comment]
Did you figure out why?

**Comment by Gavin666Github** [comment]
here ,my result ,haha,,it's funny
![image](https://user-images.githubusercontent.com/35061171/43255054-5fffdc20-90fb-11e8-96b2-bf15d28b657f.png)

![image](https://user-images.githubusercontent.com/35061171/43255068-691941fc-90fb-11e8-8d40-259fcb1b4853.png)
