### ISSUE TITLE
Is   the white  square hole in the middle of the  input image necessary?

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [JiahuiYu/generative_inpainting#83]
`python test.py --image examples/input.png --mask examples/mask.png --output examples/output.png --checkpoint model_logs/your_model_dir`
The  input image for demo in upper code (input.png) has the white square hole.

Is the square hole necessary or only for clearer demo?

**Comment by JiahuiYu** [comment]
The models in first version (DeepFill v1) are mainly trained on square holes. Please checkout DeepFill v2 as referred in README for free-form masks.

**Comment by xuyifeng-nwpu** [comment]
I have not expressed clearly.
If we input a complete image( has not the hole) to the model in the process of testing, the test algorithm will at first automatically start a square white hole?
Your input test image for demo has the white square hole. Is it only for users to see the effect more clearly?

**Comment by JiahuiYu** [comment]
The algorithm will automatically set the input as: `input image * (1 - mask image)` since 1 indicating the missing pixels. See code [here](https://github.com/JiahuiYu/generative_inpainting/blob/3e915bcad4645c5a84defcd87195225d8289cf0d/inpaint_model.py#L262).

**Comment by Adhiyaman-Manickam** [comment]
@xuyifeng-nwpu Hi. if possible can you let me know about the input, mask images to test.py. i am confusing.

**Comment by xuyifeng-nwpu** [comment]
No，  I  place  the hole at the left and the right.------------------ 原始邮件 ------------------
发件人: "Adhiyaman-Manickam"<notifications@github.com>
发送时间: 2019年11月6日(星期三) 下午3:26
收件人: "JiahuiYu/generative_inpainting"<generative_inpainting@noreply.github.com>;
抄送: "xuyifeng-nwpu"<42805959@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [JiahuiYu/generative_inpainting] Is   the white  square hole inthe middle of the  input image necessary? (#83)



@xuyifeng-nwpu Hi. if possible can you let me know about the input, mask images to test.py. i am confusing.
 
&mdash;
