### ISSUE TITLE
test image

### ISSUE THREAD

**Issue by Jason-xin** [JiahuiYu/generative_inpainting#90]
Sorry to bother you...
Your test image is mask.png + image_with_mask.png
Maybe mask.png + raw_image.png is also OK?

**Comment by JiahuiYu** [comment]
Yes. Please see this [code](https://github.com/JiahuiYu/generative_inpainting/blob/3e915bcad4645c5a84defcd87195225d8289cf0d/inpaint_model.py#L262).
