### ISSUE TITLE
Contextual Attention Layer

### ISSUE THREAD

**Issue by xaggi** [JiahuiYu/generative_inpainting#91]
Hi, I am trying to understand the contextual attention layer and its back-propagation mechanism. My question is, if we extract patches (or filters) for each image separately then what is the network learning here?  Please if you can provide me some more details or any supporting material about it (in addition to what is mentioned in the paper), I will be thankful to you.

Further more in connection to this, I was checking the code and I noticed that there is a 'training' flag in the function arguments but it is not used anywhere.

**Comment by JiahuiYu** [comment]
Hi, this is actually a very good question! If there is no parameters, how can we learn and what is the network learning?
Although there is no parameter in contextual attention layer, there is parameters/conv layers before contextual attention layer. Thus you can think that the network learning to mapping the input into a **feature space**, in which the contextual attention (for matching and pasting) works best.

Also for `training` flag, it is mainly an API that is consistent to other layers. It is currently not used in contextual attention layer. But I choose to keep this API anyway.

Let me know if you have future questions.

**Comment by xaggi** [comment]
Thank you very much for the prompt answer. Actually this line: "The contextual attention layer learns where to borrow or copy feature information from known background patches to generate missing patches." from your paper is suggesting that some kind of learning is involved in this layer.

**Comment by 1900zyh** [comment]
Hi Jiahui,
I'm trying to understand the details of contextual attention 
I don't understand why the results of [conv2d_transpose](https://github.com/JiahuiYu/generative_inpainting/blob/master/inpaint_ops.py#L307) need to be divided by 4?

The filter_size its 4X4, and why not divided by 16?
