### ISSUE TITLE
MultiGPUTrainer

### ISSUE THREAD

**Issue by GeorgeKaspar** [JiahuiYu/generative_inpainting#92]
Hi
This issue more convenient for neuralgym framework but when I use both of MultiGPUTrainer and SecondaryMultiGPUTrainer I got the deadlock
How can I place both of generator and discriminator at GPU?

**Comment by JiahuiYu** [comment]
They are automatically on all GPUs. I see communities have successfully used multiGPU. Please have a search of existing issues, which may help.
