### ISSUE TITLE
Loss with x2

### ISSUE THREAD

**Issue by GeorgeKaspar** [JiahuiYu/generative_inpainting#94]
Why did you use ae_loss and l1_loss with x2
Is it smooth results?

**Comment by JiahuiYu** [comment]
Please have a look at the code inside model build graph function. It is more clear to see difference with code.

**Comment by yang502** [comment]
So the l1 loss and ae_loss are treated as a weight sum of the reconstruction loss, to set different mask weight in inpainting region and other regions ?

**Comment by JiahuiYu** [comment]
@yang502 Yes it is an option in our code.
