### ISSUE TITLE
about loss

### ISSUE THREAD

**Issue by Lsiming** [JiahuiYu/generative_inpainting#98]
First of all, thank you for sharing the project. I would like to ask about the problem of setting superparameters. Do you have any detailed analysis materials on the effects of the following four parameters on the training results
WGAN_GP_LAMBDA: 10
COARSE_L1_ALPHA: 1.3
L1_LOSS_ALPHA: 1.3
AE_LOSS_ALPHA: 1.3

**Comment by JiahuiYu** [comment]
Hi, Please have a look of these issues #21 and #53. Basically if the result is blurry, we hypotheses that the pixel-wise loss is too large. Then we consider set lower pixel-wise loss weights, e.g., set 0.5 to COARSE_L1_ALPHA, L1_LOSS_ALPHA, AE_LOSS_ALPHA.
