### ISSUE TITLE
Question about HED

### ISSUE THREAD

**Issue by powder21** [JiahuiYu/generative_inpainting#99]
Hi, Jiahui. I read your new paper 'Free-Form Image Inpainting with Gated Convolution', and mentioned that sketch was got by HED with threshold 0.6. You used the caffe model from HED's author or trained by yourself, and how did you get binary edge from the output?

**Comment by JiahuiYu** [comment]
Binary edge is set to 1 if output is greater than `0.6`, otherwise set to 0. What's your question? I use official pre-trained caffe model (converted to tf by myself).

**Comment by powder21** [comment]
I mean there is NMS and edge thining for official HED output, did you do the same? Then, how did you convert caffe model to tf, some toolbox or trained the same model in tf by yourself?
